apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexusarchive.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "nexusarchive.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: http
