package com.nexusarchive.integration.yonsuite.service;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.util.StrUtil;
import cn.hutool.http.HttpRequest;
import cn.hutool.json.JSONArray;
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;
import com.nexusarchive.common.exception.BusinessException;
import com.nexusarchive.integration.erp.dto.ErpConfig;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * YonBIP 资金结算 - 电子回单/付款单文件服务
 * <p>
 * Generated by NexusArchive AI Agent (Pass 2: Code Generation)
 * Based on SIM JSON: yonbip_payment_file_sim.json
 * Source Doc: 2025-12-05 17:29:14 Update
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class YonPaymentFileService {

    private final YonAuthService yonAuthService;

    private static final String API_PATH = "/yonbip/EFI/payment/file/url";
    private static final int MAX_BATCH_SIZE = 20; // 接口限制最大请求量 20

    /**
     * 批量获取付款单文件下载地址
     *
     * @param config   ERP配置 (需包含 accessToken)
     * @param fileIds  文件ID列表
     * @return 文件ID -> 下载URL 的映射
     */
    public List<JSONObject> getPaymentFileUrls(ErpConfig config, List<String> fileIds) {
        if (CollUtil.isEmpty(fileIds)) {
            return Collections.emptyList();
        }

        // 1. 初始化结果集
        List<JSONObject> results = new ArrayList<>();
        String accessToken = getAccessToken(config);
        String baseUrl = extractBaseUrl(config.getBaseUrl());
        String fullUrl = baseUrl + API_PATH;

        // 2. 分批处理 (Max 20 per request)
        List<List<String>> batches = CollUtil.split(fileIds, MAX_BATCH_SIZE);
        log.info("准备获取付款单文件URL，总数: {}, 分批数: {}", fileIds.size(), batches.size());

        for (List<String> batch : batches) {
            try {
                // 3. 构建请求体
                JSONObject payload = JSONUtil.createObj();
                payload.set("fileId", batch);

                // 4. 发送 HTTP POST 请求
                String responseBody = HttpRequest.post(fullUrl)
                        .form("access_token", accessToken) // Query Param
                        .body(payload.toString())
                        .timeout(10000)
                        .execute()
                        .body();

                // 5. 解析响应
                List<JSONObject> batchResults = parseResponse(responseBody);
                results.addAll(batchResults);

            } catch (Exception e) {
                log.error("获取付款单文件URL失败 (Batch: {}): {}", batch, e.getMessage());
                // 策略：记录错误但不中断其他批次
            }
        }

        return results;
    }

    private String getAccessToken(ErpConfig config) {
        // 使用已配置的 YonAuthService 获取 Token (带缓存 + 自动刷新)
        return yonAuthService.getAccessToken(config.getAppKey(), config.getAppSecret());
    }

    private String extractBaseUrl(String configUrl) {
        // 确保 URL 格式正确 (去除末尾斜杠)
        return StrUtil.removeSuffix(configUrl, "/");
    }

    private List<JSONObject> parseResponse(String jsonStr) {
        try {
            JSONObject response = JSONUtil.parseObj(jsonStr);
            String code = response.getStr("code");
            
            if (!"200".equals(code)) {
                String msg = response.getStr("message", "Unknown Error");
                log.warn("YonBIP API Error: Code={}, Message={}", code, msg);
                return Collections.emptyList();
            }

            JSONArray data = response.getJSONArray("data");
            if (CollUtil.isEmpty(data)) {
                return Collections.emptyList();
            }

            return data.toList(JSONObject.class);

        } catch (Exception e) {
            log.error("解析 YonBIP 响应 JSON 失败", e);
            return Collections.emptyList();
        }
    }
}
