// Input: 无
// Output: DA/T 92—2022《电子档案单套管理一般要求》 全量高排版版
// Pos: /Users/user/nexusarchive/src/pages/product-website/regulations/DAT92Spec.tsx

import React from 'react';
import { RegulationLayout } from './RegulationLayout';

export const DAT92Spec: React.FC = () => {
  return (
    <RegulationLayout 
        title="DA/T 92—2022《电子档案单套管理一般要求》"
        category="核心要求"
        source="国家标准/行业规范"
        effectiveDate="2022-07-01"
    >
      <div className="regulation-content font-serif leading-relaxed text-slate-300 max-w-none">
<p className="mb-2 indent-0">ICS01.140.20</p>
<p className="mb-2 indent-0">CCSA</p>
<div className="h-4" />
<p className="mb-2 indent-0">14</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">中华 人民 共和 国档 案行 业标 准</h3>
<p className="mb-2 indent-0">DA/T 92—2022</p>
<p className="mb-2 indent-0">电子档案单套管理一般要求</p>
<p className="mb-2 indent-0">General</p>
<div className="h-4" />
<p className="mb-2 indent-0">requirements</p>
<div className="h-4" />
<p className="mb-2 indent-0">for</p>
<div className="h-4" />
<p className="mb-2 indent-0">the</p>
<div className="h-4" />
<p className="mb-2 indent-0">single</p>
<div className="h-4" />
<p className="mb-2 indent-0">set</p>
<div className="h-4" />
<p className="mb-2 indent-0">filing</p>
<div className="h-4" />
<p className="mb-2 indent-0">management</p>
<div className="h-4" />
<p className="mb-2 indent-0">of</p>
<div className="h-4" />
<p className="mb-2 indent-0">electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">records</p>
<p className="mb-2 indent-0">2022-04-07发布 2022-07-01实施</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">国家档案局发 布 341</h3>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">前言</p>
<p className="mb-2 indent-0">本文件按照 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">1.1—2020《标准化工作导则第1部分:标准化文件的结构和起草规则》的规定</p>
<p className="mb-2 indent-0">起草。</p>
<p className="mb-2 indent-0">请注意本文件的某些内容可能涉及专利。本文件的发布机构不承担识别专利的责任。</p>
<p className="mb-2 indent-0">本文件由国家档案局提出并归口。</p>
<p className="mb-2 indent-0">本文件起草单位:国家档案局档案馆(室)业务指导司、福建省档案馆、福建省档案局。</p>
<p className="mb-2 indent-0">本文件主要起草人:刘芸、黄建峰、丁德胜、宁鹏飞、郑志荣、袁平、陈义群。</p>
<p className="mb-2 indent-0">541</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">引言</p>
<p className="mb-2 indent-0">随着信息技术的迅猛发展,电子档案日益成为信息记录、传输、交换、利用 与共 享的 重要 载体,也成</p>
<p className="mb-2 indent-0">为国家档案资源的重要组成部分。由于电子文件具有可复制、易篡改和依赖设备系统读取等特性,实践</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">中一般要求具有永久保存价值或其他重要价值的电子文件转换为纸质文件 或者 缩微 胶卷 同时 归档,实</h3>
<p className="mb-2 indent-0">行双套管理。随着电子政务快速发展,办公自动化系统、业务系统普遍 应用,电子 档案 管理 研究 和实 践</p>
<p className="mb-2 indent-0">不断深入,电子档案单套管理的条件已经基本成熟,推动电子文件仅以电 子形 式进 行归 档和 管理,即单</p>
<p className="mb-2 indent-0">套管理已成为信息化条件下需要迫切解决的社会课题。2020 年6 月20 日修订通过的《中华人民共和</p>
<p className="mb-2 indent-0">国档案法》提出“电子档案应当来源可 靠、程序 规范、要素 合规”“电子 档案 与传 统载 体档 案具 有同 等效</p>
<p className="mb-2 indent-0">力”等要求,为电子档案单套管理提供了原则要求和法律支撑。</p>
<p className="mb-2 indent-0">本文件立足电子档案管理研究成果和实践,遵循《中华人民共和国档案 法》关于 电子 档案 管理 的基</p>
<p className="mb-2 indent-0">本原则,结合电子文件与电子档案管理、数字档案馆(室)建设等相关标准、规范,规定了实现电子档案单</p>
<p className="mb-2 indent-0">套管理的管理要求与技术要求,有助于解决我国电子档案管理面临的困境,切实推动电子档案单套管理</p>
<p className="mb-2 indent-0">步入正轨、有效运行,加快推进电子档案管理创新发展。</p>
<p className="mb-2 indent-0">641</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案单套管理一般要求</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">1 范围</h3>
<p className="mb-2 indent-0">本文件确立了电子档案单套管理的基本原则,规定了实现单套 管理 需要 在制 度建 设、系统 建设、资</p>
<p className="mb-2 indent-0">源建设与管理、安全管理等方面达到的要求,提出了可行性评估的方式、方法。</p>
<p className="mb-2 indent-0">本文件适用于机关、团体、企事业单位和其他组织对电子档案单 套管 理,以及 对本 单位 实行 电子 档</p>
<p className="mb-2 indent-0">案单套管理的可行性评价。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 规范性引用文件</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">下列文件中的内容通过文中的规范性引用而构成本文件必不 可少 的条 款。其中,注日 期的 引用 文</h3>
<p className="mb-2 indent-0">件,仅该日期对应的版本适用于本文件;不注日期的引用文件,其最新版本(包括 所有 的修 改单)适用 于</p>
<p className="mb-2 indent-0">本文件。</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8567 计算机软件文档编制规范</h3>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016 电子文件归档与电子档案管理规范</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">22240—2020 信息安全技术网络安全等级保护定级指南</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">26163.1—2010 信息与文献文件管理过程文件元数据第1部分:原则</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">29194—2012 电子文件管理系统通用功能要求</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33190—2016 电子文件存储与交换格式版式文档</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33476(所有部分) 党政机关电子公文格式规范</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33480—2016 党政机关电子公文元数据规范</p>
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">22—2015 归档文件整理规则</p>
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">46—2009 文书类电子文件元数据方案</p>
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">54—2014 照片类电子档案元数据方案</p>
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">63—2017 录音录像类电子档案元数据方案</p>
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">70—2018 文书类电子档案检测一般要求</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">3 术语和定义</h3>
<p className="mb-2 indent-0">下列术语和定义适用于本文件。</p>
<p className="mb-2 indent-0">3.1</p>
<p className="mb-2 indent-0">电子文件 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">document</p>
<p className="mb-2 indent-0">国家机构、社会组织或个人在履行其法定职责或处理事务过程 中,通过 计算 机等 电子 设备 形成、办</p>
<p className="mb-2 indent-0">理、传输和存储的数字格式的各种信息记录。电子文件由内容、结构和背景信息组成。</p>
<p className="mb-2 indent-0">[来源:GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016,3.1,有修改]</p>
<p className="mb-2 indent-0">741</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">3.2</p>
<p className="mb-2 indent-0">电子档案 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">records</p>
<p className="mb-2 indent-0">具有凭证、查考和保存价值并归档保存的电子文件(3.1)。</p>
<p className="mb-2 indent-0">[来源:GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016,3.2]</p>
<p className="mb-2 indent-0">3.3</p>
<p className="mb-2 indent-0">电子档案单套管理 single</p>
<div className="h-4" />
<p className="mb-2 indent-0">set</p>
<div className="h-4" />
<p className="mb-2 indent-0">filing</p>
<div className="h-4" />
<p className="mb-2 indent-0">management</p>
<div className="h-4" />
<p className="mb-2 indent-0">of</p>
<div className="h-4" />
<p className="mb-2 indent-0">electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">records</p>
<div className="h-4" />
<p className="mb-2 indent-0">仅以电子形式归档电子文件和管理电子档案的方式。</p>
<p className="mb-2 indent-0">3.4</p>
<p className="mb-2 indent-0">办公自动化系统 office</p>
<div className="h-4" />
<p className="mb-2 indent-0">automation</p>
<div className="h-4" />
<p className="mb-2 indent-0">system</p>
<p className="mb-2 indent-0">一种用于集成办公活动的信息处理系统。</p>
<p className="mb-2 indent-0">示例:</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子政务系统等用于形成、处理和维护电子文件(3.1)的计算机信息系统。</p>
<p className="mb-2 indent-0">[来源:GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">5271.27—2001,27.01.02,有修改]</p>
<p className="mb-2 indent-0">3.5</p>
<p className="mb-2 indent-0">业务系统 business</p>
<div className="h-4" />
<p className="mb-2 indent-0">system</p>
<p className="mb-2 indent-0">形成或管理机构活动数据的计算机信息系统。</p>
<p className="mb-2 indent-0">示例:</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子商务系统、财务系统、人力资源管理系统、产品 数据 管理 系统、网站 系统、电子 邮件 系统 等促 进机 构事 务</p>
<p className="mb-2 indent-0">处理的应用系统,通常这些系统内部设置相关子系统用于形成、处理和维护电子文件(3.1)。</p>
<p className="mb-2 indent-0">[来源:DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">58—2014,2.3,有修改]</p>
<p className="mb-2 indent-0">3.6</p>
<p className="mb-2 indent-0">电子档案管理系统 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">records</p>
<div className="h-4" />
<p className="mb-2 indent-0">management</p>
<div className="h-4" />
<p className="mb-2 indent-0">system</p>
<p className="mb-2 indent-0">对电子文件(3.1)、电子档案(3.2)进行采集、维护、利用和处置的计算机信息系统。</p>
<p className="mb-2 indent-0">注:</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案管理系统通常用于电子档案(3.2)形成 单位,更注 重对 电子 档案(3.2)的管 理。 系统 通过 维护 元数 据</p>
<p className="mb-2 indent-0">(3.7)及电子档案(3.2)之间的联系,支持电子档案(3.2)作为证据的价值。</p>
<p className="mb-2 indent-0">[来源:DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">58—2014,2.5,有修改]</p>
<p className="mb-2 indent-0">3.7</p>
<p className="mb-2 indent-0">元数据 metadata</p>
<p className="mb-2 indent-0">描述电子文件(3.1)、电子档案(3.2)的内容、结构、背景及其整个管理过程的数据。</p>
<p className="mb-2 indent-0">[来源:DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">58—2014,2.16,有修改]</p>
<p className="mb-2 indent-0">3.8</p>
<p className="mb-2 indent-0">电子签名 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">signature</p>
<p className="mb-2 indent-0">以电子形式所含、所附用于识别签名人身份并表明签名人认可其中内容的数据。</p>
<p className="mb-2 indent-0">[来源:DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">58—2014,2.23,有修改]</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4 总体原则和要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.1 整体系统原则</h3>
<p className="mb-2 indent-0">电子档案单套管理是一项整体性、系统性工作,实行电子档案单套管 理应 在达 到前 置性 条件(见第</p>
<p className="mb-2 indent-0">5章)的情况下,同时满足制度建设要求、系统建设要求、资源建设与管理要求、安全管理要求,并通过可</p>
<p className="mb-2 indent-0">行性评估。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.2 来源可靠原则</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">实行单套管理的电子档案应由经过 授权 和确 认的 法定 形成 者,在既 定的 业务 活动 中,在特 定的 时</h3>
<p className="mb-2 indent-0">间,通过安全可信的系统或电子设备形成。</p>
<p className="mb-2 indent-0">841</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.3 程序规范原则</h3>
<p className="mb-2 indent-0">电子档案单套管理应明确管理和技术要求,加强电子文件 形成、归档 和电 子档 案保 存、利用、鉴定、</p>
<p className="mb-2 indent-0">销毁全过程规范化控制,确保各环节程序规范,符合标准规范要求。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.4 要素合规原则</h3>
<p className="mb-2 indent-0">电子档案的内容数据、元数据均应符合相关标准要求,各组成要素齐全、完整、规范、可读。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.5 安全管理原则</h3>
<p className="mb-2 indent-0">电子档案单套管理应建立健全安全管理体系,采取措施保证电子档案在安全可信环境下管理,确保</p>
<p className="mb-2 indent-0">电子档案管理安全、过程可溯、长期可用、风险可控。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 前置性条件</h3>
<p className="mb-2 indent-0">开展电子档案单套管理,应首先满足以下前置性条件:</p>
<p className="mb-2 indent-0">a) 电子文件形成、归档和电子档案管理均通过安全可信的系统或电子设备实现;</p>
<p className="mb-2 indent-0">b) 具备满足电子档案管理需要的信息化基础设施和必要的管理制度与规范;</p>
<p className="mb-2 indent-0">c) 经费和人员配备能够满足电子档案单套管理需要;</p>
<p className="mb-2 indent-0">d) 档案、业务、信息化、安全保密等部门建立工作协调机制,分工负责电子档案单套管理工作;</p>
<p className="mb-2 indent-0">e) 具备完善的培训机制,针对单位领导、档案管理人员、业务人员、系统管理人员等分角色进行充</p>
<p className="mb-2 indent-0">分培训。</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 制度建设要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.1 应建立相应的管理制度、技术和工作规范体系,保证办公自动化系统、业务系统和电子档案管理系</h3>
<p className="mb-2 indent-0">统相互衔接并实现预定功能,支持对电子档案进行全过程管理的需要。管理制度、技术和工作规范应当</p>
<p className="mb-2 indent-0">符合相关法律法规及行业标准,充分发挥作用并被有效执行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.2 管理制度名称及主要内容宜参照附录 A 的表 A.1制定。管理制度应规定或明确电子档案效力和</h3>
<p className="mb-2 indent-0">各部门职责分工,办公自动化系统、业务系统、电子档案管理系统管理流程和运行维护要求,电子文件归</p>
<p className="mb-2 indent-0">档范围,电子档案分类方案与保管期限表,电子文件整理、归档要求,电子档案鉴定、利用、统计与移交要</p>
<p className="mb-2 indent-0">求,电子档案安全(保密)管理 要求,电子 档案 管理 培训 要求 等。 管理 制度 可以 根据 需要 单独 或合 并</p>
<p className="mb-2 indent-0">制定。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.3 技术和工作规范名称及主要内容宜参 照表 A.2 制定。 技术 和工 作规 范应 与6.2 协调 配合,明确</h3>
<p className="mb-2 indent-0">电子档案数据规范、电子档案管理系统接口规范、电子档案存储和备份策略、电子档案转换与迁移策略、</p>
<p className="mb-2 indent-0">电子档案数据恢复方案、电子档案管理应急处置方案。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 系统建设要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.1 办公自动化系统、业务系统</h3>
<p className="mb-2 indent-0">7.1.1 应具备电子文件流转、电子签名、安全认证等功能,具备电子文件在线归档基础条件。</p>
<p className="mb-2 indent-0">7.1.2 应具备完善的电子文件归档功能,支持在线完成电子文件归档。电子文件归档功能至少应包括</p>
<p className="mb-2 indent-0">以下内容:</p>
<p className="mb-2 indent-0">a) 支持按照电子档案格式要求形成电子文件及其组件;</p>
<p className="mb-2 indent-0">941</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">b) 支持在电子文件形成和流转过程中自动采集电子文件元数据,并形成规范的结构化数据;</p>
<p className="mb-2 indent-0">c) 支持在电子文件办理完毕或业务流程结束后,按照规范开展电子文件整理、检测工作;</p>
<p className="mb-2 indent-0">d) 支持自动或半自动进行归档鉴定、划定分类和保管期限;</p>
<p className="mb-2 indent-0">e) 支持生成包含电子文件及其元数据的存档信息包,按照程序要求向电子档案管理系统归档;</p>
<p className="mb-2 indent-0">f) 支持电子签名图形化转化。</p>
<p className="mb-2 indent-0">7.1.3 已运行的办公自动化系统或业务系统无法满足7.1.1、7.1.2条件的,应予以改造。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.2 电子档案管理系统</h3>
<p className="mb-2 indent-0">7.2.1 应支持从办公自动化系统、业务系统中在线接收存档信息包实现归 档;支持 非办 公自 动化 系统</p>
<p className="mb-2 indent-0">和业务系统生成的各类电子文件数据导入归档。</p>
<p className="mb-2 indent-0">7.2.2 应具备采集、检测、登记、分类、编目、著录、电子签名、检索、利用、鉴定、统计、处置、格式转换、审</p>
<p className="mb-2 indent-0">计、移交等 基本 功能,支持 对多 种门 类、多种 格式 电子 档案 进行 在线 管理。 各项 功能 应按 照</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">29194—2012、GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016的要求进行设置,相关要求还可见《数字档案室建设指南》。</p>
<p className="mb-2 indent-0">7.2.3 应具备电子档案存储与备份管理功能,满足保管期限内电子档案安全保管需要。</p>
<p className="mb-2 indent-0">7.2.4 应支持按照进馆要求向档案馆移交电子档案。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.3 系统部署和衔接</h3>
<p className="mb-2 indent-0">7.3.1 电子档案管理系统与办公自动化系统、业务系统宜按照 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">31914—2015定义的整合式或独</p>
<p className="mb-2 indent-0">立式系统关系模式进行部署,实现互联互通。采用嵌入式系统关系模式的,应当满足本单位档案资源统</p>
<p className="mb-2 indent-0">一管理要求。</p>
<p className="mb-2 indent-0">7.3.2 办公自动化系统、业务系统与电子档案管理系统应通过具有可信验证机制的安全接口通信等方</p>
<p className="mb-2 indent-0">式交互,确保电子档案来源可靠。</p>
<p className="mb-2 indent-0">7.3.3 电子档案管理系统开发者应向建设单位移交规范的技术文档。技术文档应按照 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">8567的</p>
<p className="mb-2 indent-0">规定编制,并包含需求规格说明书、详细设计书、数据库结构、电子档案原文存储结构和归档接口说明等</p>
<p className="mb-2 indent-0">系统设计与开发相关内容。如系统为非成品软件,还需提供源代码。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 资源建设与管理要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.1 电子文件形成与归档要求</h3>
<p className="mb-2 indent-0">8.1.1 电子文件在形成和流转过程中,应满足以下要求:</p>
<p className="mb-2 indent-0">a) 电子文件经授权和确认的法定形成者直接办理形成或导入办公自动化系统、业务系统,并一直</p>
<p className="mb-2 indent-0">在系统监控下流转,不存在脱离系统监控的情况;</p>
<p className="mb-2 indent-0">b) 保存电子文件关键节点(如电子公文应包括起草、审核、签发、收发文办 理、整理 归档、管理 等)</p>
<p className="mb-2 indent-0">修改痕迹和管理过程元数据;</p>
<p className="mb-2 indent-0">c) 电子文件组件和构成要素齐全完整,电子文 件与 相关 元数 据保 持关 联关 系。文书、照片、录音</p>
<p className="mb-2 indent-0">录像电子文件元数据项根据 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">46—2009、DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">54—2014、DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">63—2017定义,并确定</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">其中约束 性为 “必选 ”的元 数据 项为 必备 项。 其他 类型 电子 文件 元数 据应 符合</h3>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">26163.1—2010的要 求,党政 机关 电子 公文 元数 据还 应符 合 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33480—2016 的</p>
<p className="mb-2 indent-0">要求。</p>
<p className="mb-2 indent-0">8.1.2 电子 文件 应以 通用 格式 形成、收集,或在 归档 前转 换为 通用 格式。 电子 文件 格式 应符 合</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016中 8.3、GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33190—2016 的要 求,党政 机关 电子 公文 文件 格式 还应 符合</p>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33476(所有部分)的要求。</p>
<p className="mb-2 indent-0">8.1.3 电子文件应按照 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016、DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">22—2015 进行整理,封装形成存档信息 包。 存档</p>
<p className="mb-2 indent-0">051</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">信息包不应包含非开放的压缩、加密、签名、印章、时间戳等技术措施。</p>
<p className="mb-2 indent-0">8.1.4 电子文件归档应通过归档接口由办公自动化系统、业务系统和电子 档案 管理 系统 在线 完成,由</p>
<p className="mb-2 indent-0">电子档案管理系统完成登记并赋予档号。除不经业务系统形成的照片、录音录像等电子文件外,不应通</p>
<p className="mb-2 indent-0">过介质拷贝等进行离线归档。涉密电子文件的归档应符合相关保密规定要求。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.2 电子档案管理要求</h3>
<p className="mb-2 indent-0">8.2.1 电子档案应以档号为基础命名,并按照档号构成项逐级建立文件夹进行存储。电子档案元数据</p>
<p className="mb-2 indent-0">应转化为 XML 等文件并与电子档案统一存放。</p>
<p className="mb-2 indent-0">8.2.2 应建立电子档案目录,与电子档案建立关联关系,保持一一对应。</p>
<p className="mb-2 indent-0">8.2.3 电子档案应严格按照电子档案管理权限和工作程序进行管理、利用,采取 措施 保证 无非 法访 问</p>
<p className="mb-2 indent-0">和超越权限的访问,保证电子档案不被非法篡改。</p>
<p className="mb-2 indent-0">8.2.4 电子档案保管期限届满,应由系统自动提示并按照流程开展鉴 定。鉴定 后需 要销 毁的,应履 行</p>
<p className="mb-2 indent-0">审批手续后由授权用户手工确认删除,并以电子形式保存销毁清单及记 录;需要 续存 的,应履 行审 批手</p>
<p className="mb-2 indent-0">续后修改其保管期限及相关元数据。</p>
<p className="mb-2 indent-0">8.2.5 电子档案达到移交期限,应按照电子档案移交与接收的相关规定向档案馆移交。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 安全管理要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.1 系统安全</h3>
<p className="mb-2 indent-0">9.1.1 电子档案管理系统应满足网络安全等级保护要求或涉密信息系统 安全 分级 保护 要求。电子 档</p>
<p className="mb-2 indent-0">案管理系统等级保护要求按照 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">22240—2020执行,进一步的指南见《档案信息系统安全等级保护</p>
<p className="mb-2 indent-0">定级工作指南》。涉密 电子 档案 管理 系统 分级 保护 要求 见 BMB17—2006、BMB20—2007 和 BMB23—</p>
<p className="mb-2 indent-0">2008。</p>
<p className="mb-2 indent-0">9.1.2 办公自动化系统、业务系统和电子档案管理系统均应采取相应技术手段,确保电子文件、电子档</p>
<p className="mb-2 indent-0">案的安全、可靠。电子文件归档、电子档案移交等管理权转移过程应进行在线互信签名,确保程序规范。</p>
<p className="mb-2 indent-0">9.1.3 应明确电子档案管理系统管理员、安全(保密)管理员和安全审计员的 授权 和职 责,并实 施三 员</p>
<p className="mb-2 indent-0">管理。</p>
<p className="mb-2 indent-0">9.1.4 应按照电子档案管理应急预案或处置方案定期进行演练。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.2 存储与备份</h3>
<p className="mb-2 indent-0">9.2.1 应建立电子档案存储与备份规划,规划时限不低于档案保管期限。电子档案存储与备份规划应</p>
<p className="mb-2 indent-0">随技术发展定期更新。</p>
<p className="mb-2 indent-0">9.2.2 应为电子档案安全存储配置专用在线存储设备或虚拟云存储空间。电子 档案 存储 设备(空间)</p>
<p className="mb-2 indent-0">应配置在具有必要安全措施的局域网或电子政务网。</p>
<p className="mb-2 indent-0">9.2.3 应以独立的方式存储电子档案,在不依赖特定管理系统前提下实现 归档 电子 文件 的自 包含、自</p>
<p className="mb-2 indent-0">描述和自证明。</p>
<p className="mb-2 indent-0">9.2.4 应将电子档案及其元数据、电子档案管理系统及其配置数据、日志数据纳入备份管理范围,制定</p>
<p className="mb-2 indent-0">科学合理的电子档案备份策略,根据实际情况在离线、近线或在线备份中 选择 两种 以上 方式 进行 备份,</p>
<p className="mb-2 indent-0">有条件的还应采取异质异地备份。</p>
<p className="mb-2 indent-0">9.2.5 应具备电子档案及其目录数据库备份与恢复能力,对备份数据和介质进行登记、检测与管理,使</p>
<p className="mb-2 indent-0">用备份数据进行恢复处理时应记录备份恢复过程信息,并在恢复前后校验数据一致性。</p>
<p className="mb-2 indent-0">151</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.3 转换与迁移</h3>
<p className="mb-2 indent-0">9.3.1 应制定、评估电子档案数据转换与迁移策略,确保转换与迁移后 电子 档案 各组 件、元数 据、审计</p>
<p className="mb-2 indent-0">日志、配置信息之间关联关系,保持上述内容的完整性、可用性。</p>
<p className="mb-2 indent-0">9.3.2 电子档案保存格式不能满足长期保存需要时,应对电子档案进行格式转换。电子档案格式转换</p>
<p className="mb-2 indent-0">时,应自动采集相关元数据。</p>
<p className="mb-2 indent-0">9.3.3 在电子档案的存储设备更新、系统扩充、应用软件升级、存储载体 改变 等情 况发 生时,应对 电子</p>
<p className="mb-2 indent-0">档案管理系统及其数据进行相应迁移和更新操作。</p>
<p className="mb-2 indent-0">9.3.4 服务器、网络设备、存储设备、安全管理设备等基础设施应根据迁移和更新需求及时调整、扩容、</p>
<p className="mb-2 indent-0">升级。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.4 安全检测</h3>
<p className="mb-2 indent-0">9.4.1 应对电子文件归档和电子档案移交接收环节进行真实性、完整 性、可用 性、安全 性检 测,电子 文</p>
<p className="mb-2 indent-0">件归档后,每年至少进行1次检测。</p>
<p className="mb-2 indent-0">9.4.2 文书类电子文件、电子档案检测按照 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">70—2018 进行,其他 类型 电子 文件、电子 档案 检测</p>
<p className="mb-2 indent-0">可参照执行。</p>
<p className="mb-2 indent-0">9.4.3 应具备对在线电子档案存储状况进行监控和警告的能力,对存储介质不稳定、存储空间不足、电</p>
<p className="mb-2 indent-0">子档案非授权访问和系统响应超时等情况发出警告,跟踪和记录警告事项处理过程。</p>
<p className="mb-2 indent-0">9.4.4 应定期对电子档案管理系统、服务器、网络设备、存储设备及安全管理设备等软硬件有效性进行</p>
<p className="mb-2 indent-0">检测,确保电子档案保管环境无病毒感染、无安全隐患。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.5 审计跟踪</h3>
<p className="mb-2 indent-0">9.5.1 应建立审计跟踪制度,对电子档案管理流程操作行为、电子档案管理 系统 运维 操作 行为 实施 审</p>
<p className="mb-2 indent-0">计跟踪。操作行为应包括但不限于行为描述、行为步骤、行为对象、行为日期、行为人员等。</p>
<p className="mb-2 indent-0">9.5.2 应自动记录审计跟踪事件信息,并将有关审计信息按元数据方案要求同时作为电子档案的元数</p>
<p className="mb-2 indent-0">据加以管理。</p>
<p className="mb-2 indent-0">9.5.3 应规范审计跟踪日志管理,在电子档案生命周期内持续维护审计跟踪日志。审计跟踪日志和重</p>
<p className="mb-2 indent-0">要操作日志可按日期、人员等条件进行检索查询,保存时间不应低于电子 档案 保管 期限,且应 纳入 备份</p>
<p className="mb-2 indent-0">恢复范围。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 可行性评估</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.1 电子档案单套管理可行性评估 应按 照附 录 B 的评 估指 标组 织开 展。 评估 指标 划分 为5 个一 级</h3>
<p className="mb-2 indent-0">指标、13个二级指标、26个三级指标。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.2 评估应当先由本单位进行自评,通过后再向同级档案主管部门提 出评 估申 请。评估 由档 案主 管</h3>
<p className="mb-2 indent-0">部门或档案主管部门认可的其他具备电子档案管理评估能力的机构进行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.3 评估指标所有三级指标评估结果为“通过”视为通过可行性评估,可开展电子档案单套管理。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.4 电子档案单套管理每三年至少进行一次复评。电子档案单套管理系统环境或应用发生重大改变</h3>
<p className="mb-2 indent-0">时,应当立即进行复评。</p>
<p className="mb-2 indent-0">251</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 A</h3>
<p className="mb-2 indent-0">(资料性)</p>
<p className="mb-2 indent-0">电子档案管理制度、技术和工作规范</p>
<p className="mb-2 indent-0">A.1 管理制度</p>
<p className="mb-2 indent-0">表 A.1给出了推荐制定的管理制度的名称及主要内容。</p>
<p className="mb-2 indent-0">表 A.1 管理制度</p>
<p className="mb-2 indent-0">名称主要内容</p>
<p className="mb-2 indent-0">电子档案管理基本制度电子档案效力、职责分工、基本管理要求</p>
<p className="mb-2 indent-0">办公自动化系统、业务系统归档制度办公自动化系统、业务系统的归档流程、工作要求</p>
<p className="mb-2 indent-0">电子档案管理系统运行维护制度</p>
<p className="mb-2 indent-0">系统操作规程、系统 修改 规程、系统 定期 维护 要求、系统 安全 保密 要</p>
<p className="mb-2 indent-0">求、系统运行状态记录和日志归档要求等</p>
<p className="mb-2 indent-0">电子文件归档范围、电子 档案 分类 方案 与保</p>
<p className="mb-2 indent-0">管期限制度</p>
<p className="mb-2 indent-0">电子文件归档范围、电子档案分类方案、保管期限与处置要求</p>
<p className="mb-2 indent-0">电子文件整理与归档制度电子文件归档格式、元数据要求、整理要求</p>
<p className="mb-2 indent-0">电子档案鉴定、利用、统计与移交制度电子档案鉴定程序、利用规则与权限设置、统计、移交要求</p>
<p className="mb-2 indent-0">电子档案安全(保密)管理制度电子档案备份、检测、审计、应急处置及涉密信息与载体管理要求</p>
<p className="mb-2 indent-0">电子档案管理培训制度电子档案管理培训计划、安排</p>
<p className="mb-2 indent-0">A.2 技术和工作规范</p>
<p className="mb-2 indent-0">表 A.2给出了推荐制定的技术和工作规范的名称及主要内容。</p>
<p className="mb-2 indent-0">表 A.2 技术和工作规范</p>
<p className="mb-2 indent-0">名称主要内容</p>
<p className="mb-2 indent-0">电子档案数据规范电子档案数据格式、内容及相关要求</p>
<p className="mb-2 indent-0">电子档案管理系统接口规范</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">向办公自动化系统 和业 务系 统提 供电 子档 案移 交、利用 等接 口以 及接 口使 用说</h3>
<p className="mb-2 indent-0">明,明确接口调用方式、接口名称、接口参数</p>
<p className="mb-2 indent-0">电子档案存储和备份策略电子档案存储要求、备份范围和方式</p>
<p className="mb-2 indent-0">电子档案转换与迁移策略进行系统迁移、数据迁移、格式转换时,所应采取的策略</p>
<p className="mb-2 indent-0">电子档案数据恢复方案电子档案数据因系统软硬件故障、极端特殊情况等导致数据丢失后的数据恢复</p>
<p className="mb-2 indent-0">电子档案管理应急处置方案电子档案管理突发事件应急准备、应急响应、应急处置、应急恢复</p>
<p className="mb-2 indent-0">351</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 B</h3>
<p className="mb-2 indent-0">(规范性)</p>
<p className="mb-2 indent-0">电子档案单套管理可行性评估指标</p>
<p className="mb-2 indent-0">表 B.1规定了电子档案单套管理可行性评估各级指标及评估要点和评估结果。</p>
<p className="mb-2 indent-0">表 B.1 电子档案单套管理可行性评估指标</p>
<p className="mb-2 indent-0">一级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">二级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">三级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">评估要点评估结果</p>
<p className="mb-2 indent-0">前置性条件</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子文件形成、归档和电子档案管理均通过安 全可 信的 系统 或电</p>
<p className="mb-2 indent-0">子设备实现;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">具备满足电子档案管理 需要 的信 息化 基础 设施 和必 要的 管理 制</h3>
<p className="mb-2 indent-0">度与规范;</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">经费和人员配备能够满足电子档案单套管理需要;</p>
<p className="mb-2 indent-0">4.</p>
<div className="h-4" />
<p className="mb-2 indent-0">档案、业务、信息化、安全 保密 等部 门建 立工 作协 调机 制,分工 负</p>
<p className="mb-2 indent-0">责电子档案单套管理工作;</p>
<p className="mb-2 indent-0">5.</p>
<div className="h-4" />
<p className="mb-2 indent-0">具备完善的培训机制,针对 单位 领导、档案 管理 人员、业务 人员、</p>
<p className="mb-2 indent-0">系统管理人员等分角色进行充分培训</p>
<div className="h-4" />
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">(结果 为 “通过 ”则</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">可以继续进 行以 下</h3>
<p className="mb-2 indent-0">评估,结果为“未通</p>
<p className="mb-2 indent-0">过”则综 合评 估意</p>
<p className="mb-2 indent-0">见为“未通过”)</p>
<p className="mb-2 indent-0">制度</p>
<p className="mb-2 indent-0">建设</p>
<p className="mb-2 indent-0">要求</p>
<p className="mb-2 indent-0">完备性</p>
<p className="mb-2 indent-0">管理制度参照表 A.1 □通过 □未通过</p>
<p className="mb-2 indent-0">技术和工</p>
<p className="mb-2 indent-0">作规范</p>
<p className="mb-2 indent-0">参照表 A.2 □通过 □未通过</p>
<p className="mb-2 indent-0">有效性</p>
<p className="mb-2 indent-0">科学规范管理制度、技术和工作规范符合相关法律法规及行业标准 □通过 □未通过</p>
<p className="mb-2 indent-0">执行有力</p>
<p className="mb-2 indent-0">管理制度、技术和工作规范在电子档案单套管理过程中,充分发挥作</p>
<p className="mb-2 indent-0">用并被有效执行 □通过 □未通过</p>
<p className="mb-2 indent-0">系统</p>
<p className="mb-2 indent-0">建设</p>
<p className="mb-2 indent-0">要求</p>
<p className="mb-2 indent-0">办公自动</p>
<p className="mb-2 indent-0">化系统、</p>
<p className="mb-2 indent-0">业务系统</p>
<p className="mb-2 indent-0">基础功能</p>
<p className="mb-2 indent-0">具备电子文件流转、电子签名、安全 认证 等功 能,具备 电子 文件 在线</p>
<p className="mb-2 indent-0">归档基础条件 □通过 □未通过</p>
<p className="mb-2 indent-0">归档功能</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">支持按照电子档案格式要求形成电子文件及其组件;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">支持在电子文件形成和流转过程中自动采集 电子 文件 元数 据,并</h3>
<p className="mb-2 indent-0">形成规范的结构化数据;</p>
<p className="mb-2 indent-0">3.支持在电子文件办理完毕或 业务 流程 结束 后,按照 规范 开展 电子</p>
<p className="mb-2 indent-0">文件整理、检测工作;</p>
<p className="mb-2 indent-0">4.</p>
<div className="h-4" />
<p className="mb-2 indent-0">支持自动或半自动进行归档鉴定、划定分类和保管期限;</p>
<p className="mb-2 indent-0">5.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">支持生成包含电子文件及其元数据的存档信 息包,按照 程序 要求</h3>
<p className="mb-2 indent-0">向电子档案管理系统归档;</p>
<p className="mb-2 indent-0">6.支持电子签名图形化转化</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">451</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表</p>
<div className="h-4" />
<p className="mb-2 indent-0">B.1 电子档案单套管理可行性评估指标</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">一级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">二级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">三级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">评估要点评估结果</p>
<p className="mb-2 indent-0">系统</p>
<p className="mb-2 indent-0">建设</p>
<p className="mb-2 indent-0">要求</p>
<p className="mb-2 indent-0">电子档案</p>
<p className="mb-2 indent-0">管理系统</p>
<p className="mb-2 indent-0">基本功能</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">支持从办公自动化系统、业务系统中在线接收 存档 信息 包实 现归</p>
<p className="mb-2 indent-0">档;支持非办公自动化系统和业 务系 统生 成的 各类 电子 文件 数据 导</p>
<p className="mb-2 indent-0">入归档;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">具备采集、检测、登记、分类、编目、著录、电子 签名、检索、利用、鉴</p>
<p className="mb-2 indent-0">定、统计、处置、格式转换、审计、移交 等基 本功 能,支持 对多 种门 类、</p>
<p className="mb-2 indent-0">多种格式电子档案进行在线管理;</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">具备电子档案存储与备份管理功能,满足保管 期限 内电 子档 案安</p>
<p className="mb-2 indent-0">全保管需要;</p>
<p className="mb-2 indent-0">4.</p>
<div className="h-4" />
<p className="mb-2 indent-0">支持按照进馆要求向档案馆移交电子档案</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">系统部署</p>
<p className="mb-2 indent-0">和衔接</p>
<p className="mb-2 indent-0">系统部署</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案管理系统与办公自动化系统、业务系统实现互联互通。</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">电子 档案 管理 系统 与办 公自 动化 系统、业务 系统 宜按 照</h3>
<p className="mb-2 indent-0">GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">31914—2015定义的 整合 式或 独立 式系 统关 系模 式进 行部</p>
<p className="mb-2 indent-0">署。采用嵌入式的,满足本单位档案资源统一管理要求</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">交互通信</p>
<p className="mb-2 indent-0">办公自动化系统、业务系统与电 子档 案管 理系 统通 过具 有可 信验 证</p>
<p className="mb-2 indent-0">机制的安全接口通信等方式交互,确保电子档案来源可靠 □通过 □未通过</p>
<p className="mb-2 indent-0">技术文档</p>
<p className="mb-2 indent-0">与源代码</p>
<p className="mb-2 indent-0">向建设单位移交规范的技术文档。技术 文档 按照 GB/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8567 编制,</h3>
<p className="mb-2 indent-0">并包含需求规格说明书、详细 设计 书、数据 库结 构、电子 档案 原文 存</p>
<p className="mb-2 indent-0">储结构和归档接口说明等系统设计与开发相关内容。如系统为非成</p>
<p className="mb-2 indent-0">品软件,还需提供源代码</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">资源</p>
<p className="mb-2 indent-0">建设</p>
<p className="mb-2 indent-0">与管</p>
<p className="mb-2 indent-0">理要</p>
<p className="mb-2 indent-0">求</p>
<p className="mb-2 indent-0">资源建设</p>
<p className="mb-2 indent-0">形成与</p>
<p className="mb-2 indent-0">流转</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">电子文件经授权和确认 的法 定形 成者 直接 办理 形成 或导 入办 公</h3>
<p className="mb-2 indent-0">自动化系统、业务系统,并一直 在系 统监 控下 流转,不存 在脱 离系 统</p>
<p className="mb-2 indent-0">监控的情况;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">保存电子文件关键节点(如电 子公 文应 包括 起草、审核、签发、收</p>
<p className="mb-2 indent-0">发文办理、整理归档、管理等)修改痕迹和管理过程元数据;</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子文件组件和构成要素齐全完整,电子文件 与相 关元 数据 保持</p>
<p className="mb-2 indent-0">关联关系</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">格式要求</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">文书 类电 子档 案正 本、定稿、公文 处理 单等 以 OFD、PDF 等版 式</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">文档格式归档保 存,修改 过程 稿以 WPS、RTF、DOC 等格 式归 档保</h3>
<p className="mb-2 indent-0">存,党政机关电子公文格式符合 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">33476(所有部分)的要求;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">照片类电 子档 案以 TIFF、JPEG 格式 保存,其可 交换 图像 文件</h3>
<p className="mb-2 indent-0">(EXIF)信息保存完整;</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">重要或珍贵的录音类电子档案以 WAV 格式保存,其他的以 MP3</p>
<p className="mb-2 indent-0">格式保存;</p>
<p className="mb-2 indent-0">4.</p>
<div className="h-4" />
<p className="mb-2 indent-0">录像类电子档案以 MPG、MP4、AVI、MXF 格式保存;</p>
<p className="mb-2 indent-0">5.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">其他 电子 文件、电子 档案 根据 GB/T</h3>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016、DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">47—</p>
<p className="mb-2 indent-0">2009的原则和相关行业标准选择主流、成熟、开放的格式</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">归档整理</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">电子 文件 按照 GB/T</h3>
<div className="h-4" />
<p className="mb-2 indent-0">18894—2016、DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">22—2015 等标 准进 行</p>
<p className="mb-2 indent-0">整理,封装形成存 档信 息包。 存档 信息 包不 包含 非开 放的 压缩、加</p>
<p className="mb-2 indent-0">密、签名、印章、时间戳等技术措施;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">电子文件归档通过归档接口由办公自动化系 统、业务 系统 和电 子</h3>
<p className="mb-2 indent-0">档案管理系统在线完成,由电子档案管理系统完成登记并赋予档号;</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">涉密电子文件的归档符合相关保密规定要求</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">551</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表</p>
<div className="h-4" />
<p className="mb-2 indent-0">B.1 电子档案单套管理可行性评估指标</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">一级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">二级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">三级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">评估要点评估结果</p>
<p className="mb-2 indent-0">资源</p>
<p className="mb-2 indent-0">建设</p>
<p className="mb-2 indent-0">与管</p>
<p className="mb-2 indent-0">理要</p>
<p className="mb-2 indent-0">求</p>
<p className="mb-2 indent-0">资源管理管理要求</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案以档号为基础命名,并按照档号构成 项逐 级建 立文 件夹</p>
<p className="mb-2 indent-0">进行存储;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案元数据转化为 XML 等文件并与电子档案统一存放;</p>
<p className="mb-2 indent-0">3.建立电子档案目录,与电子档案建立关联关系,保持一一对应;</p>
<p className="mb-2 indent-0">4.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">电子档案严格 按照 电子 档案 管理 权限 和工 作程 序进 行管 理、利</h3>
<p className="mb-2 indent-0">用,采取措施保证无非法访问和超越权限的访问,保证电子档案不被</p>
<p className="mb-2 indent-0">非法篡改;</p>
<p className="mb-2 indent-0">5.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案保管期限届满,系统自动提示并 按照 流程 开展 鉴定。 鉴</p>
<p className="mb-2 indent-0">定后需要销毁的,履行审批手续后由授权用户手工确认删除,并以电</p>
<p className="mb-2 indent-0">子形式保存销毁清单及记录;需要续存的,履行审批手续后修改其保</p>
<p className="mb-2 indent-0">管期限及相关元数据;</p>
<p className="mb-2 indent-0">6.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案达到移交期限,按照电子档案移交与 接收 的相 关规 定向</p>
<p className="mb-2 indent-0">档案馆移交</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">安全</p>
<p className="mb-2 indent-0">管理</p>
<p className="mb-2 indent-0">要求</p>
<p className="mb-2 indent-0">系统安全</p>
<p className="mb-2 indent-0">系统安全</p>
<p className="mb-2 indent-0">保护要求</p>
<p className="mb-2 indent-0">电子档案管理系统满足网络安全等级保护要求或涉密信息系统安全</p>
<p className="mb-2 indent-0">分级保护要求 □通过 □未通过</p>
<p className="mb-2 indent-0">互信签</p>
<p className="mb-2 indent-0">名要求</p>
<p className="mb-2 indent-0">在办公自动化系统、业务系统和 电子 档案 管理 系统 中采 取相 应技 术</p>
<p className="mb-2 indent-0">手段,确保电子文件、电子档案的安全、可靠。电子文件归档、电子 档</p>
<p className="mb-2 indent-0">案移交等管理权转移过程进行在线互信签名</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">三员管理</p>
<p className="mb-2 indent-0">明确电子档案管理系统管理员、安全(保密)管理 员和 安全 审计 员的</p>
<p className="mb-2 indent-0">授权和职责,并实施三员管理 □通过 □未通过</p>
<p className="mb-2 indent-0">应急演练按照电子档案管理应急预案或处置方案定期进行演练 □通过 □未通过</p>
<p className="mb-2 indent-0">存储与</p>
<p className="mb-2 indent-0">备份</p>
<p className="mb-2 indent-0">存储管理</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">建立电子档案存储规 划,规划 时限 不低 于档 案保 管期 限,电子 档</h3>
<p className="mb-2 indent-0">案存储规划随技术发展定期更新。</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">为电子档案安全存储配置专用在线存储设备 或虚 拟云 存储 空间。</h3>
<p className="mb-2 indent-0">电子档案存储设备(空间)配置在具有必要安全措施的局域网或电子</p>
<p className="mb-2 indent-0">政务网。</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">以独立的方式存储电子档案,在不依赖特定管 理系 统前 提下 实现</p>
<p className="mb-2 indent-0">电子文件的自包含、自描述和自证明</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">备份管理</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">建立电子档案备份规划,规划时限不低于 档案 保管 期限。 电子 档</p>
<p className="mb-2 indent-0">案备份规划随技术发展定期更新。</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">将电子档案及其元数 据、电子 档案 管理 系统 及其 配置 数据、日志</h3>
<p className="mb-2 indent-0">数据纳入备份管理范围,制定科学合理的电子档案备份策略,并使用</p>
<p className="mb-2 indent-0">两种以上的备份方式。</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">具备电子档案及其目录数据库备份与恢复能 力,对备 份数 据和 介</h3>
<p className="mb-2 indent-0">质进行登记、检测与管理,使用备份数据进行恢复处理时应记录备份</p>
<p className="mb-2 indent-0">恢复过程信息,并在恢复前后校验数据一致性</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">651</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表</p>
<div className="h-4" />
<p className="mb-2 indent-0">B.1 电子档案单套管理可行性评估指标</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">一级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">二级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">三级</p>
<p className="mb-2 indent-0">指标</p>
<p className="mb-2 indent-0">评估要点评估结果</p>
<p className="mb-2 indent-0">安全</p>
<p className="mb-2 indent-0">管理</p>
<p className="mb-2 indent-0">要求</p>
<p className="mb-2 indent-0">转换与</p>
<p className="mb-2 indent-0">迁移</p>
<p className="mb-2 indent-0">转换与</p>
<p className="mb-2 indent-0">迁移要求</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">制定、评估电子档案数 据转 换与 迁移 策略,确保 转换 与迁 移后 电</p>
<p className="mb-2 indent-0">子档案各组件、元数据、审计日志、配置信息之间关联关系,保持上 述</p>
<p className="mb-2 indent-0">内容的完整性、可用性。</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子档案保存格式不能满足长期保存需要时,对电 子档 案进 行格</p>
<p className="mb-2 indent-0">式转换。电子档案格式转换时,自动采集相关元数据。</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">在电子档案的存储设备更新、系统扩充、应用 软件 升级、存储 载体</p>
<p className="mb-2 indent-0">等情况发生时,对电子档案管理 系统 及其 数据 进行 相应 迁移 和更 新</p>
<p className="mb-2 indent-0">操作。</p>
<p className="mb-2 indent-0">4.</p>
<div className="h-4" />
<p className="mb-2 indent-0">服务器、网络设备、存储设备、安全管理设备 等基 础设 施应 根据 迁</p>
<p className="mb-2 indent-0">移和更新需求及时调整、扩容、升级</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">安全检测</p>
<p className="mb-2 indent-0">四性检测</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">在电子文件归档和电子 档案 移交 接收 环节 对存 档信 息包 进行 真</h3>
<p className="mb-2 indent-0">实性、完整性、可用性、安全性检测;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子文件归档后,每年至少进行1次检测;</p>
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">文书类电子文件、电子档案 检测 按照 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">70—2018 进行,其他</p>
<p className="mb-2 indent-0">类型电子文件、电子档案检测可参照执行</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">环境检测</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">具备对在线电子档案存储状况进行监控和警 告的 能力,对存 储介</h3>
<p className="mb-2 indent-0">质不稳定、存储空间不足、电子档案非授权访问和系统响应超时等情</p>
<p className="mb-2 indent-0">况发出警告,跟踪和记录警告事项处理过程;</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">定期对电子档案管理系统、服务器、网络设 备、存储 设备 及安 全管</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">理设备等软硬件有效性进行检 测,确保 电子 档案 保管 环境 无病 毒感</h3>
<p className="mb-2 indent-0">染、无安全隐患</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">审计跟踪</p>
<p className="mb-2 indent-0">审计范围</p>
<p className="mb-2 indent-0">建立审计跟踪制度,对电子档案管理流程操作行为、电子档案管理系</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">统运维操作行为实 施审 计跟 踪。 操作 行为 应包 括但 不限 于行 为描</h3>
<p className="mb-2 indent-0">述、行为步骤、行为对象、行为日期、行为人员等</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">日志管理</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">自动记录审计跟踪事件信息,并将有关审计信 息按 元数 据方 案要</p>
<p className="mb-2 indent-0">求同时作为电子档案的元数据加以管理。</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">在电子档案生命周期 内持 续维 护审 计跟 踪日 志。 审计 跟踪 日志</h3>
<p className="mb-2 indent-0">和重要操作日志可按日期、人员等条件进行检索查询,保存时间不低</p>
<p className="mb-2 indent-0">于电子档案保管期限,且纳入备份恢复范围</p>
<p className="mb-2 indent-0">□通过 □未通过</p>
<p className="mb-2 indent-0">综合评估意见 □通过 □未通过</p>
<p className="mb-2 indent-0">751</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">92—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">参考 文献</h3>
<p className="mb-2 indent-0">[1] GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">5271.27—2001 信息技术词汇第27部分:办公自动化</p>
<p className="mb-2 indent-0">[2] GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">31914—2015</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子文件管理系统建设指南</p>
<p className="mb-2 indent-0">[3] GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">39362—2020 党政机关电子公文归档规范</p>
<p className="mb-2 indent-0">[4] DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">58—2014 电子档案管理基本术语</p>
<p className="mb-2 indent-0">[5] BMB17—2006 涉及国家秘密的信息系统分级保护技术要求</p>
<p className="mb-2 indent-0">[6] BMB20—2007 涉及国家秘密的信息系统分级保护管理规范</p>
<p className="mb-2 indent-0">[7] BMB23—2008 涉及国家秘密的信息系统分级保护方案设计指南</p>
<p className="mb-2 indent-0">[8] 机关文件材料归档范围和保管期限规定(国家档案局令第8号)</p>
<p className="mb-2 indent-0">[9] 机关档案管理规定(国家档案局令第13号)</p>
<p className="mb-2 indent-0">[10] 档案信息系统安全等级保护定级工作指南(档办发〔2013〕5号)</p>
<p className="mb-2 indent-0">[11] 数字档案室建设指南(档办发〔2014〕4号)</p>
<p className="mb-2 indent-0">[12] 数字档案室建设评价办法(档办发〔2016〕3号)</p>
<p className="mb-2 indent-0">[13] 电子档案管理系统基本功能规定(档办发〔2017〕3号)</p>
<p className="mb-2 indent-0">[14] 党政机关电子公文处理工作办法(厅字〔2019〕7号)</p>
<p className="mb-2 indent-0">[15] 李明华.数字档案室建设概论[M].北京:中国文史出版社,2016.</p>
<p className="mb-2 indent-0">851</p>
      </div>
      
      <div className="bg-amber-500/10 border p-8 rounded-3xl border-amber-500/20 mt-16">
          <h3 className="text-xl font-bold text-white mb-4">DigiVoucher 100% 合规落地</h3>
          <p className="text-slate-400 mb-6 leading-relaxed">
              DigiVoucher 系统设计严格遵循 DA/T 92—2022《电子档案单套管理一般要求》 要求。我们确保您的电子档案管理流程在技术层面上完全对标国标与行标，
              实现全生命周期的合规管控。
          </p>
      </div>
    </RegulationLayout>
  );
};

export default DAT92Spec;
