// Input: 无
// Output: DA/T 94—2022《电子会计档案管理规范》 全量高排版版
// Pos: /Users/user/nexusarchive/src/pages/product-website/regulations/DAT94Spec.tsx

import React from 'react';
import { RegulationLayout } from './RegulationLayout';

export const DAT94Spec: React.FC = () => {
  return (
    <RegulationLayout 
        title="DA/T 94—2022《电子会计档案管理规范》"
        category="核心规范"
        source="国家标准/行业规范"
        effectiveDate="2022-07-01"
    >
      <div className="regulation-content font-serif leading-relaxed text-slate-300 max-w-none">
<p className="mb-2 indent-0">ICS01.140.20</p>
<p className="mb-2 indent-0">CCSA 14</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">中华 人民 共和 国档 案行 业标 准</h3>
<p className="mb-2 indent-0">DA/T 94—2022</p>
<p className="mb-2 indent-0">电子会计档案管理规范</p>
<p className="mb-2 indent-0">Specification</p>
<div className="h-4" />
<p className="mb-2 indent-0">of</p>
<div className="h-4" />
<p className="mb-2 indent-0">electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">accounting</p>
<div className="h-4" />
<p className="mb-2 indent-0">archives</p>
<div className="h-4" />
<p className="mb-2 indent-0">management</p>
<p className="mb-2 indent-0">2022-04-07发布 2022-07-01实施</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">国家档案局发 布 571</h3>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">前言</p>
<p className="mb-2 indent-0">本文件按照 GB/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">1.1—2020《标准化工作导则第1部分:标准化文件的结构和起草规则》的规定</p>
<p className="mb-2 indent-0">起草。</p>
<div className="h-4" />
<p className="mb-2 indent-0">请注意本文件的某些内容可能涉及专利。本文件的发布机构不承担识别专利的责任。</p>
<div className="h-4" />
<p className="mb-2 indent-0">本文件由国家档案局提出并归口。</p>
<div className="h-4" />
<p className="mb-2 indent-0">本文件起草单位:国家档案局经科司、财政部会计司、航天信息股份有限公司、中国电力建设集团有</p>
<p className="mb-2 indent-0">限公司、用友网络科技股份有限公司、中国石油天然气集团有限公司。</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">本文件主要起 草人:李忱、蔡盈 芳、万文 翔、王洋、李绯、张艳 军、王强、张旋、祁慧 轩、冷冰、袁瑞、</h3>
<p className="mb-2 indent-0">戎越、张晶晶、车昊珈。</p>
<p className="mb-2 indent-0">671</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计档案管理规范</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">1 范围</h3>
<p className="mb-2 indent-0">本文件规定了电子会计资料形成、收集、整理、归档和电 子会 计档 案保 管、统计、利用、鉴定、处置 等</p>
<p className="mb-2 indent-0">工作的要求。</p>
<div className="h-4" />
<p className="mb-2 indent-0">本文件适用于机关、团体、企业 事业 单位 和其 他组 织 (以下 简称 “单位”)开展 电子 会计 档案 管理</p>
<p className="mb-2 indent-0">活动。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 规范性引用文件</h3>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">下列文件中的内容通过文中的规范性引用而构成本文件必不 可少 的条 款。其中,注日 期的 引用 文</h3>
<p className="mb-2 indent-0">件,仅该日期对应的版本适用于本文件;不注日期的引用文件,其最新版本(包括 所有 的修 改单)适用 于</p>
<p className="mb-2 indent-0">本文件。</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15 磁性载体档案管理与保护规范</h3>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">38 档案级可录类光盘 CD-R、DVD-R、DVD+R 技术要求和应用规范</h3>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">39 会计档案案卷格式</h3>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">70 文书类电子档案检测一般要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">3 术语和定义</h3>
<div className="h-4" />
<p className="mb-2 indent-0">下列术语和定义适用于本文件。</p>
<p className="mb-2 indent-0">3.1</p>
<p className="mb-2 indent-0">电子会计资料 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">accounting</p>
<div className="h-4" />
<p className="mb-2 indent-0">document</p>
<div className="h-4" />
<p className="mb-2 indent-0">单位在进行会计核算过程中通过计算机等电子设备形成、传输、存储的记录和反映单位经济业务事</p>
<p className="mb-2 indent-0">项的电子形式的各种会计信息记录。</p>
<p className="mb-2 indent-0">注:</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计资料包括以电子形式存在的会计凭证、会计账簿、财务 会计 报告 和其 他会 计资 料。 其中,财务 会计 报</p>
<p className="mb-2 indent-0">告包括企业财务会计报告、政府会计主体的财务报告和决算 报告、民间 非营 利组 织财 务会 计报 告,以及 其他 会</p>
<p className="mb-2 indent-0">计主体的财务会计报告。</p>
<p className="mb-2 indent-0">3.2</p>
<p className="mb-2 indent-0">电子会计档案 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">accounting</p>
<div className="h-4" />
<p className="mb-2 indent-0">archive</p>
<div className="h-4" />
<p className="mb-2 indent-0">在会计核算工作中由电子计算机直接形成或接收、传输、存储并 归档,记录 和反 映单 位经 济业 务事</p>
<p className="mb-2 indent-0">项,具有凭证、查考和保存价值的电子会计资料。</p>
<p className="mb-2 indent-0">3.3</p>
<p className="mb-2 indent-0">会计核算系统 accounting</p>
<div className="h-4" />
<p className="mb-2 indent-0">system</p>
<div className="h-4" />
<p className="mb-2 indent-0">单位为进行会计核算而使用的,用于直接采集数据,处理会 计业 务,生成 会计 凭证、会计 账簿、财务</p>
<p className="mb-2 indent-0">会计报告等会计资料,并对会计资料进 行转 换、输出、分析 和利 用的 计算 机软 件、软件 系统 或软 件功 能</p>
<p className="mb-2 indent-0">模块。</p>
<p className="mb-2 indent-0">3.4</p>
<p className="mb-2 indent-0">业务系统 business</p>
<div className="h-4" />
<p className="mb-2 indent-0">system</p>
<div className="h-4" />
<p className="mb-2 indent-0">除会计核算系统外,其他产生电子会计凭证的办公自动化系统、报销系统、合同管理系统、企业资源</p>
<p className="mb-2 indent-0">771</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">计划系统等计算机信息系统。</p>
<p className="mb-2 indent-0">3.5</p>
<p className="mb-2 indent-0">电子会计档案管理信息系统 electronic</p>
<div className="h-4" />
<p className="mb-2 indent-0">accounting</p>
<div className="h-4" />
<p className="mb-2 indent-0">archives</p>
<div className="h-4" />
<p className="mb-2 indent-0">management</p>
<div className="h-4" />
<p className="mb-2 indent-0">information</p>
<div className="h-4" />
<p className="mb-2 indent-0">system</p>
<div className="h-4" />
<p className="mb-2 indent-0">单位用于电子会计资料收集、整理、归档以及电子会计档案保管、统计、利用、鉴定、处置等业务的电</p>
<p className="mb-2 indent-0">子档案管理信息系统或软件功能模块。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4 管理原则和要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.1 单位应加强电子会计档案管理工作,建立和完善电子会计资料的 形成、收集、整理、归档 和电 子会</h3>
<p className="mb-2 indent-0">计档案保管、统计、利用、鉴定、处置等管理制度,采取可靠的安全防护技术和措施,保证电子会计档案在</p>
<p className="mb-2 indent-0">传递及存储过程中的真实性、完整性、可用性和安全性。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.2 单位应将电子会计档案管理工作纳入会计人员、档案人员、相关业务人员岗位职责和绩效考核。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.3 单位的会计机构或会计人员所属机构(以下统称单位会计管理机构)负责应 归档 的电 子会 计资 料</h3>
<p className="mb-2 indent-0">收集、整理、归档等工作,定期向单位的档案管理机构或者档案工作人员所属机构(以下统称单位档案管</p>
<p className="mb-2 indent-0">理机构)移交。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.4 单位档案管理机构负责电子会计档案保管、统计、利用、鉴定、处置等工作,并对电子会计资料的收</h3>
<p className="mb-2 indent-0">集、整理、归档等进行指导和监督。单位也可以委托具备档案管理条件的机构代为管理电子会计档案。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.5 单位的信息技术机构应在相关会计核算系统及业务系统规划、分析、设计、实施、运维 等过 程中 落</h3>
<p className="mb-2 indent-0">实电子会计资料归档要求,将电子会计资料归档要求在会计核算系统及业务系统中予以实现,提供信息</p>
<p className="mb-2 indent-0">技术支持,并负责电子会计档案管理信息系统的运行维护。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.6 单位应加强电子会计档案的安全保密管理,涉密电子会计资料和电子会计档案管理按照国家有关</h3>
<p className="mb-2 indent-0">规定执行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.7 符合国家有关规定形成(或接收)并按照本文件管理的电子会计资料,可仅以电子形式归档保存。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 电子会计档案管理流程</h3>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计档案管理由会计人员、档案人员分工负责,涉及会计核算系统、业务系统、电子会计档案管</p>
<p className="mb-2 indent-0">理信息系统等信息系统,管理过程包括电子会计资料的形成、收集、整理、归档 和电 子会 计档 案的 保管、</p>
<p className="mb-2 indent-0">统计、利用、鉴定、处置等,管理流程见图1。</p>
<p className="mb-2 indent-0">871</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">图1 电子会计档案管理流程</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 电子会计资料的形成</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.1 内部形成的电子会计资料应经过经办、审核、审批等必要的审签程序,内容及元数据齐全完整。元</h3>
<p className="mb-2 indent-0">数据的结构、内容等一定应符合附录 A 的规定。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.2 电子会计资料应形成相应格式的独立的电子文件进行归档。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.3 内部形成的电子会计资料应按一定的时间和单元输出归档电子会计资料,文件大小应便于管理和</h3>
<p className="mb-2 indent-0">利用,各类电子会计资料输出时间及格式应符合以下要求。</p>
<p className="mb-2 indent-0">a) 内部形成的电子会计凭证应在办理完毕后输出成归 档电 子会 计凭 证,并在 输出 信息 中体 现相</p>
<p className="mb-2 indent-0">关联电子会计凭证间的关联关系。从外部接收的电子会计凭证一般以原格式归档。如原格式</p>
<p className="mb-2 indent-0">不符合归档要求,应将专用软件一并归档,或将原 格式 转换 为符 合归 档要 求的 格式,原格 式与</p>
<p className="mb-2 indent-0">符合归档要求格式的电子会计资料一并归档。</p>
<p className="mb-2 indent-0">b) 电子会计账簿可按月、季、年等周期定期输出归档电子会计账簿,输出周 期可 根据 数据 量大 小</p>
<p className="mb-2 indent-0">确定。</p>
<p className="mb-2 indent-0">c) 电子财务会计报告可按会计期间输出归档电子财务会计报告。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.4 电子会计资料归档版式推荐使用 OFD 格式,不具备应用 OFD 格式条件的单位可使用 PDF 格式</h3>
<p className="mb-2 indent-0">或其他符合长期保存要求的版式格式。为方便解析和统计,可同步输出类 XML 描述文件归档。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 电子会计资料的收集</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.1 电子会计资料归档范围应符合附录 B 的规 定,各单 位可 参考 但不 限于 附录 B 确定 本单 位电 子会</h3>
<p className="mb-2 indent-0">计资料归档范围。</p>
<p className="mb-2 indent-0">971</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.2 属于归档范围的电子会计资料及其元数据应由会计核算系统、业务系统传输至电子会计档案管理</h3>
<p className="mb-2 indent-0">信息系统,传输过程安全可控。电子会计档案元数据方案应符合附录 A 的规定。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.3 电子会计资料收集一般通过接口在线自动收集,接口方案见附录 C。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.4 电子会计资料收集时应梳理电子会计资料的来源,归档电子会计资料与来源系统对照关系可参照</h3>
<p className="mb-2 indent-0">表1。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">表1 归档电子会计资料与来源系统对照表</h3>
<p className="mb-2 indent-0">归档电子会计资料来源系统(企业) 来源系统(行政、事业)</p>
<p className="mb-2 indent-0">电子会计凭</p>
<p className="mb-2 indent-0">证类</p>
<p className="mb-2 indent-0">原始凭证</p>
<p className="mb-2 indent-0">记账凭证</p>
<p className="mb-2 indent-0">电子会计账簿</p>
<p className="mb-2 indent-0">电子财务会计报告</p>
<p className="mb-2 indent-0">销售订单</p>
<p className="mb-2 indent-0">出库单</p>
<p className="mb-2 indent-0">销售发票</p>
<p className="mb-2 indent-0">采购订单</p>
<p className="mb-2 indent-0">入库单</p>
<p className="mb-2 indent-0">采购发票</p>
<p className="mb-2 indent-0">报销单</p>
<p className="mb-2 indent-0">银行回单</p>
<p className="mb-2 indent-0">合同</p>
<p className="mb-2 indent-0">报告</p>
<p className="mb-2 indent-0">其他原始单据</p>
<p className="mb-2 indent-0">记账凭证</p>
<p className="mb-2 indent-0">总账、明细账、现金日记账、</p>
<p className="mb-2 indent-0">银行存款日记账等</p>
<p className="mb-2 indent-0">固定资产卡片</p>
<p className="mb-2 indent-0">其他辅助性账簿</p>
<p className="mb-2 indent-0">年报</p>
<p className="mb-2 indent-0">月、季、半年报</p>
<p className="mb-2 indent-0">企业资源计划系统 —</p>
<p className="mb-2 indent-0">税务系统票据管理系统</p>
<p className="mb-2 indent-0">企业资源计划系统 —</p>
<p className="mb-2 indent-0">税务系统票据管理系统</p>
<p className="mb-2 indent-0">报销系统报销系统</p>
<p className="mb-2 indent-0">银企互联系统/</p>
<p className="mb-2 indent-0">网上银行系统</p>
<p className="mb-2 indent-0">银政互联系统/</p>
<p className="mb-2 indent-0">网上银行系统</p>
<p className="mb-2 indent-0">合同管理系统合同管理系统</p>
<p className="mb-2 indent-0">办公自动化系统办公自动化系统</p>
<p className="mb-2 indent-0">票据管理系统票据管理系统</p>
<p className="mb-2 indent-0">会计核算系统会计核算系统</p>
<p className="mb-2 indent-0">其他电子会计资料</p>
<p className="mb-2 indent-0">银行存款余额调节表、</p>
<p className="mb-2 indent-0">银行对账单</p>
<p className="mb-2 indent-0">银企互联系统银政互联系统</p>
<p className="mb-2 indent-0">纳税申报表税务系统 —</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.5 电子会计资料收集时应按照 DA/T</h3>
<div className="h-4" />
<p className="mb-2 indent-0">70中的相关要求进行真实性、完整 性、可用 性和 安全 性检 测。</p>
<p className="mb-2 indent-0">经检测合格的电子会计资料方可登记进入电子会计档案管理信息系统。检测 不合 格的,应重 新收 集并</p>
<p className="mb-2 indent-0">在检测合格后登记进入电子会计档案管理信息系统。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.6 检测合格的电子会计资 料应 根据 附录 B 划定 保管 期限。 电子 会计 档案 保管 期限 分为 永久 和定</h3>
<p className="mb-2 indent-0">期,定期一般为10年和30年,从会计年度结束后的第一天算起。附录B 中的电子会计档案保管期限为</p>
<p className="mb-2 indent-0">最低保管期限,各单位可根据工作需要选择更高的保管期限。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.7 各单位电子会计档案的具体名 称如 有同 附录 B 所列 名称 不一 致的,应比 照类 似档 案的 保管 期限</h3>
<p className="mb-2 indent-0">081</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">办理。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 电子会计资料的整理</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.1 整理时间</h3>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计资料收集完成后应及时整理。其中,电子会计凭证、电子会计账簿、电子固定资产卡片、电</p>
<p className="mb-2 indent-0">子财务会计报告及其他电子会计资料应分别在会计年度结束后1个月内、会计决算后1个月内、固定资</p>
<p className="mb-2 indent-0">产报废后1年内、电子财务会计报告生成后1个月内、会计年度结束后3个月内完成整理。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.2 原则</h3>
<div className="h-4" />
<p className="mb-2 indent-0">整理电子会计资料应按照其自然形成规律和固有特点,保持电子会计资料之间的有机联系,区别不</p>
<p className="mb-2 indent-0">同的保存价值,便于保管和利用。形成电子会计资料数量较少的单位,将电子会计资料按照8.3进行分</p>
<p className="mb-2 indent-0">类后可按件整理。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.3 分类</h3>
<p className="mb-2 indent-0">8.3.1 制定分类方案</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计资料整理时应按照电子会计档案分类方案进行分类。电子会计档案分类方案按照8.3.3</p>
<p className="mb-2 indent-0">进行编制,并嵌入电子会计档案管理信息系统中。</p>
<p className="mb-2 indent-0">8.3.2 电子会计档案分类原则</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计档案分类原则如下。</p>
<p className="mb-2 indent-0">a) 按会计资料形式分类:即按会计资料的内容 形式 分类。一般 分为 会计 凭证、会计 账簿、财务 会</p>
<p className="mb-2 indent-0">计报告、其他会计资料4类。</p>
<p className="mb-2 indent-0">b) 按会计年度分类:即按会计档案针对的会计年度分类。</p>
<p className="mb-2 indent-0">c) 按保管期限分类:即按会计档案的保管期限分类。</p>
<p className="mb-2 indent-0">d) 按组织机构分类:即按会计档案形成的组织机构分类。一般用于总 预算 会计 单位 的会 计档 案</p>
<p className="mb-2 indent-0">分类。</p>
<p className="mb-2 indent-0">e) 按会计类型分类:即按会计档案反映的会计类型分类。一般用于税务机关的会计档案分类。</p>
<p className="mb-2 indent-0">8.3.3 分类方法</p>
<div className="h-4" />
<p className="mb-2 indent-0">推荐使用的分类方法及适用性如下。</p>
<p className="mb-2 indent-0">a) 会计资料形式·会计年度·保管期限分类法,具体应符合附录 D 中 D.1的规定,适用于中、小</p>
<p className="mb-2 indent-0">型单位,即会计档案的年形成量不大的单位,也是目前大多数单位采用的方法。</p>
<p className="mb-2 indent-0">b) 会计年度·会计资料形式·保管期限分类法,具体应符合 D.2的规定,适用于预算单位。</p>
<p className="mb-2 indent-0">c) 会计年度·组织机构·会计资 料形 式· 保管 期限 分类 法,具体 应符 合 D.3 的规 定,适用 于多</p>
<p className="mb-2 indent-0">个部门产生会计档案的单位以及各级总预算单位。</p>
<p className="mb-2 indent-0">d) 会计年度· 会计类型· 会计资料形式· 保管期限分类法,具体应符合 D.4 的规定,适用 于专</p>
<p className="mb-2 indent-0">业性强的各级税务机关。</p>
<p className="mb-2 indent-0">8.3.4 类别号设置</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计档案类别号的设置应科学、简洁,可根据实际扩展。会计 年度 采用4 位阿 拉伯 数字,会计</p>
<p className="mb-2 indent-0">资料形式、保管期限、组织机构、会计类型等类目一般采用大写汉语拼音字母、阿拉伯数字或二者组合编</p>
<p className="mb-2 indent-0">181</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">制,不应有重号。上、下级类目编号间用“·”分隔。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.4 电子会计凭证的组件、组卷及排列</h3>
<p className="mb-2 indent-0">8.4.1 电子会计凭证按记账凭证号组件,记账凭证及其附带的原始凭 证、其他 附件 等组 成一 件。件内</p>
<p className="mb-2 indent-0">按记账凭证、原始凭证、其他附件的顺序排列。</p>
<p className="mb-2 indent-0">8.4.2 电子会计凭证一般按时间组卷,即将电子会计凭证按适当的时间周 期组 卷,卷内 电子 会计 凭证</p>
<p className="mb-2 indent-0">按凭证号先后顺序排列。实行电子会计凭证分类的,按类型结合时间组卷,不同类型的电子会计凭证不</p>
<p className="mb-2 indent-0">应组成一卷。</p>
<p className="mb-2 indent-0">8.4.3 电子会计凭证案卷按时间先后顺序排列。实行电子会计凭证分类的,电子会计凭证案卷按类型</p>
<p className="mb-2 indent-0">结合时间顺序排列。</p>
<p className="mb-2 indent-0">8.4.4 同一记账凭证号的会计凭证存在不同记录形式时,可分别按照不同 记录 形式 进行 整理,并以 元</p>
<p className="mb-2 indent-0">数据的方式记录其关联关系。如记账凭证为电子形式、原始凭证为纸质形式时,记账凭证按电子档案形</p>
<p className="mb-2 indent-0">式整理,成为一件电子档案;原始凭证以纸质档案形式整理,成为一件纸质档案。同时,在记账凭证的相</p>
<p className="mb-2 indent-0">应元数据中注明其原始凭证号,在原始凭证适当位置注明其对应记账凭证号。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.5 电子会计账簿的组件、组卷及排列</h3>
<p className="mb-2 indent-0">8.5.1 电子会计账簿根据6.3按科目、会计周期,结合单个电子文件可存储的数据量组件。其中,电子</p>
<p className="mb-2 indent-0">固定资产卡片按固定资产编号组件,同一固定资产编号的电子固定资产卡片组成一件。</p>
<p className="mb-2 indent-0">8.5.2 电子会计账簿应在一个会计年度内按类型定期组卷。卷内电子会计 账簿 按形 成时 间先 后顺 序</p>
<p className="mb-2 indent-0">排列。</p>
<p className="mb-2 indent-0">8.5.3 不同类型的电子会计账簿按总账、明细分类账、银行存款日记账、现金日记账、固定资产卡片、其</p>
<p className="mb-2 indent-0">他辅助账簿的顺序排列,同一类型的电子会计账簿按时间顺序排列。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.6 电子财务会计报告及其他电子会计资料的组件、组卷及排列</h3>
<p className="mb-2 indent-0">8.6.1 电子财务会计报告按类型结合周期组件。不同类型、不同周期的报告不应组成一件。</p>
<p className="mb-2 indent-0">8.6.2 电子财务会计报告按月报、季报、半年报、年报分别组卷。卷内电子财务会计报告按形成时间先</p>
<p className="mb-2 indent-0">后顺序排列。</p>
<p className="mb-2 indent-0">8.6.3 电子财务会计报告案卷按月报、季报、半年报、年报的顺序排列,同一 类型 电子 财务 会计 报告 案</p>
<p className="mb-2 indent-0">卷按时间先后顺序排列。</p>
<p className="mb-2 indent-0">8.6.4 除前述外的其他电子会计资料按类别结合时间整理组卷,不同类别和保管期限的电子会计资料</p>
<p className="mb-2 indent-0">不应组成一卷。卷内电子会计资料按形成时间顺序排列。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.7 编号</h3>
<div className="h-4" />
<p className="mb-2 indent-0">排列好的电子会计资料应编制档号,档号格式为“[全宗 号-]类别 号-案卷 号-件号(卷内 序号)”。类</p>
<p className="mb-2 indent-0">别号由分类方案给定;案卷号和件号(卷内序号)由4位阿拉伯数字标识,不足4位的,前面用“0”补足。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 电子会计资料的归档</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.1 经整理的电子会计资料在会计年度终了后,可由单位会计管理机构临 时保 管1 年,再移 交单 位档</h3>
<p className="mb-2 indent-0">案管理机构保管。因工作需要确需推迟移交的,应经单位档案管理机构同意,但最长不超过3年。临时</p>
<p className="mb-2 indent-0">保管期间,电子会计档案的保管应符合国家档案管理的有关规定,且出纳人员不应兼管电子会计档案。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.2 单位档案管理机构在接收电子会计档案时应按照 DA/T</h3>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">70的有关要 求进 行检 测,检测 合格 后方</h3>
<p className="mb-2 indent-0">可接收。</p>
<p className="mb-2 indent-0">281</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.3 电子会计档案移交与接收时,双方应通过线上或线下及时办理交接手续。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 电子会计档案的保管</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.1 定期评估</h3>
<div className="h-4" />
<p className="mb-2 indent-0">单位档案管理机构应每年对电子会计档案的可读性进行评估,形成评估报告;如存在因系统软硬件</p>
<p className="mb-2 indent-0">或其他技术升级、更新导致电子会计档案不可读取的风险,应对电子会计档案进行迁移。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.2 迁移评估</h3>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计档案迁移前应进行迁移可行性评估,包括目标载 体、系统、格式 的可 持续 性、安全 性、经济</p>
<p className="mb-2 indent-0">性等评估,并保证迁移过程中电子会计档案真实、完整,过程可控,防止迁移过程中电子会计档案信息丢</p>
<p className="mb-2 indent-0">失或被非法篡改。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.3 存储</h3>
<p className="mb-2 indent-0">10.3.1 电子会计档案应实施在线和离线存储。在线存储按电子会计档案管理系统运行要求实施。离</p>
<p className="mb-2 indent-0">线存储载体应具有较好的耐久性,按优先顺序依次为一次性写光盘、磁带、硬磁盘等。</p>
<p className="mb-2 indent-0">10.3.2 重要电子会计档案应进行一式三套离线存储,三套离线存储载体宜分开保管,有条件的单位应</p>
<p className="mb-2 indent-0">进行异地备份。</p>
<p className="mb-2 indent-0">10.3.3 离线存储载体管理按照 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">15和 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">38给出的要求进行。</p>
<p className="mb-2 indent-0">10.3.4 离线存储应按照保管单位和存储载体容量进行信息组织。应支 持导 入后 形成 交接 凭据,交接</p>
<p className="mb-2 indent-0">凭据的要求参见《电子档案移交与接收办法》,不能用运维备份的信息组织方式进行离线存储,更不能用</p>
<p className="mb-2 indent-0">系统备份文件代替离线存储文件。</p>
<p className="mb-2 indent-0">10.3.5 对离线存储电子会计档案的磁性载体每满2年、光盘每满4年进行一次抽样机读检验,抽样率</p>
<p className="mb-2 indent-0">不低于10%,发现问题应及时采取措施。</p>
<p className="mb-2 indent-0">10.3.6 对磁性载体上的电子档案,应每4年转存一次。原载体同时保留时间不少于4年。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11 电子会计档案的统计</h3>
<div className="h-4" />
<p className="mb-2 indent-0">单位应按照国家档案统计要求及本单位实际需要,对电子会计档案进行统计。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12 电子会计档案的利用</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12.1 单位应制定利用电子会计档案的权限规定,权限设置应科学、合理,并在 电子 会计 档案 管理 信息</h3>
<p className="mb-2 indent-0">系统中实施。当超出权限利用档案时,应进行审批。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12.2 单位应保证电子会计档案在利用过程中不被篡改。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12.3 电子会计档案可根据授权提供在线或离线利用,利用过程应通过日志或其他方式形成记录,记录</h3>
<p className="mb-2 indent-0">信息包括利用人、利用时间、利用方式、利用电子会计档案名称、档号等。利用过程信息应作为电子会计</p>
<p className="mb-2 indent-0">档案元数据进行保存。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13 电子会计档案的定期鉴定及处置</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13.1 单位应定期对已到保管期限的电子会计档案进行鉴定,形成鉴定意见书。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13.2 电子会计档案鉴定工作应由单位档案管理机构牵头,组织单位会计、信息技术、审计、纪检监察等</h3>
<p className="mb-2 indent-0">381</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">机构或人员共同进行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13.3 经鉴定,仍需继续保存的电子会计档案,应重新划定保管期限;经鉴定可以销毁的电子会计档案,</h3>
<p className="mb-2 indent-0">按照以下程序销毁。</p>
<p className="mb-2 indent-0">a) 由单位档案管理机构输出电子会计档案销毁清 册,列明 拟销 毁电 子会 计档 案的 名称、册数、起</p>
<p className="mb-2 indent-0">止年度、档号、应保管期限、已保管期限、应销毁时间等内容。</p>
<p className="mb-2 indent-0">b) 单位负责人、档案 管理 机构 负责 人、档案 管理 机构 经办 人在 电子 会计 档案 销毁 清册 上签 署</p>
<p className="mb-2 indent-0">意见。</p>
<p className="mb-2 indent-0">c) 单位档案管理机构负责组织电子会计档案销毁工作,并与会计管理机构共同派员监销,销毁完</p>
<p className="mb-2 indent-0">成后监销在销毁清单上签字。电子会计档案销 毁应 通过 物理 删除 的方 式进 行,并进 行不 可恢</p>
<p className="mb-2 indent-0">复性验证,销毁清册及记录宜输出纸质文件永久保存。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13.4 保管期满但未结清债权、债务或涉及其他未了事项的电子会计档案不应销毁,应单独抽出立卷或</h3>
<p className="mb-2 indent-0">转存,直至未了事项完结为止。单独抽出立卷或转存的电子会计档案,应在 电子 会计 档案 鉴定 意见 书、</p>
<p className="mb-2 indent-0">电子会计档案销毁清册和电子会计档案保管清册中列明。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13.5 单位按照国家有关规定及时将应进馆的电子档案及其元数据移交进 馆。移交 方法 参见《电子 档</h3>
<p className="mb-2 indent-0">案移交与接收办法》。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">14 元数据管理</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">14.1 在电子会计资料归档和电子会计档案管理过程中应同时捕获、归档和管理元数据。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">14.2 系统开发时应对元数据捕获节点进行规划,明确会计核算系统、业务 系统、电子 会计 档案 管理 信</h3>
<p className="mb-2 indent-0">息系统需捕获的元数据项及其捕获方式,具体应符合附录 A 的规定。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">14.3 应对电子会计档案元数据进行完善,具体 应符 合附 录 A 的规 定,确保 元数 据能 够规 范、客观、准</h3>
<p className="mb-2 indent-0">确地描述电子会计档案的主题内容与形式特征。电子会计档案背景、结构和管理过程元数据不应修改。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15 会计核算系统、业务系统及电子会计档案管理信息系统建设</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15.1 单位会计核算系统、业务系统建设要求</h3>
<div className="h-4" />
<p className="mb-2 indent-0">单位在会计核算系统、业务系统建设时应充分考虑电子会计资料以下归档要求。</p>
<p className="mb-2 indent-0">a) 选择适宜的电子会计资料存储格式,以便于向电 子会 计档 案存 储格 式转 换。为保 证电 子会 计</p>
<p className="mb-2 indent-0">资料的顺利归档,系统实施时尽可能采用符合归 档要 求的 数据 结构 和文 件存 储格 式作 为系 统</p>
<p className="mb-2 indent-0">运行时的文件存储格式。如确无法采用符合归档 要求 的格 式,应在 系统 实施 时对 所使 用的 数</p>
<p className="mb-2 indent-0">据结构和文件格式进行可转换性评估,评估为无法转换或风险较大的业务系统应谨慎使用。</p>
<p className="mb-2 indent-0">b) 对电子会计资料在会计核算系 统、业务 系统 中的 元数 据捕 获节 点与 元素 进行 规划,将应 由会</p>
<p className="mb-2 indent-0">计核算系统、业务系统捕获的电子会计资料元数据全部形成并捕获。有关要求见附录 A。</p>
<p className="mb-2 indent-0">c) 根据系统技术架构选择可行的电子会计资料输出方式,具体见附录 C。</p>
<p className="mb-2 indent-0">d) 确定会计核算系统、业务系统生成电子会计资料归档时的数据包格式。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15.2 电子会计档案管理信息系统功能</h3>
<div className="h-4" />
<p className="mb-2 indent-0">电子会计档案管理信息系统功能应符合附录 E 的规定。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15.3 会计核算系统、业务系统与电子会计档案管理信息系统衔接</h3>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">电子会计资料归档和电子会计档案管理一般通过电子会计档案管 理信 息系 统实 现,也可 通过 在会</h3>
<p className="mb-2 indent-0">计核算系统、业务系统中设计电子会计资料归档和电子会计档案管理功能实现,还可通过将相应功能分</p>
<p className="mb-2 indent-0">481</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">别设计在会计核算系统、业务系统和电子会计档案管理信息系统中实现。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">16 未实施电子会计档案管理信息系统单位电子会计档案保存方法</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">16.1 通过会计核算系统进行会计核算单位的电子会计档案保存方法</h3>
<div className="h-4" />
<p className="mb-2 indent-0">为落实财政部、国家档案局《关于规范电子会计凭证报销入账归档的通 知》中“四、单位 以电 子会 计</p>
<p className="mb-2 indent-0">凭证的纸质打印件作为报销入账归档依据的,必须同时保存打印该纸质件的 电子 会计 凭证”要求,未实</p>
<p className="mb-2 indent-0">施电子会计档案管理信息系统,但通过会计核算系统进行会计核算的单位,电子会计档案应由会计人员</p>
<p className="mb-2 indent-0">按照以下方法进行保存。</p>
<p className="mb-2 indent-0">a) 从会计核算系统下载电子会计 资料,按照 附录 F 中表 F.1 填写 电子 会计 档案 登记 表,对电 子</p>
<p className="mb-2 indent-0">会计资料进行登记。</p>
<p className="mb-2 indent-0">b) 对下载后的电子会计资料进行真实性、完整性、可用性和安全性检测,检测合格后方可接收。</p>
<p className="mb-2 indent-0">c) 对电子会计资料进行组件。将同一凭证号的电 子会 计凭 证拷 贝至 同一 文件 夹,并在 文件 夹内</p>
<p className="mb-2 indent-0">按记账凭证、报销单、发票、其他附件的顺序排列,一个文件夹视为一件;电子会计账簿按科目、</p>
<p className="mb-2 indent-0">会计周期,结合单个电子文件可存储的数据量 组件,每个 会计 周期 为一 件;电子 财务 会计 报告</p>
<p className="mb-2 indent-0">按会计周期组件,一个会计周期为一件。存储格式应符合第6章的要求。</p>
<p className="mb-2 indent-0">d) 划定保管期限。</p>
<p className="mb-2 indent-0">e) 排列电子会计资料。根据分 类方 案和 电子 会计 资料 号顺 序以 件为 单位 依次 排列 电子 会计 资</p>
<p className="mb-2 indent-0">料,编制档号,并将档号、保管期限等信息填入电子会计档案登记表。</p>
<p className="mb-2 indent-0">f) 编制说明文件,包括电子会计档案内容(会计 期间+ 会计 文件 形式)、电子 会计 档案 数量、移交</p>
<p className="mb-2 indent-0">人、其他需要说明的情况(如非 通用 格式 文件 说明)等。例如:2020 年1 月—12 月电 子会 计凭</p>
<p className="mb-2 indent-0">证,共555件,张三移交。</p>
<p className="mb-2 indent-0">g) 电子会计资料、目录(电子会计资料登记表)及说明文件的存储见图 F.1。</p>
<p className="mb-2 indent-0">h) 将目录(电子会计资料登记表)输出纸质文件。</p>
<p className="mb-2 indent-0">i) 将电子会计资料、目录(电子会计资料登记表)及其纸质文件、说明文件和其他纸质档案在规定</p>
<p className="mb-2 indent-0">时限内移交档案人员。</p>
<p className="mb-2 indent-0">j) 采用多重备份、定期检测等方法,保证电子会计档案在保管期限内真实、完整、安全、可用。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">16.2 未通过会计核算系统进行会计核算单位的电子会计凭证保存方法</h3>
<div className="h-4" />
<p className="mb-2 indent-0">为落实财政部、国家档案局《关于规范电子会计凭证报销入账归档的通 知》中“四、单位 以电 子会 计</p>
<p className="mb-2 indent-0">凭证的纸质打印件作为报销入账归档依据的,必须同时保存打印该纸质件的 电子 会计 凭证”要求,未实</p>
<p className="mb-2 indent-0">施电子会计档案管理信息系统且未通过会计核算系统进行会计核算的单位,会计资料主要为纸质载体,</p>
<p className="mb-2 indent-0">从外部接收的电子会计凭证应由会计人员按以下方法进行保存。</p>
<p className="mb-2 indent-0">a) 接收电子会计凭证,填写电子会计资料登记表,对电子会计资料进行登记。</p>
<p className="mb-2 indent-0">b) 对接收的电子会计凭证进行真实性、完整性、可用性和安全性检测,检测合格后方可接收。</p>
<p className="mb-2 indent-0">c) 根据相应纸质载体会计凭证所在案卷(或册)号在存 储载 体中 建立 卷(或册)文件 夹,将电 子会</p>
<p className="mb-2 indent-0">计凭证拷贝至相应卷(或册)文件夹。</p>
<p className="mb-2 indent-0">d) 根据相应纸质载体会计凭证所在 案卷(或册)号,将档 号、保管 期限 等信 息填 入电 子会 计档 案</p>
<p className="mb-2 indent-0">登记表中。</p>
<p className="mb-2 indent-0">e) 编制说明文件,包括会计期间、电子会计凭证名称、数量、移交人、其他需要说明的情况(如非通</p>
<p className="mb-2 indent-0">用格式文件说明)等。例如:2020年1月—12月电子发票,共555件,张三移交。</p>
<p className="mb-2 indent-0">f) 电子会计凭证、目录(电子会计档案登记表)及说明文件的存储见图 F.2。</p>
<p className="mb-2 indent-0">g) 将目录(电子会计档案登记表)输出纸质文件。</p>
<p className="mb-2 indent-0">581</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">h) 将整理好的电子会计凭证、目录(电子 会计 档案 登记 表)及其 纸质 文件、说明 文件 和其 他纸 质</p>
<p className="mb-2 indent-0">档案在规定时限内移交档案人员。</p>
<p className="mb-2 indent-0">i) 采用多重备份、定期检测等方法,保证电子会计档案在保管期限内真实、完整、安全、可用。</p>
<p className="mb-2 indent-0">681</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 A</h3>
<p className="mb-2 indent-0">(规范性)</p>
<p className="mb-2 indent-0">电子会计档案元数据方案</p>
<p className="mb-2 indent-0">本方案参考 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">46,结合目前电子会计资料归档和电子会计档案 管理 的实 际制 定,表 A.1 给出</p>
<p className="mb-2 indent-0">了文件实体元数据项,表 A.2给出了机构人员实体元数据项,表 A.3给出了业务实体元数据项,表 A.4</p>
<p className="mb-2 indent-0">给出了实体关系元数据项。</p>
<p className="mb-2 indent-0">表 A.1 文件实体元数据</p>
<p className="mb-2 indent-0">编号元数据编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M1 聚合层次</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M2 来源</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M3 档案馆名称电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M4 档案馆代码电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M5 全宗名称电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M6 立档单位名称电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M7 电子文件号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M8 档号</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M9 全宗号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M10 目录号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M11 年度电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M12 保管期限电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M13 机构或问题会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M14 类别号会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M15 室编案卷号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M16 馆编案卷号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M17 室编件号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M18 馆编件号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M19 文档序号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M20 页号电子会计档案管理信息系统</h3>
<p className="mb-2 indent-0">781</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.1 文件实体元数据</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">编号元数据编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M21 内容描述</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M22 题名会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M23 并列题名会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M24 副题名会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M25 说明题名文字会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M26 主题词会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M27 关键词会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M28 人名会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M29 摘要电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M30 分类号会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M31 文件编号会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M32 责任者会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M33 日期会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M34 文种会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M35 紧急程度会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M36 主送会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M37 抄送会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M38 密级会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M39 保密期限会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M40 会计年度会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M41 会计月份会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M42 本位币会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M43 编制人会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M44 编制日期会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M45 审核人会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M46 审核日期会计核算系统</h3>
<p className="mb-2 indent-0">881</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.1 文件实体元数据</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">编号元数据编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M47 形式特征</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M48 文件组合类型会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M49 件数会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M50 页数会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M51 语种会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M52 稿本会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M53 电子属性</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M54 格式信息会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M55 计算机文件名会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M56 计算机文件大小会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M57 文档创建程序会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M58 信息系统描述会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M59 数字化属性</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M60 数字化对象形态会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M61 扫描分辨率会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M62 扫描色彩模式会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M63 图像压缩方案会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M64 电子签名</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M65 签名规则会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M66 签名时间会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M67 签名人会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M68 签名结果会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M69 证书会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M70 证书引证会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M71 签名算法标识会计核算系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M72 存储位置</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M73 当前位置电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M74 脱机载体编号电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M75 脱机载体存址电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M76 缩微号电子会计档案管理信息系统</h3>
<p className="mb-2 indent-0">981</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.1 文件实体元数据</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">编号元数据编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M77 权限管理</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M78 知识产权说明会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M79 授权对象会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M80 授权行为会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M81 控制标识会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M82 附注</h3>
<p className="mb-2 indent-0">表 A.2 机构人员实体元数据</p>
<p className="mb-2 indent-0">编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M83 机构人员类型会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M84 机构人员名称会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M85 组织机构代码会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M86 个人职位会计核算系统/电子会计档案管理信息系统</h3>
<p className="mb-2 indent-0">表 A.3 业务实体元数据</p>
<p className="mb-2 indent-0">编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M87 业务状态会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M88 业务行为会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M89 行为时间会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M90 行为依据会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M91 行为描述会计核算系统/电子会计档案管理信息系统</h3>
<p className="mb-2 indent-0">表 A.4 实体关系元数据</p>
<p className="mb-2 indent-0">编号元数据来源系统</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M92 实体标识符会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M93 关系类型会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M94 关系会计核算系统/电子会计档案管理信息系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">M95 关系描述会计核算系统/电子会计档案管理信息系统</h3>
<p className="mb-2 indent-0">091</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 B</h3>
<p className="mb-2 indent-0">(规范性)</p>
<p className="mb-2 indent-0">会计档案归档范围与保管期限表</p>
<p className="mb-2 indent-0">表 B.1规定了企业和其他组织会计档案保管期限,表 B.2规定了财政总预算、行政单位、事业单位</p>
<p className="mb-2 indent-0">和税收会计档案保管期限。税务机关的税务经费会计档案保管期限,按照 行政 单位 会计 档案 保管 期限</p>
<p className="mb-2 indent-0">规定办理。</p>
<p className="mb-2 indent-0">表 B.1 企业和其他组织会计档案保管期限表</p>
<p className="mb-2 indent-0">序号档案名称保管期限备注</p>
<p className="mb-2 indent-0">一会计凭证</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">1 原始凭证 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 记账凭证 30年</h3>
<p className="mb-2 indent-0">二会计账簿</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">3 总账 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4 明细账 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 日记账 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 固定资产卡片固定资产报废清理后再保管5年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 其他辅助性账簿 30年</h3>
<p className="mb-2 indent-0">三财务会计报告</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 月度、季度、半年度财务会计报告 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 年度财务会计报告永久</h3>
<p className="mb-2 indent-0">四其他会计资料</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 银行存款余额调节表 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11 银行对账单 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12 纳税申报表 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13 会计档案移交清册 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">14 会计档案保管清册永久</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15 会计档案销毁清册永久</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">16 会计档案鉴定意见书永久</h3>
<p className="mb-2 indent-0">191</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 B.2 财政总预算、行政单位、事业单位和税收会计档案保管期限表</p>
<p className="mb-2 indent-0">序号档案名称</p>
<p className="mb-2 indent-0">保管期限</p>
<p className="mb-2 indent-0">财政</p>
<p className="mb-2 indent-0">总预算</p>
<p className="mb-2 indent-0">行政单位</p>
<p className="mb-2 indent-0">事业单位</p>
<p className="mb-2 indent-0">税收</p>
<p className="mb-2 indent-0">会计</p>
<p className="mb-2 indent-0">备注</p>
<p className="mb-2 indent-0">一会计凭证</p>
<p className="mb-2 indent-0">1</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">国家金库编 送的 各种 报表 及缴 库退</h3>
<p className="mb-2 indent-0">库凭证 10年 10年</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 各收入机关编送的报表 10年</h3>
<p className="mb-2 indent-0">3</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">行政 单位 和事 业单 位的 各种 会计</h3>
<p className="mb-2 indent-0">凭证 30年包括:原始凭证、记账凭证和传票汇总表</p>
<p className="mb-2 indent-0">4</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">财政 总预 算拨 款凭 证和 其他 会计</h3>
<p className="mb-2 indent-0">凭证 30年包括:拨款凭证和其他会计凭证</p>
<p className="mb-2 indent-0">二会计账簿</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 日记账 30年 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 总账 30年 30年 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 税收日记账(总账) 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 明细分类、分户账或登记簿 30年 30年 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 行政单位和事业单位固定资产卡片固定资产报废清理后保管5年</h3>
<p className="mb-2 indent-0">三财务会计报告</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 政府综合财务报告永久</h3>
<p className="mb-2 indent-0">下级财政、本级部门和单位报送的</p>
<p className="mb-2 indent-0">保管2年</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11 部门财务报告永久所属单位报送的保管2年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12 财政总决算永久</h3>
<p className="mb-2 indent-0">下级财政、本级部门和单位报送的</p>
<p className="mb-2 indent-0">保管2年</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">13 部门决算永久所属单位报送的保管2年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">14 税收年报(决算) 永久</h3>
<p className="mb-2 indent-0">291</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 B.2 财政总预算、行政单位、事业单位和税收会计档案保管期限表</p>
<div className="h-4" />
<p className="mb-2 indent-0">(续)</p>
<p className="mb-2 indent-0">序号档案名称</p>
<p className="mb-2 indent-0">保管期限</p>
<p className="mb-2 indent-0">财政</p>
<p className="mb-2 indent-0">总预算</p>
<p className="mb-2 indent-0">行政单位</p>
<p className="mb-2 indent-0">事业单位</p>
<p className="mb-2 indent-0">税收</p>
<p className="mb-2 indent-0">会计</p>
<p className="mb-2 indent-0">备注</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">15 国家金库年报(决算) 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">16 基本建设拨、贷款年报(决算) 10年</h3>
<p className="mb-2 indent-0">17</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">行政单 位和 事业 单位 会计 月、季度</h3>
<p className="mb-2 indent-0">报表 10年所属单位报送的保管2年</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">18 税收会计报表 10年所属税务机关报送的保管2年</h3>
<p className="mb-2 indent-0">四其他会计资料</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">19 银行存款余额调节表 10年 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">20 银行对账单 10年 10年 10年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">21 会计档案移交清册 30年 30年 30年</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">22 会计档案保管清册永久永久永久</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">23 会计档案销毁清册永久永久永久</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">24 会计档案鉴定意见书永久永久永久</h3>
<p className="mb-2 indent-0">391</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 C</h3>
<p className="mb-2 indent-0">(资料性)</p>
<p className="mb-2 indent-0">会计核算系统、业务系统与电子会计档案管理信息系统接口方案</p>
<p className="mb-2 indent-0">C.1 接口方式</p>
<p className="mb-2 indent-0">C.1.1 Web</p>
<div className="h-4" />
<p className="mb-2 indent-0">Service服务调用方式</p>
<p className="mb-2 indent-0">基于 Web</p>
<div className="h-4" />
<p className="mb-2 indent-0">Service服务调用的归档接口示意见图 C.1。</p>
<p className="mb-2 indent-0">图 C.1 Web</p>
<div className="h-4" />
<p className="mb-2 indent-0">Service服务调用方式示意图</p>
<p className="mb-2 indent-0">数据流说明:</p>
<p className="mb-2 indent-0">①</p>
<div className="h-4" />
<p className="mb-2 indent-0">服务请求:会计核算系统、业务系统发起服务请求;</p>
<p className="mb-2 indent-0">②</p>
<div className="h-4" />
<p className="mb-2 indent-0">服务响应:电子会计档案管理信息系统 接收 服务 请求,处理 完成 后返 回结 果并 反馈 至会 计核 算</p>
<p className="mb-2 indent-0">系统、业务系统。</p>
<p className="mb-2 indent-0">C.1.2 中间库方式</p>
<p className="mb-2 indent-0">基于中间库的归档接口示意见图 C.2。</p>
<p className="mb-2 indent-0">491</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">图 C.2 中间库方式示意图</p>
<p className="mb-2 indent-0">数据流说明:</p>
<p className="mb-2 indent-0">①</p>
<div className="h-4" />
<p className="mb-2 indent-0">数据上传:会计核算系统、业务系统将待归档数据传输至中间库;</p>
<div className="h-4" />
<p className="mb-2 indent-0">②</p>
<div className="h-4" />
<p className="mb-2 indent-0">数据提取:电子会计档案管理信息系统从中间库提取待归档数据;</p>
<p className="mb-2 indent-0">③</p>
<div className="h-4" />
<p className="mb-2 indent-0">结果反馈:电子会计档案管理信息系统完成待归档数据提取处理后,将处理结果反馈至中间库;</p>
<p className="mb-2 indent-0">④</p>
<div className="h-4" />
<p className="mb-2 indent-0">结果反馈:会计核算系统、业务系统从中间库提取处理结果。</p>
<p className="mb-2 indent-0">C.2 接口功能</p>
<p className="mb-2 indent-0">C.2.1 会计核算系统、业务系统接口功能</p>
<p className="mb-2 indent-0">会计核算系统、业务系统接口功能参照下列要求:</p>
<p className="mb-2 indent-0">a) 归档前将待归档电子会计资料及其元数据按推荐格式封装成归档信息包;</p>
<p className="mb-2 indent-0">b) 将归档信息包传输至指定位置(或者 调用 对方 接口),传输 过程 中归 档信 息包 信息 不丢 失、不</p>
<p className="mb-2 indent-0">被非法更改;</p>
<p className="mb-2 indent-0">c) 接收归档信息包接收方的反馈消息,包括归档成功或失败消息、失败故障代码等;</p>
<p className="mb-2 indent-0">d) 对归档成功的电子会计资料进行已归档标记,以防止重复归档,并能 取消 标记,在人 工干 预下</p>
<p className="mb-2 indent-0">重新归档;</p>
<p className="mb-2 indent-0">e) 记录归档电子会计资料类型、归档时间、归档状态,并能够实现按照归档电子会计资料类型、归</p>
<p className="mb-2 indent-0">档时间、归档状态组合查询。</p>
<p className="mb-2 indent-0">C.2.2 电子会计档案管理信息系统接口功能</p>
<p className="mb-2 indent-0">电子会计档案管理信息系统接口功能参照下列要求:</p>
<p className="mb-2 indent-0">a) 接收会计核算系统、业务系统传递来的数据包(或者从指定位置提取数据),并正确解析;</p>
<p className="mb-2 indent-0">b) 对会计核算系统、业务系统提交 归档 的电 子会 计资 料及 其元 数据 的真 实性、完整 性、可用 性、</p>
<p className="mb-2 indent-0">安全性进行检测,检测不合格的拒绝接收;</p>
<p className="mb-2 indent-0">c) 将解析后的电子会计资料及其元数据存储在数据库、文件库,并保存过程日志;</p>
<p className="mb-2 indent-0">d) 向会计核算系统、业务系统发送电子会计资料归档成功或失败消息,以及失败故障代码;</p>
<p className="mb-2 indent-0">e) 在归档信息包接收、解析和数据存储等过程中,信息不丢失、不被非法更改;</p>
<p className="mb-2 indent-0">f) 记录归档电子会计资料类型、归档时间、归档状态,并能够按照归档电子会计资料类型、归档时</p>
<p className="mb-2 indent-0">间、归档状态组合查询。</p>
<p className="mb-2 indent-0">591</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">C.3 接口建设管理</p>
<p className="mb-2 indent-0">接口建设管理参照下列要求:</p>
<p className="mb-2 indent-0">a) 归档接口应与会计核算系统、业务系统,同设 计、同开 发、同测 试和 同实 施,实施 时未 开发 归档</p>
<p className="mb-2 indent-0">接口的会计核算系统、业务系统应及时通过二次开发实现;</p>
<p className="mb-2 indent-0">b) 为保证电子会计资料真实性、完整性、可用性、安全性,应将检测功能 嵌入 归档 接口,减少 人工</p>
<p className="mb-2 indent-0">干预;</p>
<p className="mb-2 indent-0">c) 归档接口开发时应进行充分测试,并经专家评审,以确认功能要求达到设计目标要求;</p>
<p className="mb-2 indent-0">d) 归档接口投入运行后,应安排专人对接口运行情况进行持续跟踪,发现问题及时处理;</p>
<p className="mb-2 indent-0">e) 对于现存会计核算系统、业务系统,应联系会计 核算 系统、业务 系统 原开 发商 或组 织自 有力 量</p>
<p className="mb-2 indent-0">进行接口开发;</p>
<p className="mb-2 indent-0">f) 对于新开发会计核算系统、业务系统,应在 开发 初期 将档 案部 门纳 入实 施团 队,提出 会计 核算</p>
<p className="mb-2 indent-0">系统、业务系统电子会计资料归档功能要求,并对归档功能进行测试确认;</p>
<p className="mb-2 indent-0">g) 会计核算系统、业务系统和电子会计档案管理信息系统更新应充分论 证对 归档 接口 功能 的影</p>
<p className="mb-2 indent-0">响,确保归档接口能够正常运行;</p>
<p className="mb-2 indent-0">h) 应制 定应 急机 制,在会 计核 算系 统、业务 系统 和电 子会 计档 案管 理信 息系 统因 升级、系统 故</p>
<p className="mb-2 indent-0">障、病毒感染等原因影响接口功能时立即启动应急响应。</p>
<p className="mb-2 indent-0">691</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 D</h3>
<p className="mb-2 indent-0">(规范性)</p>
<p className="mb-2 indent-0">电子会计档案分类方案</p>
<p className="mb-2 indent-0">D.1 会计资料形式·会计年度·保管期限分类法</p>
<p className="mb-2 indent-0">具体分类方法如下:</p>
<p className="mb-2 indent-0">1</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计凭证</p>
<p className="mb-2 indent-0">2009年</p>
<p className="mb-2 indent-0">30年(收款凭证、付款凭证、转账凭证)</p>
<p className="mb-2 indent-0">2010年</p>
<p className="mb-2 indent-0">30年(收款凭证、付款凭证、转账凭证)</p>
<p className="mb-2 indent-0">2</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计账簿</p>
<p className="mb-2 indent-0">2009年</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年(总账、明细分类账、银行存款日记账、现金日记账、其他辅助账簿)</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年或固定资产报废后5年(固定资产卡片)</p>
<p className="mb-2 indent-0">2010年</p>
<div className="h-4" />
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年(总账、明细分类账、银行存款日记账、现金日记账、其他辅助账簿)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年或固定资产报废后5年(固定资产卡片)</p>
<p className="mb-2 indent-0">3</p>
<div className="h-4" />
<p className="mb-2 indent-0">财务会计报告</p>
<p className="mb-2 indent-0">2009年</p>
<div className="h-4" />
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年度财务会计报告&lt;决算&gt;)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(月度财务会计报告、季度财务会计报告、半年财务会计报告)</p>
<p className="mb-2 indent-0">2010年</p>
<div className="h-4" />
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年度财务会计报告&lt;决算&gt;)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(月度财务会计报告、季度财务会计报告、半年财务会计报告)</p>
<p className="mb-2 indent-0">4</p>
<div className="h-4" />
<p className="mb-2 indent-0">其他会计资料</p>
<div className="h-4" />
<p className="mb-2 indent-0">2009年</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年度内部控制评价报告、年度内 部控 制审 计报 告、会计 档案 保管 清册、会计 档案</p>
<p className="mb-2 indent-0">销毁清册)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年(会计档案移交清册)</p>
<div className="h-4" />
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(银行余额调节表、银行对账单)</p>
<p className="mb-2 indent-0">2010年</p>
<p className="mb-2 indent-0">……</p>
<p className="mb-2 indent-0">本分类方法适用于大多数的中、小型单位,即会计档案的年形成 量不 大的 单位,也是 目前 大多 数单</p>
<p className="mb-2 indent-0">位采用的方法。</p>
<p className="mb-2 indent-0">D.2 会计年度·会计资料形式·保管期限分类法</p>
<p className="mb-2 indent-0">具体分类方法如下:</p>
<p className="mb-2 indent-0">2009年</p>
<p className="mb-2 indent-0">791</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">1</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计凭证</p>
<p className="mb-2 indent-0">30年(收款凭证、付款凭证、转账凭证)</p>
<p className="mb-2 indent-0">2</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计账簿</p>
<div className="h-4" />
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年(总账、明细分类账、银行存款日记账、现金日记账、其他辅助账簿)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年或固定资产报废后5年(固定资产卡片)</p>
<p className="mb-2 indent-0">3</p>
<div className="h-4" />
<p className="mb-2 indent-0">财务会计报告</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年度财务会计报告&lt;决算&gt;)</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(月度财务会计报告、季度财务会计报告、半年财务会计报告)</p>
<p className="mb-2 indent-0">4</p>
<div className="h-4" />
<p className="mb-2 indent-0">其他会计资料</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年度内部控制评价报告、年度 内部 控制 审计 报告、会计 档案 保管 清册、会计 档案</p>
<p className="mb-2 indent-0">销毁清册)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">30年(会计档案移交清册)</p>
<div className="h-4" />
<p className="mb-2 indent-0">3.</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(银行余额调节表、银行对账单)</p>
<p className="mb-2 indent-0">2010年</p>
<div className="h-4" />
<p className="mb-2 indent-0">1</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计凭证</p>
<p className="mb-2 indent-0">30年(收款凭证、付款凭证、转账凭证)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计账簿</p>
<p className="mb-2 indent-0">1.30年(总账、明细分类账、银行存款日记账、现金日记账、其他辅助账簿)</p>
<p className="mb-2 indent-0">2.30年或固定资产报废后5年(固定资产卡片)</p>
<div className="h-4" />
<p className="mb-2 indent-0">3</p>
<div className="h-4" />
<p className="mb-2 indent-0">财务会计报告</p>
<p className="mb-2 indent-0">1.永久(年度财务会计报告&lt;决算&gt;)</p>
<p className="mb-2 indent-0">2.10年(月度财务会计报告、季度财务会计报告、半年财务会计报告)</p>
<div className="h-4" />
<p className="mb-2 indent-0">4</p>
<div className="h-4" />
<p className="mb-2 indent-0">其他会计资料</p>
<p className="mb-2 indent-0">1.永久(年度内部控制评价报告、年度内部控制审计报告、会计档案保管清册、会计档案销</p>
<p className="mb-2 indent-0">毁清册)</p>
<p className="mb-2 indent-0">2.30年(会计档案移交清册)</p>
<p className="mb-2 indent-0">3.10年(银行余额调节表、银行对账单)</p>
<p className="mb-2 indent-0">本分类方法适用于预算单位。</p>
<p className="mb-2 indent-0">D.3 会计年度·组织机构·会计资料形式·保管期限分类法</p>
<p className="mb-2 indent-0">具体分类方法如下:</p>
<p className="mb-2 indent-0">2009年</p>
<p className="mb-2 indent-0">1国库处</p>
<p className="mb-2 indent-0">1.会计凭证(30年)</p>
<p className="mb-2 indent-0">2.会计账簿(30年)</p>
<p className="mb-2 indent-0">a)30年(总账、明细分类账、银行存款日记账、现金日记账、其他辅助账簿)</p>
<p className="mb-2 indent-0">b)30年或固定资产报废后5年(固定资产卡片)</p>
<p className="mb-2 indent-0">3.财务会计报告</p>
<div className="h-4" />
<p className="mb-2 indent-0">a)永久(年度财务会计报告&lt;决算&gt;)</p>
<p className="mb-2 indent-0">b)10年(月度财务会计报告、季度财务会计报告、半年财务会计报告)</p>
<p className="mb-2 indent-0">4.其他会计资料</p>
<p className="mb-2 indent-0">a)永久(年度内部控制评价报告、年度内部控制审计报告、会计档案保管清册、会计档案销</p>
<p className="mb-2 indent-0">891</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">毁清册)</p>
<p className="mb-2 indent-0">b)30年(会计档案移交清册)</p>
<p className="mb-2 indent-0">c)10年(银行余额调节表、银行对账单)</p>
<div className="h-4" />
<p className="mb-2 indent-0">2预算处</p>
<p className="mb-2 indent-0">a)30年(总账、明细分类账、银行存款日记账、现金日记账、其他辅助账簿)</p>
<p className="mb-2 indent-0">b)30年或固定资产报废后5年(固定资产卡片)</p>
<div className="h-4" />
<p className="mb-2 indent-0">3会计处</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">财务会计报告</p>
<p className="mb-2 indent-0">……</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">其他会计资料</p>
<p className="mb-2 indent-0">……</p>
<div className="h-4" />
<p className="mb-2 indent-0">2010年</p>
<p className="mb-2 indent-0">……</p>
<p className="mb-2 indent-0">本分类方法适用于多个部门产生会计档案的单位以及各级总预算单位。</p>
<p className="mb-2 indent-0">D.4 会计年度·会计类型·会计资料形式·保管期限分类法</p>
<p className="mb-2 indent-0">具体分类方法如下:</p>
<div className="h-4" />
<p className="mb-2 indent-0">2009年</p>
<p className="mb-2 indent-0">1税收会计</p>
<p className="mb-2 indent-0">1.会计凭证</p>
<p className="mb-2 indent-0">2.会计账簿</p>
<p className="mb-2 indent-0">3.财务会计报告</p>
<p className="mb-2 indent-0">a)</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年报)</p>
<p className="mb-2 indent-0">b)</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(季报、月报)</p>
<p className="mb-2 indent-0">4.其他会计资料</p>
<div className="h-4" />
<p className="mb-2 indent-0">2经费会计</p>
<p className="mb-2 indent-0">1.</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计凭证</p>
<p className="mb-2 indent-0">2.</p>
<div className="h-4" />
<p className="mb-2 indent-0">会计账簿</p>
<p className="mb-2 indent-0">3.财务会计报告</p>
<p className="mb-2 indent-0">a)</p>
<div className="h-4" />
<p className="mb-2 indent-0">永久(年报)</p>
<p className="mb-2 indent-0">b)</p>
<div className="h-4" />
<p className="mb-2 indent-0">10年(季报、月报)</p>
<p className="mb-2 indent-0">4.其他会计资料</p>
<div className="h-4" />
<p className="mb-2 indent-0">2010年</p>
<div className="h-4" />
<p className="mb-2 indent-0">……</p>
<p className="mb-2 indent-0">本分类方法适用于专业性强的各级税务机关。</p>
<p className="mb-2 indent-0">991</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 E</h3>
<div className="h-4" />
<p className="mb-2 indent-0">(规范性)</p>
<p className="mb-2 indent-0">电子会计档案管理信息系统功能需求</p>
<p className="mb-2 indent-0">E.1 收集功能</p>
<p className="mb-2 indent-0">E.1.1 电子会计资料手工登记</p>
<p className="mb-2 indent-0">电子会计资料手工登记参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持手工输入电子会计资料元数据及上传电子会计资料并赋予唯一编号;</p>
<p className="mb-2 indent-0">b) 应支持所输入的元数据项在满足国家有关标准的前提下,可根据需要增减;</p>
<p className="mb-2 indent-0">c) 应支持元数据校验功能,可对元数据根据权限进行更改、删除、检索等操作。</p>
<p className="mb-2 indent-0">E.1.2 在线接收</p>
<p className="mb-2 indent-0">在线接收参照下列需求。</p>
<p className="mb-2 indent-0">a) 应支持与业务系统的集成,能够从报销系统、核算系统、报表系统、税务系统等会计业务系统接</p>
<p className="mb-2 indent-0">收电子会计资料及其元数据,并对所接收的电子会计资料赋予唯一编号。</p>
<div className="h-4" />
<p className="mb-2 indent-0">b) 应支持接收立档单位移交的,符合国家档案局、财政部相关标准规定的 电子 会计 资料,包括 但</p>
<p className="mb-2 indent-0">不限于:</p>
<p className="mb-2 indent-0">1) 文本文件;</p>
<p className="mb-2 indent-0">2) 版式文件;</p>
<p className="mb-2 indent-0">3) 数据文件;</p>
<p className="mb-2 indent-0">4) 图像文件;</p>
<p className="mb-2 indent-0">5) 音视频文件。</p>
<p className="mb-2 indent-0">c) 应支持对接收的电子会计资料全文进行格式转换的功能,生成符合国家、行业相关标准的电子</p>
<p className="mb-2 indent-0">文件格式。EXCEL 等格式文件转换为版式文件后 涉及 跨页 等问 题,不能 完整 阅读 的,宜支 持</p>
<p className="mb-2 indent-0">原始格式在线查看。</p>
<p className="mb-2 indent-0">d) 应支持电子会计资料元数据与纸质会计资料同步接收,支持自动建立 电子 会计 资料 元数 据与</p>
<p className="mb-2 indent-0">会计资料全文的关联关系。</p>
<p className="mb-2 indent-0">e) 应支持不限制接收电子会计档案的数量,支持对电子会计档案的接收数量、不合格退回数量等</p>
<p className="mb-2 indent-0">的统计与查询。</p>
<p className="mb-2 indent-0">f) 宜支持在接收或捕获时,对重复接收或捕获的电子会计档案进行识别,系统应发出警告。</p>
<p className="mb-2 indent-0">g) 应能够生成与移交清单对应的电子档案接收单,并自动赋予责任 人、时间 以及 相关 信息,提供</p>
<p className="mb-2 indent-0">输出等功能。</p>
<p className="mb-2 indent-0">E.1.3 电子会计资料和电子会计档案离线接收</p>
<p className="mb-2 indent-0">电子会计资料和电子会计档案离线接收参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持电子会计 资料、电子 会计 档案 数据 的离 线批 量导 入功 能,支持 常见 的 EXCEL、DBF、</p>
<p className="mb-2 indent-0">MDB、XML、TXT、ET 等格式文件的导入接收,并实现元数据和电子全文的自动关联;</p>
<p className="mb-2 indent-0">002</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">b) 应支持接收导入过程中数据的校验,如是否唯一、是否可以为空、日期格式是否正确等;</p>
<p className="mb-2 indent-0">c) 应支持如出现部分数据导入失败时,提供报 告说 明;如出 现中 断(如断 电、断网、死机 等),应支</p>
<p className="mb-2 indent-0">持再次导入时,断点续传功能;</p>
<p className="mb-2 indent-0">d) 应支持导入后形成交接凭据,交接凭据的要求参见《电子档案移交与接收办法》。</p>
<p className="mb-2 indent-0">E.1.4 接收检测</p>
<p className="mb-2 indent-0">接收检测参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支 持对 归档 接收 的电 子会 计资 料按 照 DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">70 进行 真实 性、完整 性、可用 性、安全 性的</h3>
<p className="mb-2 indent-0">检测;</p>
<p className="mb-2 indent-0">b) 应支持检测后显示详细检测结果及问题说明;</p>
<p className="mb-2 indent-0">c) 应支持检测完成后以件为单位形成检测业务实体元数据,保存在元数据中;</p>
<p className="mb-2 indent-0">d) 应支持对接收的电子会计资料全文进行格式转换,包括按件转换和批量转换。</p>
<p className="mb-2 indent-0">E.2 归档文件整理功能</p>
<p className="mb-2 indent-0">E.2.1 划定保管期限</p>
<p className="mb-2 indent-0">应支持按照电子会计档案保管期限表对归档电子会计资料划定保管期限。</p>
<p className="mb-2 indent-0">E.2.2 组件</p>
<p className="mb-2 indent-0">组件参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对来自于同一业务系统或不同业务系统的归档电子会计资料按照8.4、8.5、8.6给出的</p>
<p className="mb-2 indent-0">要求将归档电子会计资料组成件,并保持会计事项文件之间的有机联系;</p>
<p className="mb-2 indent-0">b) 应支持对件内电子会计资料的子件进行排序;</p>
<p className="mb-2 indent-0">c) 应支持组件后的撤销组件、重新组件等。</p>
<p className="mb-2 indent-0">E.2.3 分类</p>
<p className="mb-2 indent-0">应支持按照设定的会计档案分类方案,将电子会计资料进行分类,并给定类别号。</p>
<p className="mb-2 indent-0">E.2.4 组成保管单位</p>
<p className="mb-2 indent-0">组成保管单位参照下列需求。</p>
<p className="mb-2 indent-0">a) 应支持对归档电子会计资料按照 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">39规则自动或在人工干预下组成卷或盒,并能按规则</p>
<p className="mb-2 indent-0">将卷(盒)内电子会计资料排序定位,包括但不限制:</p>
<p className="mb-2 indent-0">1) 应支持电子会计资料元数据和档案标引信息的自动生成功能;</p>
<p className="mb-2 indent-0">2) 应支持电子会计资料目录的自动生成功能。</p>
<p className="mb-2 indent-0">b) 应支持在人工干预下调整归档会计资料所属卷(盒)并重新排序定位。</p>
<p className="mb-2 indent-0">E.2.5 编号</p>
<p className="mb-2 indent-0">应支持依据档号编制规则形成档号,所形成档号唯一、合理、稳定、可扩充、简单。</p>
<p className="mb-2 indent-0">E.2.6 编目</p>
<p className="mb-2 indent-0">编目参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持提供规范的会计档案目录模板,能按 照 DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">39 套打 出案 卷封 面、卷内 目录 或归 档文</h3>
<p className="mb-2 indent-0">102</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">件目录、全引目录、备考表、卷(盒)封面和脊背等;</p>
<p className="mb-2 indent-0">b) 应支持进行目录模板制作,可以对模板中的字体、打印内容、排序方式等进行调整;</p>
<p className="mb-2 indent-0">c) 应支持打印预览功能,宜支持多模板批量生成和打印功能;</p>
<p className="mb-2 indent-0">d) 应支持根据模板对选定的归档电子会计资料或电子会计档案形成相应的目录;</p>
<p className="mb-2 indent-0">e) 应支持按照 DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">39格式将案卷封面、卷内目 录、归档 文件 目录 或全 引目 录、案卷 目录、备考</p>
<p className="mb-2 indent-0">表等通用格式文件导出功能;</p>
<p className="mb-2 indent-0">f) 应支持会计档案编目操作过程有审计跟踪日志,可追踪、审计和审查。</p>
<p className="mb-2 indent-0">E.2.7 关联关系建立</p>
<p className="mb-2 indent-0">关联关系建立参照下列需求。</p>
<p className="mb-2 indent-0">a) 应支持建立同一会计档案及其子件间关联关系的功能,包括但不限于:</p>
<p className="mb-2 indent-0">1) 应支持建立电子记账凭证与电子原始凭证的关联关系;</p>
<p className="mb-2 indent-0">2) 应支持归档电子会计资料主件与附件之间的关联关系;</p>
<p className="mb-2 indent-0">3) 应支持电子会计资料全文与元数据间建立关联关系;</p>
<p className="mb-2 indent-0">4) 应支持同一核算单位的电子会计档案之间建立关联关系。</p>
<p className="mb-2 indent-0">b) 应支持电子会计档案元数据在档案移动、修改、处置后能够自动及时更 新,确保 关联 关系 的正</p>
<p className="mb-2 indent-0">确性。</p>
<p className="mb-2 indent-0">c) 应支持电子会计档案之间的关联关系在档 案移 动、修改、处置 后能 够自 动及 时更 新,确保 关联</p>
<p className="mb-2 indent-0">的正确性。</p>
<p className="mb-2 indent-0">d) 关联功能的操作应有审计跟踪日志,可追踪、审计和审查。</p>
<p className="mb-2 indent-0">e) 宜支持存在纸质会计档案时,可维护纸质会计档案与电子会计档案的关联关系。</p>
<p className="mb-2 indent-0">E.3 电子档案存储功能</p>
<p className="mb-2 indent-0">电子档案存储功能参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持电子会计档案的集中存储、分布式存储、集中+分布式存储,完全在线存储、部分在线存</p>
<p className="mb-2 indent-0">储+部分离线存储等存储方式;</p>
<p className="mb-2 indent-0">b) 应支持可按离线存储载体容量进行信息组织,将组织好的会计档案存至相 应的 离线 存储 载体</p>
<p className="mb-2 indent-0">上,信息组织要求参见《电子档案移交与接收办法》;</p>
<p className="mb-2 indent-0">c) 应支持文件存储与数据存储分离,不允许数据库中存储文件字节码。</p>
<p className="mb-2 indent-0">E.4 电子档案保管功能</p>
<p className="mb-2 indent-0">E.4.1 电子档案长期保存</p>
<p className="mb-2 indent-0">电子档案长期保存参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持电子档案 存储 格式 的转 换,将存 入系 统的 电子 档案 转换 为符 合长 期保 存要 求的 存储</p>
<p className="mb-2 indent-0">格式;</p>
<p className="mb-2 indent-0">b) 应支持对转为长期保存的电子会计档案及其元数据按照 DA/T</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">70 进行 真实 性、完整 性、安全</h3>
<p className="mb-2 indent-0">性、可用性检查;</p>
<p className="mb-2 indent-0">c) 应支持长期保存的电子会计档案有日志记录,可追踪、审计和审查;</p>
<p className="mb-2 indent-0">d) 系统 应支 持按 离线 存储 载体 容量 进行 信息 组织,将组 织好 的档 案存 至相 应的 离线 存储 载体</p>
<p className="mb-2 indent-0">上,信息组织要求参见《电子档案移交与接收办法》;</p>
<p className="mb-2 indent-0">202</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">e) 应支持采用迁移、仿真、封装、检测等方式保障数字档案信息的长期保管;能对非通用格式电子</p>
<p className="mb-2 indent-0">档案阅读所需要的原始软硬件在系统中进行标识;</p>
<p className="mb-2 indent-0">f) 应支持关键业务实体元数据记录到长期保存的电子会计档案元数据中。</p>
<p className="mb-2 indent-0">E.4.2 电子档案存储格式转换与信息组织</p>
<p className="mb-2 indent-0">电子档案存储格式转换与信息组织参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持电子会计资料、档案的格式转换功能,如批量格式转换、单个转换、人工定制转换或通过</p>
<p className="mb-2 indent-0">外部解决方案实现转换,并生 成符 合国 家、行业 相关 标准 的用 于利 用和 长期 保存 的电 子会 计</p>
<p className="mb-2 indent-0">档案;</p>
<p className="mb-2 indent-0">b) 应支持能够将格式转换结束的电子会计档案个别或批量存储至存储载体;</p>
<p className="mb-2 indent-0">c) 应支持对格式转换过程中发生的问题或错误,进行提示或发出警告,并记录未转换成功的相关</p>
<p className="mb-2 indent-0">信息;</p>
<p className="mb-2 indent-0">d) 应提供对格式转换前后的电子会计档案进行真实性、完整性、安全性、可用性的检测功能;</p>
<p className="mb-2 indent-0">e) 应支持在格式转换过程中添加可记录电子档案原始状态的信息。</p>
<p className="mb-2 indent-0">E.4.3 备份</p>
<p className="mb-2 indent-0">备份参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对电子会计档案的元数据、全文数据,进行完全、增量、差分备份等功能;</p>
<p className="mb-2 indent-0">b) 应支持系统中出现故障后恢复电子会计档案全文数据及其元数据;</p>
<p className="mb-2 indent-0">c) 应具备备份、恢复策略的配置和维护功能;</p>
<p className="mb-2 indent-0">d) 应对备份的数据、介质和信息,进行登记、检测与管理;</p>
<p className="mb-2 indent-0">e) 应记录备份、恢复的业务过程日志信息。</p>
<p className="mb-2 indent-0">E.4.4 定期鉴定</p>
<p className="mb-2 indent-0">定期鉴定参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对电子会计档案鉴定与处置的定义、配置 和实 施功 能,按照 电子 会计 档案 的处 置规 则,</p>
<p className="mb-2 indent-0">建立和配置鉴定与处置条件、策略和流程;</p>
<p className="mb-2 indent-0">b) 应支持会计档案保管期限到期自动提醒功能;</p>
<p className="mb-2 indent-0">c) 应支持根据鉴定意见调整电子会计档案保管期限、密级等功能;</p>
<p className="mb-2 indent-0">d) 系统应保存鉴定与处置的过程 信息,如记 录鉴 定情 况、责任 人员、意见 和时 间等 信息,可统 计</p>
<p className="mb-2 indent-0">查询;</p>
<p className="mb-2 indent-0">e) 鉴定行为应记录日志,关键操作信息应记入电子会计档案元数据中,并可跟踪审查。</p>
<p className="mb-2 indent-0">E.4.5 销毁管理</p>
<p className="mb-2 indent-0">销毁管理参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对需要销毁的会计档案进行销毁申请、审批等流程定制;</p>
<p className="mb-2 indent-0">b) 应支持从在线存储设备、异地容 灾备 份系 统中 彻底 删除 被销 毁的 电子 会计 档案,同时 应留 存</p>
<p className="mb-2 indent-0">已销毁电子会计档案的元数据信息,并在管理过程元数据、日志中自动记录鉴定销毁活动;</p>
<p className="mb-2 indent-0">c) 宜将销毁档案的相关记录单独建立数据库进 行安 全保 存,与当 前有 效的 电子 会计 档案 进行 分</p>
<p className="mb-2 indent-0">别管理;</p>
<p className="mb-2 indent-0">d) 应支持对销毁的电子会计档案编制销毁清册,记录文件名称、数量、销毁原因等信息。</p>
<p className="mb-2 indent-0">E.4.6 移交</p>
<p className="mb-2 indent-0">移交参照下列需求:</p>
<p className="mb-2 indent-0">302</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">a) 应支持电子会计档案到期移交提醒的功能;</p>
<p className="mb-2 indent-0">b) 应支持电子会计档案移交的在线申请、审批等流程设置;</p>
<p className="mb-2 indent-0">c) 应支持移交接收前对电子会计档案进行真实性、完整性、安全性、可用性检测;</p>
<p className="mb-2 indent-0">d) 应支持符合移交要求的电子会计档案移交完整会计档案信息包,移交 过程 中产 生的 关键 业务</p>
<p className="mb-2 indent-0">信息需记录到档案元数据中;</p>
<p className="mb-2 indent-0">e) 应支持档案移交接收后形成会计档案移交清册;</p>
<p className="mb-2 indent-0">f) 应支持移交过程中的业务操作记录日志,可跟踪审查。</p>
<p className="mb-2 indent-0">E.4.7 介质管理</p>
<p className="mb-2 indent-0">介质管理参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对存放电子会计档案存储介质的统一管理,系统 管理 员可 根据 介质 保管 的实 际需 求为</p>
<p className="mb-2 indent-0">会计档案设置相应的存储介质;</p>
<p className="mb-2 indent-0">b) 宜支持介质预警功能,当存储介质不稳定、存储空间不足等情况出现时,通知系统管理员。</p>
<p className="mb-2 indent-0">E.5 统计与报表</p>
<p className="mb-2 indent-0">统计与报表参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对电子会计档案数量与容量的统计功能,可按 照档 案的 会计 分类、文件 格式、时间 等维</p>
<p className="mb-2 indent-0">度进行统计;</p>
<p className="mb-2 indent-0">b) 应支持对一定时间期限内的电 子会 计档 案的 接收、整理、保存、鉴定、利用 等关 键业 务工 作情</p>
<p className="mb-2 indent-0">况进行统计的功能;</p>
<p className="mb-2 indent-0">c) 应支持统计结果的输出及打印;</p>
<p className="mb-2 indent-0">d) 宜支持内置常用电子档案工作统计报表模板,并能够基于模板根据输入条件生成统计结果;</p>
<p className="mb-2 indent-0">e) 宜支持报表制作工具,支持用户自定义统计报表。</p>
<p className="mb-2 indent-0">E.6 利用功能</p>
<p className="mb-2 indent-0">E.6.1 检索查询</p>
<p className="mb-2 indent-0">检索查询参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持按会计分类检索档案,具备模糊检索、组合检索、筛选检索、关联检索等多种检索方式;</p>
<p className="mb-2 indent-0">b) 应支持对会计档案元数据、全文数据检索的访问权限控制。</p>
<p className="mb-2 indent-0">E.6.2 浏览</p>
<p className="mb-2 indent-0">浏览参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对常见格式的电子会计档案信息进行浏览,如元数据浏览、全文浏览等;</p>
<p className="mb-2 indent-0">b) 应支持对电子会计档案浏览的访问权限控制;</p>
<p className="mb-2 indent-0">c) 应支持授权范围内的在线浏览、下载、打印等操作;</p>
<p className="mb-2 indent-0">d) 宜支持在电子会计档案浏览时增加防盗水印等保护措施。</p>
<p className="mb-2 indent-0">E.6.3 借阅</p>
<p className="mb-2 indent-0">借阅参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持对电子会计档案借阅申请、审批、催还、归还功能;</p>
<p className="mb-2 indent-0">b) 应支持电子会计档案在线借阅申请、审批和流程定制等操作,支持自动授权功能;</p>
<p className="mb-2 indent-0">402</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">c) 应支持借阅审批流程符合会计档案管理利用制度;</p>
<p className="mb-2 indent-0">d) 应支持授权范围内的在线阅读、下载、打印等操作;</p>
<p className="mb-2 indent-0">e) 应支持对下载的电子会计档案原文权限的使用控制,可包括但不限于:</p>
<p className="mb-2 indent-0">1) 全文在线浏览控制;</p>
<p className="mb-2 indent-0">2) 全文在线打印控制;</p>
<p className="mb-2 indent-0">3) 全文下载浏览次数、时间的控制;</p>
<p className="mb-2 indent-0">4) 全文防拷贝、防扩散、防篡改。</p>
<p className="mb-2 indent-0">E.7 系统管理功能</p>
<p className="mb-2 indent-0">E.7.1 日志管理</p>
<p className="mb-2 indent-0">日志管理参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持日志记载功能,记录用户操作信息、系统启动关闭信息、用户登录等行为和信息;</p>
<p className="mb-2 indent-0">b) 应支持对电子会计档案管理关键业务过程操作行为和系统非授权访问等 事项 进行 审计、跟踪</p>
<p className="mb-2 indent-0">的功能,记录发现的问题;</p>
<p className="mb-2 indent-0">c) 应支持日志自动生成的功能,并实施分类管理;系统日志应包括系统运行日志、用户操作日志、</p>
<p className="mb-2 indent-0">电子会计档案数据处理日志等类别;</p>
<p className="mb-2 indent-0">d) 应支持用户行为监控和预警工具,通过系统消息、邮件、短信等方式告知系统安全保密员;</p>
<p className="mb-2 indent-0">e) 宜支持日志的检索、查询功能,通过可视化的界面展示日志的检索结果。</p>
<p className="mb-2 indent-0">E.7.2 系统设置</p>
<p className="mb-2 indent-0">系统设置参照下列需求。</p>
<p className="mb-2 indent-0">a) 应支持对电子会计档案进行流程化管理,可根据不同 的电 子会 计档 案类 别的 管理 要求 设置 相</p>
<p className="mb-2 indent-0">应管理流程,可对流程进行跟踪和回溯。</p>
<p className="mb-2 indent-0">b) 应支持对电子会计档案元数据结构进行定义和维护的功能,规定电子会计 档案 分类 的等 级层</p>
<p className="mb-2 indent-0">次及关联关系,具体功能可包括但不限于:</p>
<p className="mb-2 indent-0">1) 使用系统提供的功能对分类体系进行逐级定义;</p>
<p className="mb-2 indent-0">2) 从外部接口文件中导入分类体系;</p>
<p className="mb-2 indent-0">3) 从外部系统中自动导入分类体系;</p>
<p className="mb-2 indent-0">4) 系统开始使用后,会计分类目录结构的修改、调整应在审批后 方可 进行,并采 用安 全可 靠</p>
<p className="mb-2 indent-0">的方法确保电子会计档案不被修改。</p>
<p className="mb-2 indent-0">c) 应支持代码表的设置与维护,如会计年度代码、密级代码、保管期限代码等信息的设置与维护;</p>
<p className="mb-2 indent-0">应支持元数据及其关联关系的设置维护,可以 定义 元数 据的 名称、类型、是否 为空、是否 唯一、</p>
<p className="mb-2 indent-0">字符串长度限制、缺省值、最大值、最小值、组合字段、关联关系等属性信息。</p>
<p className="mb-2 indent-0">d) 应支持“四性检测”的设置维护,可进行检测规则、检测元数据项目等设置。</p>
<p className="mb-2 indent-0">E.7.3 用户管理</p>
<p className="mb-2 indent-0">用户管理参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持用户信息的直接录入,或通过接口方式同步其他系统中的用户信息;</p>
<p className="mb-2 indent-0">b) 应支持系统管理员、系统安全保密员和系统安全审计员的三员分立的安全控制功能;</p>
<p className="mb-2 indent-0">c) 应支持用户信息的管理,对用户信息可以进行查看、新增、修改、删除、启用、禁用、分组、分类等</p>
<p className="mb-2 indent-0">功能操作,用户信息的删除、启用、禁用可以支持批量操作;</p>
<p className="mb-2 indent-0">d) 应支持用户密码强度管理,可以设置、调整用户密码强度策略,对于 多次 登录 验证 失败 的用 户</p>
<p className="mb-2 indent-0">502</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">账号信息,支持用户锁定处理;</p>
<p className="mb-2 indent-0">e) 宜具备用户身份安全认证服务或用户信息绑定固定IP 地址和 MAC 地址等功能,实现控制用</p>
<p className="mb-2 indent-0">户登录,保证信息安全。</p>
<p className="mb-2 indent-0">E.7.4 组织管理</p>
<p className="mb-2 indent-0">组织管理参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持组织机构信息的直接录入,或通过接口方式同步其他系统中的组织机构信息;</p>
<p className="mb-2 indent-0">b) 应支持组织机构的多级管理功能;</p>
<p className="mb-2 indent-0">c) 应支持组织机构信息的管理,对组织机构 信息 可以 进行 查看、新增、修改、删除 等功 能操 作,可</p>
<p className="mb-2 indent-0">实现用户与组织机构的映射。</p>
<p className="mb-2 indent-0">E.7.5 权限管理</p>
<p className="mb-2 indent-0">权限管理参照下列需求:</p>
<p className="mb-2 indent-0">a) 应支持电子会计档案权限管理功能,保证授权用户能够在其权限范围内进行合法操作;</p>
<p className="mb-2 indent-0">b) 应支持权限精细控制,如指定用户、角色、岗位、单位等授权档案记录的访问和使用权限;</p>
<p className="mb-2 indent-0">c) 应支持权限有效期的设置,到期后系统自动取消权限;</p>
<p className="mb-2 indent-0">d) 应支持根据职责和岗位的不同以功能和数据授权方式赋权。</p>
<p className="mb-2 indent-0">602</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 F</h3>
<div className="h-4" />
<p className="mb-2 indent-0">(资料性)</p>
<p className="mb-2 indent-0">电子会计档案保存用表(图)</p>
<p className="mb-2 indent-0">表 F.1给出了电子会计档案保存时所用的目录文件(电子会计档案登记表)格式,图 F.1给出了电</p>
<p className="mb-2 indent-0">子会计档案存储结构的示意图,图 F.2给出了电子会计凭证存储结构的示意图。</p>
<p className="mb-2 indent-0">表 F.1 目录文件(电子会计档案登记表)</p>
<p className="mb-2 indent-0">序号档号文件号题名形成日期保管期限电子文件名数量备注</p>
<p className="mb-2 indent-0">注:</p>
<div className="h-4" />
<p className="mb-2 indent-0">档号、保管期限在编号后填写。文件号根据电子会计资料的类别分别填写电子会计凭证号、电子 会计 账簿 号</p>
<p className="mb-2 indent-0">或电子财务会计报告号。电子会计凭 证的 题名 填写“摘要”;电子 会计 账簿 的题 名填 写“会计 期间 + 账簿 类</p>
<p className="mb-2 indent-0">别”;其他电子会计资料题名填写其实际题名。电子文件 名填 写电 子会 计档 案的 计算 机文 件名(含扩 展名)。</p>
<p className="mb-2 indent-0">数量填写电子会计档案包含电子文档的个数。</p>
<p className="mb-2 indent-0">图 F.1 电子会计档案存储结构示意图</p>
<p className="mb-2 indent-0">702</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<p className="mb-2 indent-0">图 F.2 电子会计凭证存储结构示意图</p>
<p className="mb-2 indent-0">802</p>
<div className="h-4" />
<p className="mb-2 indent-0">DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">94—2022</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">参考 文献</h3>
<p className="mb-2 indent-0">[1] DA/T</p>
<div className="h-4" />
<p className="mb-2 indent-0">46—2009 文书类电子文件元数据方案</p>
<p className="mb-2 indent-0">[2] 企业电子文件归档和电子档案管理指南(档办发〔2015〕4号)</p>
<p className="mb-2 indent-0">[3] 会计档案管理办法(中华人民共和国财政部国家档案局令第79号)</p>
<p className="mb-2 indent-0">[4] 关于规范电子会计凭证报销入账归档的通知(财会〔2020〕6号)</p>
<p className="mb-2 indent-0">[5] 电子档案移交与接收办法(档发〔2012〕7号)</p>
<p className="mb-2 indent-0">902</p>
      </div>
      
      <div className="bg-amber-500/10 border p-8 rounded-3xl border-amber-500/20 mt-16">
          <h3 className="text-xl font-bold text-white mb-4">DigiVoucher 100% 合规落地</h3>
          <p className="text-slate-400 mb-6 leading-relaxed">
              DigiVoucher 系统设计严格遵循 DA/T 94—2022《电子会计档案管理规范》 要求。我们确保您的电子档案管理流程在技术层面上完全对标国标与行标，
              实现全生命周期的合规管控。
          </p>
      </div>
    </RegulationLayout>
  );
};

export default DAT94Spec;
