// Input: 无
// Output: DA/T 104—2024《企业资源计划（ERP）系统电子文件归档和电子档案管理规范》 全量高排版版
// Pos: /Users/user/nexusarchive/src/pages/product-website/regulations/ERPArchiveSpec.tsx

import React from 'react';
import { RegulationLayout } from './RegulationLayout';

export const ERPArchiveSpec: React.FC = () => {
  return (
    <RegulationLayout 
        title="DA/T 104—2024《企业资源计划（ERP）系统电子文件归档和电子档案管理规范》"
        category="行业标准"
        source="国家标准/行业规范"
        effectiveDate="2024-04-01"
    >
      <div className="regulation-content font-serif leading-relaxed text-slate-300 max-w-none">
<p className="mb-2 indent-0">ICS01.140.20</p>
<p className="mb-2 indent-0">CCS A 14</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">中华 人民 共和 国档 案行 业标 准</h3>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统电子文件归档和电子档案</h3>
<p className="mb-2 indent-0">管理规范</p>
<p className="mb-2 indent-0">Specificationforelectronicdocumentsarchivingandelectronicrecords</p>
<p className="mb-2 indent-0">managementofenterpriseresourceplanningsystem</p>
<p className="mb-2 indent-0">2024-08-16发布 2025-02-01实施</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">国家档案局发 布</h3>
<div className="h-4" />
<p className="mb-2 indent-0">目次</p>
<p className="mb-2 indent-0">前言 Ⅲ…………………………………………………………………………………………………………</p>
<p className="mb-2 indent-0">引言 Ⅳ…………………………………………………………………………………………………………</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">1 范围 1………………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 规范性引用文件 1…………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">3 术语和定义 1………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4 总体要求 1…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 职责 2………………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.1 档案部门 2……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.2 业务部门 2……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.3 信息化部门 2…………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.4 保密部门 2……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 收集 2………………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.1 收集范围 2……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.2 元数据收集 2…………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.3 收集时间 3……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.4 归档格式 3……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.5 收集方式 3……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.6 接收 3…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 整理 3………………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.1 组件 3…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.2 保管期限划分 4………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.3 分类 4…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.4 组卷 4…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.5 编号 5…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.6 编目 5…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.7 归档 5…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 存储 5………………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.1 在线存储 5……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.2 离线存储 6……………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 保管 6………………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 统计与利用 7………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.1 统计 7…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.2 利用 7…………………………………………………………………………………………………</h3>
<p className="mb-2 indent-0">Ⅰ</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11 鉴定与处置 7………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12 系统建设 7…………………………………………………………………………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 A (资料性) ERP 系统电子文件归档范围与电子档案保管期限表 8………………………………</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 B (资料性) ERP 系统与电子档案管理信息系统接口方案 14………………………………………</h3>
<p className="mb-2 indent-0">参考文献 17……………………………………………………………………………………………………</p>
<p className="mb-2 indent-0">Ⅱ</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">前言</p>
<p className="mb-2 indent-0">本文件按照 GB/T1.1—2020《标准化工作导则第1部分:标准化文件的结构和起草规则》的规定</p>
<p className="mb-2 indent-0">起草。</p>
<p className="mb-2 indent-0">请注意本文件的某些内容可能涉及专利。本文件的发布机构不承担识别专利的责任。</p>
<p className="mb-2 indent-0">本文件由国家档案局提出并归口。</p>
<p className="mb-2 indent-0">本文件起草单位:中国宝武马钢集团、国家 档案 局经 济科 技档 案业 务指 导司、本钢 集团 有限 公司、</p>
<p className="mb-2 indent-0">成都飞机工业(集团)有限责任公司。</p>
<p className="mb-2 indent-0">本文件主要起草人:李忱、蔡盈芳、查满林、王桃、肖妍、杨孝义、赵伟、车昊珈、李璘。</p>
<p className="mb-2 indent-0">Ⅲ</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">引言</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统是对企业物流、资金 流、信息 流进 行全 面一 体化 管理 的管 理信 息系 统,一般 包括 采购 管</h3>
<p className="mb-2 indent-0">理、物料管理、生产计划管理、质量管理、销售管理、设备管理、项目管理、会计管理、人力资源管理等子系</p>
<p className="mb-2 indent-0">统。本文件主要规范采购、物料、生产计划、质量、销售、设备、项目管理等子系统形成的电子文件归档和</p>
<p className="mb-2 indent-0">电子档案管理,会计管理子系统电子文件归档和电子档案管理参照 DA/T94,人力资源管理子系统功</p>
<p className="mb-2 indent-0">能正逐步被独立部署的人力资源管理系统所替代,两个子系统不纳入本文件范围。</p>
<p className="mb-2 indent-0">Ⅳ</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">ERP系统电子文件归档和电子档案</p>
<p className="mb-2 indent-0">管理规范</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">1 范围</h3>
<p className="mb-2 indent-0">本文件规定了企业资源计划(以下简称 ERP)系统(包括采购、物料、生产计划、质量、销售、设备、项</p>
<p className="mb-2 indent-0">目管理等子系统)的电子文件收集、整理、归档和电子档案保管、存储、统计、利用、鉴定与处置等要求。</p>
<p className="mb-2 indent-0">本文件适用于 ERP 系统电子文件归档和电子档案管理工作。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 规范性引用文件</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">下列文件中的内容通过文中的规范性引用而构成本文件必不 可少 的条 款。其中,注日 期的 引用 文</h3>
<p className="mb-2 indent-0">件,仅该日期对应的版本适用于本文件;不注日期的引用文件,其最新版本(包括 所有 的修 改单)适用 于</p>
<p className="mb-2 indent-0">本文件。</p>
<p className="mb-2 indent-0">GB/T29194 电子文件管理系统通用功能要求</p>
<p className="mb-2 indent-0">GB/T39784 电子档案管理系统通用功能要求</p>
<p className="mb-2 indent-0">DA/T13 档号编制规则</p>
<p className="mb-2 indent-0">DA/T38 档案级可录类光盘 CD-R、DVD-R、DVD+R 技术要求和应用规范</p>
<p className="mb-2 indent-0">DA/T70 文书类电子档案检测一般要求</p>
<p className="mb-2 indent-0">DA/T74 电子档案存储用可录类蓝光光盘(BD-R)技术要求和应用规范</p>
<p className="mb-2 indent-0">DA/T75 档案数据硬磁盘离线存储管理规范</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">3 术语和定义</h3>
<p className="mb-2 indent-0">下列术语和定义适用于本文件。</p>
<p className="mb-2 indent-0">3.1</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统 enterpriseresourceplanningsystem</h3>
<p className="mb-2 indent-0">对企业物流、资金流、信息流进行全面一体化管理的管理信息系统。</p>
<p className="mb-2 indent-0">注:一般包括采购管理、物料管理、生产计划管理、质量管理、销售管理、设备管理、项目管理、会计管理、人力资源管</p>
<p className="mb-2 indent-0">理等子系统。</p>
<p className="mb-2 indent-0">3.2</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统电子文件 enterpriseresourceplanningsystemelectronicdocument</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统(3.1)形成、传输和存储的各种数字格式信息记录。</h3>
<p className="mb-2 indent-0">3.3</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统电子档案 enterpriseresourceplanningsystemelectronicarchives</h3>
<p className="mb-2 indent-0">具有凭证、参考和保存价值并归档保存的 ERP 系统电子文件(3.2)。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4 总体要求</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.1 使用 ERP 系统的单位应建 立和 完善 ERP 系统 电子 文件 的收 集、整理、归档 和电 子档 案保 管、存</h3>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">储、统计、利用、鉴定、处置等管理制度,采取可靠的技术和措施,确保 ERP 系统电子档案来源可靠、程序</p>
<p className="mb-2 indent-0">规范、要素合规。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.2 应将 ERP 系统电子文件归档和电子 档案 管理 工作 纳入 档案、业务、信息 化、保密 等相 关部 门和 人</h3>
<p className="mb-2 indent-0">员岗位职责,明确分工、相互协作。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.3 ERP 系统、电子档案管理信息系统及其运行网络的安全防范,应符合国家网 络安 全等 级保 护有 关</h3>
<p className="mb-2 indent-0">的要求。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.4 符合国家有关规定形成(或接收)并按 照本 文件 管理 的 ERP 系统 电子 文件,可仅 以电 子形 式归 档</h3>
<p className="mb-2 indent-0">保存。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 职责</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.1 档案部门</h3>
<p className="mb-2 indent-0">5.1.1 会同业务部门确定 ERP 系统电子文件的归档范围和电子档案保管期限。</p>
<p className="mb-2 indent-0">5.1.2 参与 ERP 系统建设,提出 ERP 系统电子文件归档功能、归档方式、归档格式、归档时间和“四性”</p>
<p className="mb-2 indent-0">(真实性、完整性、可用性、安全性)检测等要求。</p>
<p className="mb-2 indent-0">5.1.3 负责 ERP 系统电子档案的保管、存储、统计、利用、鉴定与处置,并对 ERP 系统 电子 文件 归档 工</p>
<p className="mb-2 indent-0">作进行指导和监督。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.2 业务部门</h3>
<p className="mb-2 indent-0">5.2.1 协助档案部门确定 ERP 系统电子文件的归档范围与电子档案保管期限。</p>
<p className="mb-2 indent-0">5.2.2 负责 ERP 系统电子文件收集、整理、移交归档工作。</p>
<p className="mb-2 indent-0">5.2.3 配合档案部门开展 ERP 系统电子档案鉴定工作。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.3 信息化部门</h3>
<p className="mb-2 indent-0">5.3.1 负责将 ERP 系统 电子 文件 归档 功能 建设 和电 子档 案管 理信 息系 统建 设列 入企 业信 息化 规</p>
<p className="mb-2 indent-0">划,并组织实施。</p>
<p className="mb-2 indent-0">5.3.2 负责为 ERP 系统电子文件归档功能和电子档案管理信息系统提供开发、运行维护等技术支持。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.4 保密部门</h3>
<p className="mb-2 indent-0">负责 ERP 系统电子文件归档和电子档案管理过程中相关保密工作的监督与检查。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 收集</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.1 收集范围</h3>
<p className="mb-2 indent-0">6.1.1 根据企业实际情况确定 ERP 系统电子文件归档范围(见附录 A),并按归档范围进行收集。</p>
<p className="mb-2 indent-0">6.1.2 ERP 系统电子文件及其组件应齐全、完整,内容信息与其形成时保持一致。</p>
<p className="mb-2 indent-0">6.1.3 以专有格式存储的电 子文 件不 能转 换为 通用 格式 时,应同 时收 集专 用软 件、技术 资料、操作 手</p>
<p className="mb-2 indent-0">册等。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.2 元数据收集</h3>
<p className="mb-2 indent-0">6.2.1 ERP 系统电子文件收集时应完整捕获元数据,元数据项的设置见 DA/T46,企业可根据 情况 自</p>
<p className="mb-2 indent-0">行扩展元数据。</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">6.2.2 元数据的捕获方式和捕获节点应在 ERP 系统和电子档案管理信息系统设计与开发过程中 进行</p>
<p className="mb-2 indent-0">规划和实现。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.3 收集时间</h3>
<p className="mb-2 indent-0">业务单据和报表办结后1个月内完成收集,其他电子文件收集时间不应晚于次年6月30日。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.4 归档格式</h3>
<p className="mb-2 indent-0">6.4.1 ERP 系统电子文件应形成相应独立格式的电子文件进行归档。</p>
<p className="mb-2 indent-0">6.4.2 ERP 系统归档电子文件的格式应具备开放、不绑定软硬件、显示一致性、可转换、易于利用性,以</p>
<p className="mb-2 indent-0">通用格式收集、归档或转换成通用格式归档,归档格式要求如下:</p>
<p className="mb-2 indent-0">a) 结构化数据可转换为符合归档要求的版式文件,或以 XML、XLS、DBF 等格 式的 文件 归档,为</p>
<p className="mb-2 indent-0">方便解析和统计,以版式文件归档时可同步归档 XML 文件;</p>
<p className="mb-2 indent-0">b) 二维图样文件以原始 格式 和 ODF/A 或 PDF/A 格式 同时 归档,三维 数模 文件 以原 始格 式和</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">STEP 及轻量化可视化格式同时归档。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.5 收集方式</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统生成归档信息包,通过接口自动收集,接口方案见附录 B。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.6 接收</h3>
<p className="mb-2 indent-0">6.6.1 接收时应对归档信息包进行“四性”检测,检测内容和方案按照 DA/T70相关规定执行。</p>
<p className="mb-2 indent-0">6.6.2 检测不合格 的归 档信 息包 应拒 收,并向 ERP 系统 发送 拒收 原因,业务 部门 核实 修正 后重 新</p>
<p className="mb-2 indent-0">推送。</p>
<p className="mb-2 indent-0">6.6.3 对通过检测的归档信息包进行解析,将元数据、电子文件、各类关联关系按照约定规则写入电子</p>
<p className="mb-2 indent-0">档案管理信息系统。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 整理</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.1 组件</h3>
<p className="mb-2 indent-0">7.1.1 应遵循文件材料形成规律进行组件,参照如下规则:</p>
<p className="mb-2 indent-0">a) 凭证及附件组成一件;</p>
<p className="mb-2 indent-0">b) 采购询价单、报价单组成一件;</p>
<p className="mb-2 indent-0">c) 需审核的业务单据与审核单组成一件;</p>
<p className="mb-2 indent-0">d) 合同及附件组成一件;</p>
<p className="mb-2 indent-0">e) 设备检(维)修相关业务单据按次组件;</p>
<p className="mb-2 indent-0">f) 固定资产卡片按固定资产编号组件,同一编号的固定资产卡片组成一件;</p>
<p className="mb-2 indent-0">g) 项目范围的定义文件和变更文件组成一件。</p>
<p className="mb-2 indent-0">7.1.2 件内文件一般按照业务单据在前、关联单据在后的顺序排列。凭证在前,附件在后;采购询价单</p>
<p className="mb-2 indent-0">在前,报价单在后;审核单在前,需审核 的业 务单 据在 后;合同 在前,附件 在后;项目 范围 的定 义文 件在</p>
<p className="mb-2 indent-0">前,变更文件在后;关联多种业务单据的,按照业务流程先后排序。</p>
<p className="mb-2 indent-0">7.1.3 文件题名可按“责任者 + 文件编号(或日期)+ 业务子系统 + 业务单据(或报表)名称”的规 则自</p>
<p className="mb-2 indent-0">动编制(见示例)。</p>
<p className="mb-2 indent-0">示例:××公司0000575771生产计划订单。</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.2 保管期限划分</h3>
<p className="mb-2 indent-0">7.2.1 ERP 系统电子文 件归 档时 应划 定保 管期 限,保管 期限 分为 永久 和定 期,定期 一般 为 30 年和</p>
<p className="mb-2 indent-0">10年,具体见附录 A。</p>
<p className="mb-2 indent-0">7.2.2 电子文件名称与附录 A 不一致或未列出的,参照相关门类档案管理规定划分保管期限。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.3 分类</h3>
<p className="mb-2 indent-0">7.3.1 分类规则</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统电子文件可独立形成 ERP 系统 电子 档案 类集 中管 理,也可 根据 其内 容归 入相 应档 案门</h3>
<p className="mb-2 indent-0">类管理。</p>
<p className="mb-2 indent-0">7.3.2 集中管理</p>
<p className="mb-2 indent-0">7.3.2.1 分类方法</p>
<p className="mb-2 indent-0">电子文件可按业务子系统、文件类型、年度等实施多级分类。以制造业为例,参照如下规则。</p>
<p className="mb-2 indent-0">a) 按业务子系统分类,即按照产生 ERP 系统电子文件的业务子系统分类(见表1)。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">表1 按业务子系统分类的电子文件分类示例</h3>
<p className="mb-2 indent-0">子系统名称业务子系统代号</p>
<p className="mb-2 indent-0">采购管理子系统 01</p>
<p className="mb-2 indent-0">物料管理子系统 02</p>
<p className="mb-2 indent-0">生产计划管理子系统 03</p>
<p className="mb-2 indent-0">质量管理子系统 04</p>
<p className="mb-2 indent-0">销售管理子系统 05</p>
<p className="mb-2 indent-0">设备管理子系统 06</p>
<p className="mb-2 indent-0">项目管理子系统 07</p>
<p className="mb-2 indent-0">其他 08</p>
<p className="mb-2 indent-0">b) 按年度分类,即按照 ERP 系统电子文件的形成年度分类。</p>
<p className="mb-2 indent-0">c) 按文件类型分类,即按照 ERP 系统电子文件反映的文件类型分类(见表2)。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">表2 按文件类型分类的电子文件分类示例</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">名称 文件类型代号</h3>
<p className="mb-2 indent-0">业务单据 01</p>
<p className="mb-2 indent-0">业务报表 02</p>
<p className="mb-2 indent-0">其他 03</p>
<p className="mb-2 indent-0">7.3.2.2 分类方案</p>
<p className="mb-2 indent-0">集中管理可按照以下方法进行分类:</p>
<p className="mb-2 indent-0">a) 业务子系统(或文件类型)—年度分类法;</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">b) 年度—业务子系统(或文件类型)分类法;</p>
<p className="mb-2 indent-0">c) 业务子系统—文件类型—年度分类法;</p>
<p className="mb-2 indent-0">d) 年度—业务子系统—文件类型分类法。</p>
<p className="mb-2 indent-0">7.3.3 归类管理</p>
<p className="mb-2 indent-0">对 ERP 系统电子文件实行归类管理的,按照相应门类分类方法进行分类。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.4 组卷</h3>
<p className="mb-2 indent-0">7.4.1 实行集中管理的宜以卷为单位管理,归入相应门类的可按照相应门类的管理方法选择以件或卷</p>
<p className="mb-2 indent-0">为单位管理。</p>
<p className="mb-2 indent-0">7.4.2 实行集中管理的 ERP 系统电子文件宜按时间组卷,规则参照如下:</p>
<p className="mb-2 indent-0">a) 业务单据一般按月进行组卷;</p>
<p className="mb-2 indent-0">b) 业务报表可按业务子系统分别按月、季、半年、年组卷;</p>
<p className="mb-2 indent-0">c) 其他可按业务子系统结合年度组卷。</p>
<p className="mb-2 indent-0">7.4.3 归入相应门 类管 理的 电子 文件 应与 其所 属门 类的 其他 电子 文件 一并 整理。 以卷 为保 管单 位</p>
<p className="mb-2 indent-0">的,组卷规则参照7.4.2,结合相应门类的电子文件整理要求进行。</p>
<p className="mb-2 indent-0">7.4.4 卷内文件 一般 按照 形成 时间 顺序 排列,订单、合同、凭证 等有 编号 的电 子文 件按 照编 号顺 序</p>
<p className="mb-2 indent-0">排列。</p>
<p className="mb-2 indent-0">7.4.5 案卷按分类进行排序,同一子类按照形成时间顺序排列。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.5 编号</h3>
<p className="mb-2 indent-0">7.5.1 按照卷内文件排列顺序编制卷内序号,不必编制页号。</p>
<p className="mb-2 indent-0">7.5.2 按照 DA/T13 的相关规定编制档号,档号格式为“[全宗号]-分类号-案卷号(或件号)”,中间用</p>
<p className="mb-2 indent-0">“-”隔开。分类号由分类方案给定,案卷号根据案卷排序规则自动编制,案卷号和件号为流水 号,由4位</p>
<p className="mb-2 indent-0">阿拉伯数字标识,不足4位的,前面用“0”补足。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.6 编目</h3>
<p className="mb-2 indent-0">7.6.1 应自动生成目录,包括案卷目录、卷内文件目录、归档文件目录,并按规则自动建立案卷、文件之</p>
<p className="mb-2 indent-0">间的关联关系。</p>
<p className="mb-2 indent-0">7.6.2 题名宜简明扼要,准确反映案卷或文件的内容。案卷以月度为周期组卷的,题名可按“责任者+</p>
<p className="mb-2 indent-0">年度+月度+业务子系统+业务单据(或报表)名称”的规则自动编制(见示例)。</p>
<p className="mb-2 indent-0">示例:××公司2021年6月生产计划订单。</p>
<p className="mb-2 indent-0">7.6.3 保管期限按卷内文件的最长保管期限填写。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.7 归档</h3>
<p className="mb-2 indent-0">7.7.1 对整理阶段划 定的 保管 期限、分类 结果 及排 序等 内容 进行 审核 和确 认,修正 不合 理或 不准 确</p>
<p className="mb-2 indent-0">的,并及时完成入库确认。</p>
<p className="mb-2 indent-0">7.7.2 按批次或归档年度形成电子文件归档登记表(见 GB/T18894—2016附录 A 的表 A.1)。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 存储</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.1 在线存储</h3>
<p className="mb-2 indent-0">8.1.1 应在电子档案管理信息系统设计开发时进行在线存储方式规划,并配备相应的软硬件设备。</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">8.1.2 在线存储方式应能适应大容 量电 子档 案存 储需 要,随着 电子 档案 存储 容量 增加,不影 响电 子档</p>
<p className="mb-2 indent-0">案管理信息系统访问、运行性能。</p>
<p className="mb-2 indent-0">8.1.3 在线存储容量应至少满足3年增量需求,避免电子文件的归档因存储容量不足而中断。</p>
<p className="mb-2 indent-0">8.1.4 电子档案管理信息系统应依据分类规则逐级建立文件夹,分门别类、集中有序地存储电子档案。</p>
<p className="mb-2 indent-0">8.1.5 电子档案管理信息系统应在元数据中自动记录电子档案在线存储路径,方便在线查阅、下载。</p>
<p className="mb-2 indent-0">8.1.6 宜每天实施增量备份,定期实施全量备份,有条件的企业可实施双机热备或异地应用级灾备。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.2 离线存储</h3>
<p className="mb-2 indent-0">8.2.1 应以件(含元数据)为存储单元离线存储 ERP 系统电子档案,存储结构及其说明见图1。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">图1 电子档案离线存储载体存储结构示例</h3>
<p className="mb-2 indent-0">8.2.2 电子档案离线存储可按年度 实施,离线 存储 介质 应至 少制 作一 套,根据 异质、异地 备份 要求,可</p>
<p className="mb-2 indent-0">制作第二套、第三套,并在装具上标识套别。</p>
<p className="mb-2 indent-0">8.2.3 不同套别的存储载体应分开保存,有条件的企业应将1套置于相距300km 以上,不属同一江河</p>
<p className="mb-2 indent-0">流域、同一地震带的地点保存。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 保管</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.1 应采取科学措施对存储载体进行管控,避免存储载体损坏,并防止未经授权的访问。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.2 电子档案管理信息系统应能跟踪到保管期间对电子档案的相关操作,并在日志中进行记录。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.3 因技术更新、介质检测不合格等原因需 要更 换离 线存 储介 质时,应实 施电 子档 案或 元数 据离 线存</h3>
<p className="mb-2 indent-0">储介质的迁移。离线存储载体管理按照 DA/T38、DA/T74、DA/T75的要求进行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.4 应每年对 ERP 系统电子档案的可读性进行评估,形成评估报告;如存在因系统软硬件或其他技术</h3>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">升级、更新导致 ERP 系统电子档案不可读取的风险,应对 ERP 系统电子档案进行迁移。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.5 ERP 系统 电子 档案 迁移 前应 进行 迁移 可行 性评 估,包括 目标 载体、系统、格式 的可 持续 性、安全</h3>
<p className="mb-2 indent-0">性、经济性评估,并保证迁移过程中 ERP 系统电子 档案 真实、完整,过程 可控,防止 迁移 过程 中 ERP 系</p>
<p className="mb-2 indent-0">统电子档案信息丢失或被非法篡改。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 统计与利用</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.1 统计</h3>
<p className="mb-2 indent-0">应按照全国档案事业统计调查制度及本单位实际需要,对 ERP 系统电子档案进行统计。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.2 利用</h3>
<p className="mb-2 indent-0">10.2.1 档案部门应会同业务部门制 定详 细的 电子 档案 利用 权限 规定,利用 权限 应在 电子 档案 管理 信</p>
<p className="mb-2 indent-0">息系统中实现。超权限利用时应进行审批,并保证利用过程中电子档案不被非法篡改。</p>
<p className="mb-2 indent-0">10.2.2 电子档案可根据授权通过电 子档 案管 理信 息系 统在 线或 离线 提供 利用,并通 过日 志或 其他 方</p>
<p className="mb-2 indent-0">式记录利用过程,记录信息包括利用者、利用方式、利用目的、档号、文件题名、利用时间等。</p>
<p className="mb-2 indent-0">10.2.3 可实现具有 ERP 系统数据特点的业务单据链式检索方式,具体方式如下:</p>
<p className="mb-2 indent-0">a) 采购业务链检索:订购合同→验收抵库单→业务报支单→付款申请单→记账凭证(应付);</p>
<p className="mb-2 indent-0">b) 销售业务链检索:销售订单→发货通知单→装车作 业单 → 质保 书 → 质量 鉴定 书 → 异议 处理 通</p>
<p className="mb-2 indent-0">知单→异议协议书→销账→结算单→记账凭证(应收)。</p>
<p className="mb-2 indent-0">10.2.4 应实现符合 ERP 系统电子档案特点的组合检索,参照如下方式:</p>
<p className="mb-2 indent-0">a) 设备分层检索:公司—厂矿—生产线—区域—设备;</p>
<p className="mb-2 indent-0">b) 工程项目检索:公司—立项年度—项目类型—项目—项目投资控制分解结构;</p>
<p className="mb-2 indent-0">c) 报表检索:对归档的 ERP 报表,按照 不同 业务 子系 统划 分成 工程 系统 报表、物料 系统 报表、</p>
<p className="mb-2 indent-0">原料系统报表、质量系统报表、生产系统报表、销售系统报表、设备系统报表等,分别查询检索。</p>
<p className="mb-2 indent-0">10.2.5 检索结果呈现应包括必要的元数据、电子档案全文和关联关系。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11 鉴定与处置</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11.1 应根据业务规则组织开展到期电子档案鉴定工作。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11.2 对经鉴定后确无保存价值的电子档案 进行 销毁,销毁 时应 先登 记、编制 清册,并按 有关 规定 履行</h3>
<p className="mb-2 indent-0">审批手续后,再将电子档案进行物理删除,物理删除时应由业务部门、档案部门共同监督,销毁清单及记</p>
<p className="mb-2 indent-0">录打印存档。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">11.3 经鉴定,仍需继续保存的 ERP 系统电子档案,应重新划定保管期限,继续保存。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12 系统建设</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12.1 ERP 系统应与电子档案管理信息系统相衔接,具有电子文件归档接口,接口功能见附录 B。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">12.2 电子档案管理信息系统功能应符合 GB/T29194、GB/T39784的相关规定,并具 有接 口功 能,接</h3>
<p className="mb-2 indent-0">口功能见附录 B。</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 A</h3>
<p className="mb-2 indent-0">(资料性)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统电子文件归档范围与电子档案保管期限表</h3>
<p className="mb-2 indent-0">本附录列出 ERP 系统电子文件归档范围和电子档案保管期限表,表 A.1是采购管理子系统电子文</p>
<p className="mb-2 indent-0">件归档范围与电子档案保管期限表,表 A.2是物料管理子系统电子文件归档范围与电子档案保 管期 限</p>
<p className="mb-2 indent-0">表,表 A.3是生产计划管理子系统电子 文件 归档 范围 与电 子档 案保 管期 限表,表 A.4 是设 备管 理子 系</p>
<p className="mb-2 indent-0">统电子文件归档范围与电子档案保管期限表,表 A.5是质量管理子系统电子文件归档范围与电 子档 案</p>
<p className="mb-2 indent-0">保管期限表,表 A.6是销售管理子系统电子文件归档范围与电子档案保管期限表,A.7是项目管理子系</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">统电子文件归档范围与电 子档 案保 管期 限表,A.8 是主 数据 电子 文件 归档 范围 与电 子档 案保 管期 限</h3>
<p className="mb-2 indent-0">表,供企业制定 ERP 系统电子文件归档范围与电子档案保管期限表时参考。</p>
<p className="mb-2 indent-0">表 A.1 采购管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">14</p>
<p className="mb-2 indent-0">15</p>
<p className="mb-2 indent-0">16</p>
<p className="mb-2 indent-0">采购管理子系统</p>
<p className="mb-2 indent-0">采购需求文件 30年</p>
<p className="mb-2 indent-0">采购计划及审核相关文件 30年</p>
<p className="mb-2 indent-0">询价及报价文件 30年</p>
<p className="mb-2 indent-0">评标、中标文件 30年</p>
<p className="mb-2 indent-0">采购订单、订单更改单、重要的采购订单目录等相关文件 30年</p>
<p className="mb-2 indent-0">商务合同及变更文件 30年</p>
<p className="mb-2 indent-0">采购案审核文件 30年</p>
<p className="mb-2 indent-0">选厂审批文件 30年</p>
<p className="mb-2 indent-0">采购订单 30年</p>
<p className="mb-2 indent-0">采购订单更改单 30年</p>
<p className="mb-2 indent-0">到货、退货相关文件 30年</p>
<p className="mb-2 indent-0">验货相关文件 30年</p>
<p className="mb-2 indent-0">转港物资验配单 30年</p>
<p className="mb-2 indent-0">采购结算通知单、结算单等相关单据 30年</p>
<p className="mb-2 indent-0">供应商认证计划 30年</p>
<p className="mb-2 indent-0">记账凭证 30年</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.2 物料管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">物料管理子系统</p>
<p className="mb-2 indent-0">物料配套计划 30年</p>
<p className="mb-2 indent-0">物料凭证、收发货凭证等 30年</p>
<p className="mb-2 indent-0">出入库单、移库单等相关单据 30年</p>
<p className="mb-2 indent-0">退料、退货等单据 30年</p>
<p className="mb-2 indent-0">盘库相关表单 30年</p>
<p className="mb-2 indent-0">各类物资结算单及相关单据 30年</p>
<p className="mb-2 indent-0">成本中心发货单、冲销单等相关单据 30年</p>
<p className="mb-2 indent-0">产品收货单 30年</p>
<p className="mb-2 indent-0">主要产品产量清单 30年</p>
<p className="mb-2 indent-0">主要技术经济指标 30年</p>
<p className="mb-2 indent-0">物料收发存报表 30年</p>
<p className="mb-2 indent-0">工程设备备件支出单等 30年</p>
<p className="mb-2 indent-0">主要产品销售、库存清单永久</p>
<p className="mb-2 indent-0">表 A.3 生产计划管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">14</p>
<p className="mb-2 indent-0">生产计划管理</p>
<p className="mb-2 indent-0">子系统</p>
<p className="mb-2 indent-0">月度生产经营分析 30年</p>
<p className="mb-2 indent-0">生产日报 10年</p>
<p className="mb-2 indent-0">生产订单及审批相关文件 30年</p>
<p className="mb-2 indent-0">生产订单收料单、冲销单等相关单据 30年</p>
<p className="mb-2 indent-0">生产装置投料单、投料冲销单等相关单据 30年</p>
<p className="mb-2 indent-0">生产装置 30年</p>
<p className="mb-2 indent-0">收发存汇总表、明细表等 30年</p>
<p className="mb-2 indent-0">交易汇总表、明细表等 30年</p>
<p className="mb-2 indent-0">生产版本 30年</p>
<p className="mb-2 indent-0">生产订单汇总报表 30年</p>
<p className="mb-2 indent-0">定额工艺路线 30年</p>
<p className="mb-2 indent-0">季度生产计划 30年</p>
<p className="mb-2 indent-0">月生产计划 10年</p>
<p className="mb-2 indent-0">制造、装配大纲 30年</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.4 设备管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">14</p>
<p className="mb-2 indent-0">15</p>
<p className="mb-2 indent-0">16</p>
<p className="mb-2 indent-0">17</p>
<p className="mb-2 indent-0">18</p>
<p className="mb-2 indent-0">19</p>
<p className="mb-2 indent-0">20</p>
<p className="mb-2 indent-0">设备管理子系统</p>
<p className="mb-2 indent-0">设备外委采购订单 30年</p>
<p className="mb-2 indent-0">设备检、维修工单及相关单据 30年</p>
<p className="mb-2 indent-0">设备点检、维修基准清单 30年</p>
<p className="mb-2 indent-0">设备维修基准清单 30年</p>
<p className="mb-2 indent-0">停机统计表 30年</p>
<p className="mb-2 indent-0">设备通知单 30年</p>
<p className="mb-2 indent-0">固定资产卡片、设备转固交付清单等相关单据 30年</p>
<p className="mb-2 indent-0">预结算审批单 30年</p>
<p className="mb-2 indent-0">设备文档 30年</p>
<p className="mb-2 indent-0">检验计划 30年</p>
<p className="mb-2 indent-0">设备外委收货凭证 30年</p>
<p className="mb-2 indent-0">设备专业台账 30年</p>
<p className="mb-2 indent-0">设备合同台账 30年</p>
<p className="mb-2 indent-0">承包商考核 30年</p>
<p className="mb-2 indent-0">润滑油五定指示表 30年</p>
<p className="mb-2 indent-0">加换油记录 30年</p>
<p className="mb-2 indent-0">油品检验排程报表 30年</p>
<p className="mb-2 indent-0">代用油品审批 30年</p>
<p className="mb-2 indent-0">仪表自动化技术状况 30年</p>
<p className="mb-2 indent-0">特种设备延期监控记录 30年</p>
<p className="mb-2 indent-0">01</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.5 质量管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">14</p>
<p className="mb-2 indent-0">15</p>
<p className="mb-2 indent-0">16</p>
<p className="mb-2 indent-0">17</p>
<p className="mb-2 indent-0">18</p>
<p className="mb-2 indent-0">19</p>
<p className="mb-2 indent-0">20</p>
<p className="mb-2 indent-0">21</p>
<p className="mb-2 indent-0">22</p>
<p className="mb-2 indent-0">23</p>
<p className="mb-2 indent-0">24</p>
<p className="mb-2 indent-0">25</p>
<p className="mb-2 indent-0">26</p>
<p className="mb-2 indent-0">27</p>
<p className="mb-2 indent-0">28</p>
<p className="mb-2 indent-0">29</p>
<p className="mb-2 indent-0">30</p>
<p className="mb-2 indent-0">质量管理子系统</p>
<p className="mb-2 indent-0">数控加工试用程序 30年</p>
<p className="mb-2 indent-0">工艺模型 30年</p>
<p className="mb-2 indent-0">外购原燃料质量验证单 30年</p>
<p className="mb-2 indent-0">质保书(重要) 永久</p>
<p className="mb-2 indent-0">质保书(一般) 30年</p>
<p className="mb-2 indent-0">技术鉴定报告 30年</p>
<p className="mb-2 indent-0">异议处理通知单(重要) 永久</p>
<p className="mb-2 indent-0">异议处理通知单(一般) 30年</p>
<p className="mb-2 indent-0">异议协议书(重要) 永久</p>
<p className="mb-2 indent-0">异议协议书(一般) 30年</p>
<p className="mb-2 indent-0">放行报表、质量报表、外购料统计报表等报表 30年</p>
<p className="mb-2 indent-0">质量评审/状态检查申请报告 30年</p>
<p className="mb-2 indent-0">评审意见处理情况记录表 30年</p>
<p className="mb-2 indent-0">质量评审/状态检查报告 30年</p>
<p className="mb-2 indent-0">年度、季度等质量分析报告 30年</p>
<p className="mb-2 indent-0">质量问题续报单、报告单等 30年</p>
<p className="mb-2 indent-0">技术服务工作报告 30年</p>
<p className="mb-2 indent-0">技术服务保障工作情况报告 30年</p>
<p className="mb-2 indent-0">季(年)度外场质量趋势分析报告 30年</p>
<p className="mb-2 indent-0">总提交单 30年</p>
<p className="mb-2 indent-0">专题质量报告 30年</p>
<p className="mb-2 indent-0">不合格品通知单、审理单等相关单据 30年</p>
<p className="mb-2 indent-0">废品通知单 30年</p>
<p className="mb-2 indent-0">偏离申请单 30年</p>
<p className="mb-2 indent-0">保留单 30年</p>
<p className="mb-2 indent-0">预先处置单 30年</p>
<p className="mb-2 indent-0">材料合格证 30年</p>
<p className="mb-2 indent-0">成品合格证/履历本附页 30年</p>
<p className="mb-2 indent-0">理化试验、无损检测等委托单 30年</p>
<p className="mb-2 indent-0">检测提交单永久</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.6 销售管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">销售管理子系统</p>
<p className="mb-2 indent-0">销售订单 30年</p>
<p className="mb-2 indent-0">产品委托单 30年</p>
<p className="mb-2 indent-0">销售发货单 30年</p>
<p className="mb-2 indent-0">车辆调运单 30年</p>
<p className="mb-2 indent-0">装车作业单/装船作业单 30年</p>
<p className="mb-2 indent-0">产品出库重量凭证 30年</p>
<p className="mb-2 indent-0">产品出库重量凭证明细 30年</p>
<p className="mb-2 indent-0">销售提货单 30年</p>
<p className="mb-2 indent-0">销售退货单 30年</p>
<p className="mb-2 indent-0">销售结算明细表 30年</p>
<p className="mb-2 indent-0">销售结算汇总表 30年</p>
<p className="mb-2 indent-0">出货状况查询 30年</p>
<p className="mb-2 indent-0">订单发货/出货状态统计表 30年</p>
<p className="mb-2 indent-0">表 A.7 项目管理子系统电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">14</p>
<p className="mb-2 indent-0">15</p>
<p className="mb-2 indent-0">16</p>
<p className="mb-2 indent-0">17</p>
<p className="mb-2 indent-0">项目管理子系统</p>
<p className="mb-2 indent-0">项目工程合同永久</p>
<p className="mb-2 indent-0">工程研制/批量生产阶段质量计划永久</p>
<p className="mb-2 indent-0">项目零级/Ⅰ级网络计划永久</p>
<p className="mb-2 indent-0">项目年度计划 30年</p>
<p className="mb-2 indent-0">项目年度工作总结 30年</p>
<p className="mb-2 indent-0">试制工作总结 30年</p>
<p className="mb-2 indent-0">技术状态管理计划永久</p>
<p className="mb-2 indent-0">项目范围的定义文件 30年</p>
<p className="mb-2 indent-0">工作结构分解文件 30年</p>
<p className="mb-2 indent-0">研制分工文件 30年</p>
<p className="mb-2 indent-0">项目各级组织机构及其职责文件 30年</p>
<p className="mb-2 indent-0">成本估算和预算文件 30年</p>
<p className="mb-2 indent-0">项目风险的识别和处理文件 30年</p>
<p className="mb-2 indent-0">经营、项目、生产等指令永久</p>
<p className="mb-2 indent-0">项目进度、状态和问题报告文件 30年</p>
<p className="mb-2 indent-0">项目协调及协调会议文件 30年</p>
<p className="mb-2 indent-0">项目绩效的评估文件 30年</p>
<p className="mb-2 indent-0">21</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.7 项目管理子系统电子文件归档范围与电子档案保管期限表 (续)</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">18</p>
<p className="mb-2 indent-0">19</p>
<p className="mb-2 indent-0">20</p>
<p className="mb-2 indent-0">21</p>
<p className="mb-2 indent-0">22</p>
<p className="mb-2 indent-0">23</p>
<p className="mb-2 indent-0">24</p>
<p className="mb-2 indent-0">项目管理子系统</p>
<p className="mb-2 indent-0">项目范围变更文件永久</p>
<p className="mb-2 indent-0">项目计划、成本等变更文件 30年</p>
<p className="mb-2 indent-0">项目进度和状态预测报告文件 30年</p>
<p className="mb-2 indent-0">项目风险分析和评估文件 30年</p>
<p className="mb-2 indent-0">项目达标报告或因故中止的报告和批复文件永久</p>
<p className="mb-2 indent-0">工程资源请购 30年</p>
<p className="mb-2 indent-0">材料代用 30年</p>
<p className="mb-2 indent-0">表 A.8 主数据电子文件归档范围与电子档案保管期限表</p>
<p className="mb-2 indent-0">序号业务子系统名称保管期限备注</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">10</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">12</p>
<p className="mb-2 indent-0">13</p>
<p className="mb-2 indent-0">14</p>
<p className="mb-2 indent-0">15</p>
<p className="mb-2 indent-0">16</p>
<p className="mb-2 indent-0">17</p>
<p className="mb-2 indent-0">其他</p>
<p className="mb-2 indent-0">供应商数据 30年</p>
<p className="mb-2 indent-0">往来单位信息数据 30年</p>
<p className="mb-2 indent-0">基础代码信息数据 30年</p>
<p className="mb-2 indent-0">资产折旧信息 30年</p>
<p className="mb-2 indent-0">设备主数据 30年</p>
<p className="mb-2 indent-0">物料清单 30年</p>
<p className="mb-2 indent-0">工程项目主数据 30年</p>
<p className="mb-2 indent-0">资产分配信息 30年</p>
<p className="mb-2 indent-0">物料评估信息 30年</p>
<p className="mb-2 indent-0">物料仓储信息 30年</p>
<p className="mb-2 indent-0">客户信息数据库 30年</p>
<p className="mb-2 indent-0">客户信用信息 30年</p>
<p className="mb-2 indent-0">员工信息 30年</p>
<p className="mb-2 indent-0">内控审批流信息 30年</p>
<p className="mb-2 indent-0">成本内部订单 30年</p>
<p className="mb-2 indent-0">销售价格信息 30年</p>
<p className="mb-2 indent-0">各业务单据对应的目录数据 30年</p>
<p className="mb-2 indent-0">31</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 B</h3>
<p className="mb-2 indent-0">(资料性)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统与电子档案管理信息系统接口方案</h3>
<p className="mb-2 indent-0">B.1 接口方式</p>
<p className="mb-2 indent-0">B.1.1 WebService服务调用方式</p>
<p className="mb-2 indent-0">基于 WebService服务调用的归档接口示意见图 B.1。</p>
<p className="mb-2 indent-0">数据流说明:</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">① 服务请求:ERP 系统发起服务请求;</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">② 服务响应:电子档案管理信息系统接收服务请求,处理完成后返回结果并反馈至 ERP 系统。</h3>
<p className="mb-2 indent-0">图 B.1 WebService服务调用方式示意图</p>
<p className="mb-2 indent-0">B.1.2 中间库方式</p>
<p className="mb-2 indent-0">基于中间库的归档接口示意见图 B.2。</p>
<p className="mb-2 indent-0">数据流说明:</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">① 数据传输:ERP 系统将待归档电子文件传输至中间库;</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">② 数据提取:电子档案管理信息系统从中间库提取待归档电子文件;</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">③ 结果反馈:电子档案管理信息系统完成待归档电子文件提取处理后,将处理结果反馈至中间库;</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">④ 结果反馈:ERP 系统从中间库提取处理结果。</h3>
<p className="mb-2 indent-0">图 B.2 中间库方式示意图</p>
<p className="mb-2 indent-0">41</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">B.2 接口功能</p>
<p className="mb-2 indent-0">B.2.1 ERP 系统接口功能</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">ERP 系统接口功能如下:</h3>
<p className="mb-2 indent-0">a) 归档前将待归档 ERP 系统电子文件及其元数据按推荐格式封装成归档信息包;</p>
<p className="mb-2 indent-0">b) 能够嵌入分类方案和组卷方案,业务部门人员可根据电子文件内容选择生成类号和档号;</p>
<p className="mb-2 indent-0">c) 将归档信息包传输至指定位置(或者调用对方接口),传输过程中归档信息包信息不丢失、不被</p>
<p className="mb-2 indent-0">非法更改;</p>
<p className="mb-2 indent-0">d) 接收归档信息包接收方的反馈消息,包括归档成功或失败消息、失败故障代码等;</p>
<p className="mb-2 indent-0">e) 对归档成功的 ERP 系统电子文件进行已归档标记,以防止重复归档,并能取消标记,在人工干</p>
<p className="mb-2 indent-0">预下重新归档;</p>
<p className="mb-2 indent-0">f) 能够将升版、作废等电子文件更改信息传 递至 电子 档案 管理 信息 系统,确保 ERP 系统 电子 文</p>
<p className="mb-2 indent-0">件与电子档案管理信息系统电子档案状态保持一致;</p>
<p className="mb-2 indent-0">g) 记录 ERP 系统电子文件类型、归档时间、归档 状态,并能 够实 现按 照归 档 ERP 系统 电子 文件</p>
<p className="mb-2 indent-0">类型、归档时间、归档状态组合查询。</p>
<p className="mb-2 indent-0">h) 归档 接口 具备 通过 定制 作业 等方 式 ,实现 按照 传输 标准 、频次 、时间 自动 完成 传输 动作 的</p>
<p className="mb-2 indent-0">功能 。</p>
<p className="mb-2 indent-0">B.2.2 电子档案管理信息系统接口功能</p>
<p className="mb-2 indent-0">电子档案管理信息系统接口功能如下:</p>
<p className="mb-2 indent-0">a) 接收 ERP 系统传递来的数据包(或者从指定位置提取数据),并正确解析;</p>
<p className="mb-2 indent-0">b) 对 ERP 系统提交归档的电子文件及其元数据的“四性”进行 检测,检测 不合 格的 拒绝 接收,并</p>
<p className="mb-2 indent-0">反馈检测结果及不合格原因;</p>
<p className="mb-2 indent-0">c) 将解析后的 ERP 系统电子文件及其元数据存储在数据库、文件库,并保存过程日志;</p>
<p className="mb-2 indent-0">d) 能够正确解析升版、作废等电子文件变化信息,并按约定规则与对应电子档案关联;</p>
<p className="mb-2 indent-0">e) 向 ERP 系统发送电子文件归档成功或失败消息,以及故障代码;</p>
<p className="mb-2 indent-0">f) 在归档信息包接收、解析和数据存储等过程中,信息不丢失、不被非法更改;</p>
<p className="mb-2 indent-0">g) 记录归档 ERP 系统电子文件类型、归档时 间、归档 状态,并能 够按 照归 档 ERP 系统 电子 文件</p>
<p className="mb-2 indent-0">类型、归档时间、归档状态组合查询。</p>
<p className="mb-2 indent-0">B.2.3 接口建设管理</p>
<p className="mb-2 indent-0">接口建设管理如下:</p>
<p className="mb-2 indent-0">a) 归档接口与 ERP 系统同设计、同开发、同测 试和 同实 施,实施 时未 开发 归档 接口 的 ERP 系统</p>
<p className="mb-2 indent-0">及时通过二次开发实现;</p>
<p className="mb-2 indent-0">b) 为保证 ERP 系统电子文件真实性、完整性、可用性、安全性,将检测功能嵌入归档接口,减少人</p>
<p className="mb-2 indent-0">工干预;</p>
<p className="mb-2 indent-0">c) 归档接口开发时进行充分测试,并经专家评审,以确认功能达到设计目标要求;</p>
<p className="mb-2 indent-0">d) 归档接口投入运行后,安排专人对接口运行情况进行持续跟踪,发现问题及时处理;</p>
<p className="mb-2 indent-0">e) 对于现存 ERP 系统,联系 ERP 系统原开发商或组织自有力量进行接口开发;</p>
<p className="mb-2 indent-0">f) 对于新开发 ERP 系统,在开发初期将档案部门纳入实施团队,提出 ERP 系统电子文件归档功</p>
<p className="mb-2 indent-0">51</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<p className="mb-2 indent-0">能要求,并对归档功能进行测试确认;</p>
<p className="mb-2 indent-0">g) ERP 系统和电子档案管理信息系统更新充分论证对归档接口功能的影响,确保归档接口能够</p>
<p className="mb-2 indent-0">正常运行;</p>
<p className="mb-2 indent-0">h) 制定应急机制,在 ERP 系统和电子档案管理信息系统因升级、系统故障、病毒感染等原因影响</p>
<p className="mb-2 indent-0">接口功能时立即启动应急响应。</p>
<p className="mb-2 indent-0">61</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">参考 文献</h3>
<p className="mb-2 indent-0">[1] GB/T18894—2016 电子文件归档与电子档案管理规范</p>
<p className="mb-2 indent-0">[2] DA/T46 文书类电子文件元数据方案</p>
<p className="mb-2 indent-0">[3] DA/T92 电子档案单套管理一般要求</p>
<p className="mb-2 indent-0">[4] DA/T94 电子会计档案管理规范</p>
<p className="mb-2 indent-0">[5] DA/T97 电子档案证据效力维护规范</p>
<p className="mb-2 indent-0">71</p>
<p className="mb-2 indent-0">DA/T 104—2024</p>
      </div>
      
      <div className="bg-amber-500/10 border p-8 rounded-3xl border-amber-500/20 mt-16">
          <h3 className="text-xl font-bold text-white mb-4">DigiVoucher 100% 合规落地</h3>
          <p className="text-slate-400 mb-6 leading-relaxed">
              DigiVoucher 系统设计严格遵循 DA/T 104—2024《企业资源计划（ERP）系统电子文件归档和电子档案管理规范》 要求。我们确保您的电子档案管理流程在技术层面上完全对标国标与行标，
              实现全生命周期的合规管控。
          </p>
      </div>
    </RegulationLayout>
  );
};

export default ERPArchiveSpec;
