// Input: 无
// Output: GB/T 18894—2016《电子文件归档与电子档案管理规范》 全量高排版版
// Pos: /Users/user/nexusarchive/src/pages/product-website/regulations/GBT18894Spec.tsx

import React from 'react';
import { RegulationLayout } from './RegulationLayout';

export const GBT18894Spec: React.FC = () => {
  return (
    <RegulationLayout 
        title="GB/T 18894—2016《电子文件归档与电子档案管理规范》"
        category="国家标准"
        source="国家标准/行业规范"
        effectiveDate="2017-03-01"
    >
      <div className="regulation-content font-serif leading-relaxed text-slate-300 max-w-none">
<p className="mb-2 indent-0">ICS01.140.20</p>
<p className="mb-2 indent-0">A 14</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">中华 人民 共和 国国 家标 准</h3>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<p className="mb-2 indent-0">代替 GB/T18894—2002</p>
<p className="mb-2 indent-0">电子文件归档与电子档案管理规范</p>
<p className="mb-2 indent-0">Specificationonelectronicdocumentsarchivingand</p>
<p className="mb-2 indent-0">electronicrecordsmanagement</p>
<p className="mb-2 indent-0">2016-08-29发布 2017-03-01实施</p>
<p className="mb-2 indent-0">中华人民共和国国家质量监督检验检疫总局</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">中国 国家 标准 化管 理委 员会</h3>
<p className="mb-2 indent-0">发布</p>
<div className="h-4" />
<p className="mb-2 indent-0">前言</p>
<p className="mb-2 indent-0">本标准按照 GB/T1.1—2009给出的规则起草。</p>
<p className="mb-2 indent-0">本标准代替 GB/T18894—2002《电子文件归档与管理规范》。</p>
<p className="mb-2 indent-0">本标准与 GB/T18894—2002相比主要变化如下:</p>
<p className="mb-2 indent-0">———将标准名称更改为“电子文件归档与电子档案管理规范”,增加 了必 要的 规范 性引 用文 件和 术</p>
<p className="mb-2 indent-0">语或定义;</p>
<p className="mb-2 indent-0">———根据电子文件、电子档案管理要求,专设第5章对业务 系统、电子 档案 管理 系统 相关 功能 提出</p>
<p className="mb-2 indent-0">明确要求;</p>
<p className="mb-2 indent-0">———自第6章开始用5个章节分别描述电子文件、电子档案主要业务环节管理要求,包括电子文件</p>
<p className="mb-2 indent-0">归档范围、电子文件的收集与整理、电子文件归档与电子档案编目、电子档案的管理、电子档案</p>
<p className="mb-2 indent-0">的处置。</p>
<p className="mb-2 indent-0">本标准由国家档案局提出并归口。</p>
<p className="mb-2 indent-0">本标准起草单位:国家档案局。</p>
<p className="mb-2 indent-0">本标准主要起草人:毛海帆、王岚、丁德胜、侯佳、方昀、黄玉明、刘伟晏、蔡学美、马淑桂、张楠。</p>
<p className="mb-2 indent-0">本标准所代替标准的历次版本发布情况为:</p>
<p className="mb-2 indent-0">———GB/T18894—2002。</p>
<p className="mb-2 indent-0">Ⅰ</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">电子文件归档与电子档案管理规范</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">1 范围</h3>
<p className="mb-2 indent-0">本标准规定了在公务活动中产生的,具有保存价值的电子文件 的收 集、整理、归档 与电 子档 案的 编</p>
<p className="mb-2 indent-0">目、管理与处置的一般方法。</p>
<p className="mb-2 indent-0">本标准适用于机关、团体、企事业单位和其他组织在处理公务过程中产生的电子文件归档与电子档</p>
<p className="mb-2 indent-0">案管理,其他活动中产生的电子文件归档与电子档案管理可参照执行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">2 规范性引用文件</h3>
<p className="mb-2 indent-0">下列文件对于本文件的应用是必不可少的。凡是注日期的引用 文件,仅注 日期 的版 本适 用于 本文</p>
<p className="mb-2 indent-0">件。凡是不注日期的引用文件,其最新版本(包括所有的修改单)适用于本文件。</p>
<p className="mb-2 indent-0">GB/T2828.1—2012 计数抽样检验程序第1 部分:按接 收质 量限(AQL)检索 的逐 批检 验抽 样</p>
<p className="mb-2 indent-0">计划(ISO2859-1:1999,IDT)</p>
<p className="mb-2 indent-0">GB/T7156—2003 文献保密等级代码与标识</p>
<p className="mb-2 indent-0">GB/T9704—2012 党政机关公文格式</p>
<p className="mb-2 indent-0">GB/T11821—2002 照片档案整理规范</p>
<p className="mb-2 indent-0">GB/T11822—2008 科学技术档案案卷构成的一般要求</p>
<p className="mb-2 indent-0">GB/T12628—2008 硬磁盘驱动器通用规范</p>
<p className="mb-2 indent-0">GB/T17678—1999 CAD 电子文件光盘存储、归档与档案管理要求</p>
<p className="mb-2 indent-0">GB/T20988—2007 信息安全技术信息系统灾难恢复规范</p>
<p className="mb-2 indent-0">GB/T26163.1—2010 信息与文献文件管理过程文件元数据第 1 部分:原则 (ISO23081-1,</p>
<p className="mb-2 indent-0">IDT)</p>
<p className="mb-2 indent-0">GB/T29194—2012 电子文件管理系统通用功能要求</p>
<p className="mb-2 indent-0">DA/T13—1994 档号编制规则</p>
<p className="mb-2 indent-0">DA/T15—1995 磁性载体档案管理与保护规范</p>
<p className="mb-2 indent-0">DA/T18—1999 档案著录规则</p>
<p className="mb-2 indent-0">DA/T22 归档文件整理规则</p>
<p className="mb-2 indent-0">DA/T28—2002 国家重大建设项目文件归档要求与档案整理规范</p>
<p className="mb-2 indent-0">DA/T31 纸质档案数字化技术规范</p>
<p className="mb-2 indent-0">DA/T32—2005 公务电子邮件归档与管理规则</p>
<p className="mb-2 indent-0">DA/T38—2008 电子文件归档光盘技术要求和应用规范</p>
<p className="mb-2 indent-0">DA/T46—2009 文书类电子文件元数据方案</p>
<p className="mb-2 indent-0">DA/T47—2009 版式电子文件长期保存格式需求</p>
<p className="mb-2 indent-0">ISO13008:2012 信息 与文 献数 字档 案转 换和 迁移 过程 (Informationanddocumentation —</p>
<p className="mb-2 indent-0">Digitalrecordsconversionandmigrationprocess)</p>
<p className="mb-2 indent-0">ISO/TR13028:2010 信息与文献档案数字化实施指南(InformationanddocumentationImple-</p>
<p className="mb-2 indent-0">mentationguidelinesfordigitizationofrecords)</p>
<p className="mb-2 indent-0">ISO16175.2:2011 信息与文献电子办公环境中档案管理原则和功能要求第 2 部分:数字档</p>
<p className="mb-2 indent-0">1</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">案管理系统指南与功能要求(Principlesandfunctionalrequirementsforrecordsinelectronicofficeen-</p>
<p className="mb-2 indent-0">vironments — Part2:Guidelinesandfunctionalrequirementsfordigitalrecordsmanagementsystems)</p>
<p className="mb-2 indent-0">ISO16175.3:2010 信息与文献电子办公环境中档案管理原则和功能要求第 3 部分:业务系</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">统中档案管理指 南与 功能 要求 (Informationanddocumentation — Principlesandfunctionalrequire-</h3>
<p className="mb-2 indent-0">mentsforrecordsinelectronicofficeenvironments — Part3:Guidelinesandfunctionalrequirements</p>
<p className="mb-2 indent-0">forrecordsinbusinesssystems)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">3 术语和定义</h3>
<p className="mb-2 indent-0">下列术语和定义适用于本文件。</p>
<p className="mb-2 indent-0">3.1</p>
<p className="mb-2 indent-0">电子文件 electronicdocument</p>
<p className="mb-2 indent-0">国家机构、社会组织或个人在履行其法定职责或处理事务过程 中,通过 计算 机等 电子 设备 形成、办</p>
<p className="mb-2 indent-0">理、传输和存储的数字格式的各种信息记录。电子文件由内容、结构、背景组成。</p>
<p className="mb-2 indent-0">3.2</p>
<p className="mb-2 indent-0">电子档案 electronicrecords</p>
<p className="mb-2 indent-0">具有凭证、查考和保存价值并归档保存的电子文件(3.1)。</p>
<p className="mb-2 indent-0">3.3</p>
<p className="mb-2 indent-0">元数据 metadata</p>
<p className="mb-2 indent-0">描述电子文件和电子档案的内容、背景、结构及其管理过程的数据。</p>
<p className="mb-2 indent-0">注:改写 GB/T26162.1—2010,定义3.12。</p>
<p className="mb-2 indent-0">3.4</p>
<p className="mb-2 indent-0">组件 component</p>
<p className="mb-2 indent-0">构成电子文件、电子档案且独立存在的一个比特流。</p>
<p className="mb-2 indent-0">[ISO16175.2—2011,3术语和定义]</p>
<p className="mb-2 indent-0">示例:文书类电子档案的组件包括电子公文正文、若干附件、定稿或修改稿、公文处理单等。</p>
<p className="mb-2 indent-0">3.5</p>
<p className="mb-2 indent-0">真实性 authenticity</p>
<p className="mb-2 indent-0">电子文件、电子档案的内容、逻辑结构和形成背景与形成时的原始状况相一致的性质。</p>
<p className="mb-2 indent-0">3.6</p>
<p className="mb-2 indent-0">可靠性 reliability</p>
<p className="mb-2 indent-0">电子文件、电子档案的内容完全和正确地表达其所反映的事务、活动或事实的性质。</p>
<p className="mb-2 indent-0">3.7</p>
<p className="mb-2 indent-0">完整性 integrity</p>
<p className="mb-2 indent-0">电子文件、电子档案的内容、结构和背景信息齐全且没有破坏、变异或丢失的性质。</p>
<p className="mb-2 indent-0">3.8</p>
<p className="mb-2 indent-0">可用性 useability</p>
<p className="mb-2 indent-0">电子文件、电子档案可以被检索、呈现或理解的性质。</p>
<p className="mb-2 indent-0">3.9</p>
<p className="mb-2 indent-0">业务系统 businesssystem</p>
<p className="mb-2 indent-0">形成或管理机构活动数据的计算机信息系统。</p>
<p className="mb-2 indent-0">示例:办公自动化系统、电子商务系统、财务系统、人力资源系统、产品数据管理系 统、网站 系统、电子 邮件 系统 等促</p>
<p className="mb-2 indent-0">进机构事务处理的应用系统。</p>
<p className="mb-2 indent-0">2</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">3.10</p>
<p className="mb-2 indent-0">电子档案管理系统  electronicrecordsmanagementsystem</p>
<p className="mb-2 indent-0">对电子档案(3.2)进行采集(3.11)、归档(3.12)、编目、管理和处置的计算机信息系统。</p>
<p className="mb-2 indent-0">3.11</p>
<p className="mb-2 indent-0">采集 capture</p>
<p className="mb-2 indent-0">对电子文件、电子档案及其元数据进行收集和存储的方法与过程。</p>
<p className="mb-2 indent-0">3.12</p>
<p className="mb-2 indent-0">归档 archiving</p>
<p className="mb-2 indent-0">将具有凭证、查考和保存价值且办理完毕、经系统整理的电子文件(3.1)及其元数据(3.3)管理权限</p>
<p className="mb-2 indent-0">向档案部门提交的过程。</p>
<p className="mb-2 indent-0">3.13</p>
<p className="mb-2 indent-0">移交 transfer</p>
<p className="mb-2 indent-0">按照国家规定将电子档案(3.2)的保管权交给国家档案馆的过程。</p>
<p className="mb-2 indent-0">3.14</p>
<p className="mb-2 indent-0">登记 registration</p>
<p className="mb-2 indent-0">电子档案进入电子档案管理系统(3.10)时赋予电子档案唯一标识符的行为。</p>
<p className="mb-2 indent-0">注:改写 GB/T26162.1—2010,3.18。</p>
<p className="mb-2 indent-0">3.15</p>
<p className="mb-2 indent-0">转换 conversion</p>
<p className="mb-2 indent-0">在维护真实性、完整性和可用性前提下,将电子档案从一种载体转换到另一种载体或从一种格式转</p>
<p className="mb-2 indent-0">换成另一种格式的过程。</p>
<p className="mb-2 indent-0">注:改写 GB/T26162.1—2010,3.7。</p>
<p className="mb-2 indent-0">3.16</p>
<p className="mb-2 indent-0">迁移 migration</p>
<p className="mb-2 indent-0">在维护真实性、完整性和可用性的前提下,将电子档案从一个系统转移到另一个系统的过程。</p>
<p className="mb-2 indent-0">注:改写 GB/T26162.1—2010,3.13。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4 总则</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.1 电子文件归档与电子档案管理应遵循纳 入单 位信 息化 建设 规划、技术 与管 理并 重、便于 利用 和安</h3>
<p className="mb-2 indent-0">全可靠的原则。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.2 应对电子文件、电子档案实施全程和集中管理,确保电子档案的真实性、可靠性、完整性与可用性。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.3 应建立严格的管理制度,明确相关部门 电子 文件 归档 和电 子档 案管 理的 职责 与分 工,主要 包括 以</h3>
<p className="mb-2 indent-0">下四类部门的职责与分工:</p>
<p className="mb-2 indent-0">a) 档案部门负责制定电子文件归档与电子档案管理制度,提出业务系统电子文件归档功能要求,</p>
<p className="mb-2 indent-0">负责电子档案管理系统的建设与应用培训;负责 指导 电子 文件 形成 或办 理部 门按 归档 要求 管</p>
<p className="mb-2 indent-0">理应归档电子文件;负责电子文件归档和电子档案编目、管理和处置等各项工作;</p>
<p className="mb-2 indent-0">b) 电子文件形成或办理部门负责电子文件的收集、整理、著录和移交归档等工作;</p>
<p className="mb-2 indent-0">c) 信息化部门负责依据标准建设业务系统电子文件归档功能,参与电子档案管理系统建设,为电</p>
<p className="mb-2 indent-0">子档案管理提供信息化支持;</p>
<p className="mb-2 indent-0">d) 保密部门负责监督涉密电子文件归档和电子档案的保密管理。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.4 应明确各门类电子文件及其元数据的归档范围、时间、程序、接口和格式等要求。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.5 应执行规范的工作程序,采取必要的技术手段,对电子文件归档和电子档案管理全过程实行监控。</h3>
<p className="mb-2 indent-0">3</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">4.6 应基于安全的网络和离线存储介质实施电子文件归档和电子档案管理。</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5 业务系统与电子档案管理系统</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.1 业务系统电子文件归档功能</h3>
<p className="mb-2 indent-0">5.1.1 应能按6、7、8.1~8.4给出的相关要求形成、收集、整理、归档电子文件及其元数据。</p>
<p className="mb-2 indent-0">5.1.2 应内置电子文件分类方案、保管期限表等工具,支持电子文件形成或办理部门完整收集、整理应</p>
<p className="mb-2 indent-0">归档电子文件及其元数据。</p>
<p className="mb-2 indent-0">5.1.3 应能以单个流式文档集中记录电子文件拟制、办理过程中对其进行的全部修改信息。</p>
<p className="mb-2 indent-0">5.1.4 能按内置规则自动命名、存储电子文件及其组件,保持电子文件内在的有机联系,建立电子文件</p>
<p className="mb-2 indent-0">与元数据之间的关联关系。</p>
<p className="mb-2 indent-0">5.1.5 能按标准生成电子文件及其元数据归档数据包,或向归档接口推送电子文件及其元数据。</p>
<p className="mb-2 indent-0">5.1.6 能对已收集、积累的电子文件的所有操作进行跟踪、审计。</p>
<p className="mb-2 indent-0">5.1.7 需通过业务系统开展电子档案管理活动时,业务系统电子档案管理功能应参照 GB/T29194—</p>
<p className="mb-2 indent-0">2012、ISO16175-3:2010等标准以及5.2给出的要求执行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.2 电子档案管理系统基本功能</h3>
<p className="mb-2 indent-0">5.2.1 电子 档案 管理 系统 基本 功能 和可 选功 能应 参照 GB/T29194—2012、DA/T31、ISO 13028—</p>
<p className="mb-2 indent-0">2010、ISO16175-2:2011等标准以及同级国家综合档案馆的相关要求执行。</p>
<p className="mb-2 indent-0">5.2.2 应具备电子档案管理配置功 能,包括 分类 方案 管理、档号 规则 管理、保管 期限 表管 理、元数 据方</p>
<p className="mb-2 indent-0">案管理、门类定义等功能。</p>
<p className="mb-2 indent-0">5.2.3 应具备电子档案管 理功 能,包括 电子 档案 及其 元数 据的 采集、登记、分类、编目、命名、存储、利</p>
<p className="mb-2 indent-0">用、统计、鉴定、销毁、移交、备份、报表管理等功能。</p>
<p className="mb-2 indent-0">5.2.4 应具备电子档案安全管理功能,包括身份认证、权限管理、跟踪审计、生成固化信息等功能。</p>
<p className="mb-2 indent-0">5.2.5 应具备系统管理功能,包括系统参数管理、系统用户和资源管理、系统功能配置、操作权限分配、</p>
<p className="mb-2 indent-0">事件报告等功能。</p>
<p className="mb-2 indent-0">5.2.6 应具备各 门类 纸质 档案 管理 功能,包括 对电 子档 案和 纸质 档案 同步 编目、排序、编制 档号 等</p>
<p className="mb-2 indent-0">功能。</p>
<p className="mb-2 indent-0">5.2.7 应具备纸质档案数字化以及纸质档案数字副本管理功能。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.3 档案信息化基础设施</h3>
<p className="mb-2 indent-0">5.3.1 档案信息化基础设施和信息安全设施应能保障电子档案管理系统的正常运行,满足电子文件归</p>
<p className="mb-2 indent-0">档与电子档案管理活动的实际需求。</p>
<p className="mb-2 indent-0">5.3.2 应为档案部门配备局域网、政务 网和 互联 网等 网络 基础 设施,网络 性能 应能 适应 各门 类电 子文</p>
<p className="mb-2 indent-0">件、电子档案传输、利用要求。</p>
<p className="mb-2 indent-0">5.3.3 应配备与电子档案管理系统 以及 电子 档案 管理 需求 相适 应的 系统 硬件、基础 软件 和存 储、备份</p>
<p className="mb-2 indent-0">等设备。</p>
<p className="mb-2 indent-0">5.3.4 应配备与电子档案管理系统相适应的安全保障设施,包括杀毒软件、防火墙等设备。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">5.4 电子档案管理系统安全管理</h3>
<p className="mb-2 indent-0">5.4.1 电子档案管理系统安全管理应参照《档案信息系统安全等级保护定级工作指南》、涉密计算机信</p>
<p className="mb-2 indent-0">息系统分级保护等规定执行。</p>
<p className="mb-2 indent-0">5.4.2 应建立电子档案管理系统安全管理制度,明确管理职责和要求,规范操作行为。</p>
<p className="mb-2 indent-0">4</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">5.4.3 电子档案管理系统以及档案 信息 化基 础设 施、信息 安全 设施 等各 种设 备的 选型、采购 应符 合国</p>
<p className="mb-2 indent-0">家有关信息安全和知识产权保护等方面的规定。</p>
<p className="mb-2 indent-0">5.4.4 支撑电子档案管理系统运行的网络应与互联网物理隔离,与互联网设备之间的数据传输应通过</p>
<p className="mb-2 indent-0">一次性写入光盘实施。</p>
<p className="mb-2 indent-0">5.4.5 严格管理电子档案管理系统 的专 用离 线存 储介 质及 其用 户,定期 查杀 病毒,监控 非授 权用 户的</p>
<p className="mb-2 indent-0">登录与操作行为。</p>
<p className="mb-2 indent-0">5.4.6 应制定并实施电子档案管理系统应急处置预案,明确职责分工和保障措施,建立预防预警、应急</p>
<p className="mb-2 indent-0">响应和奖惩等应急处置机制。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6 电子文件归档范围</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.1 电子文件归档范围</h3>
<p className="mb-2 indent-0">6.1.1 反映单位职能活动、具有查考和保存价值的各门类电子文件及其元数据应收集、归档。</p>
<p className="mb-2 indent-0">6.1.2 文书类电子文件归档范围按照《机关文件材料归档范围和档案保管期限规定》《企业文件材料归</p>
<p className="mb-2 indent-0">档范围和档案保管期限规定》等执行。</p>
<p className="mb-2 indent-0">6.1.3 照片、录音、录像等声像类电子文件归档范围参照 GB/T11821—2002执行。</p>
<p className="mb-2 indent-0">6.1.4 科技类电子文件的归档范围按照 GB/T11822—2008、DA/T28—2002等标准执行。</p>
<p className="mb-2 indent-0">6.1.5 各种专业类电子文件归档范围按照国家相关规定执行。</p>
<p className="mb-2 indent-0">6.1.6 邮件类电子文件的归档范围按照 DA/T32—2005等标准执行。</p>
<p className="mb-2 indent-0">6.1.7 网页、社交 媒体 类电 子文 件归 档范 围可 参照 《机关 文件 材料 归档 范围 和档 案保 管期 限规 定 》</p>
<p className="mb-2 indent-0">执行。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">6.2 电子文件元数据归档范围</h3>
<p className="mb-2 indent-0">6.2.1 应归档电子文件元数据应与电子文件一并收集、归档。</p>
<p className="mb-2 indent-0">6.2.2 文书类电子文件应归档元数据按照 DA/T46—2009等标准执行,至少包括:</p>
<p className="mb-2 indent-0">a) 题名、文件编号、责任者、日期、机构或问题、保管 期限、密级、格式 信息、计算 机文 件名、计算 机</p>
<p className="mb-2 indent-0">文件大小、文档创建程序等文件实体元数据;</p>
<p className="mb-2 indent-0">b) 记录有关电子文件拟制、办理活动的业务行为、行为时间和机构人员名 称等 元数 据,应记 录的</p>
<p className="mb-2 indent-0">拟制、办理活动包括:发文的起草、审核、签发、复核、登记、用印、核发 等,收文 的签 收、登记、初</p>
<p className="mb-2 indent-0">审、承办、传阅、催办、答复等。</p>
<p className="mb-2 indent-0">6.2.3 科技、专业、邮件、网页、社交媒体类电子文件应归档元数据可参照6.2.2给出的要求执行。</p>
<p className="mb-2 indent-0">6.2.4 声像类电子文件应归档元数据包括题名、摄影者、录音者、摄像者、人物、地点、业务活动描述、密</p>
<p className="mb-2 indent-0">级、计算机文件名等。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7 电子文件的收集与整理</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.1 电子文件及其元数据的收集</h3>
<p className="mb-2 indent-0">7.1.1 应在业务系统电子文件拟制、办理过程中完成电子文件的收集,声像类电子文件、在单台计算机</p>
<p className="mb-2 indent-0">中经办公、绘图等应用软件形成的电子文件的收集由电子文件形成部门基于 电子 档案 管理 系统 或手 工</p>
<p className="mb-2 indent-0">完成。</p>
<p className="mb-2 indent-0">7.1.2 应齐全、完整地收集电子文件及其组件,电子文件内容信息与其形成时保持一致,包括但不限于</p>
<p className="mb-2 indent-0">以下6个方面的要求:</p>
<p className="mb-2 indent-0">5</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">a) 同一业务活动形成的电子文件应齐全、完整;</p>
<p className="mb-2 indent-0">b) 电子公文的正本、正文与附件、定稿或修改稿、公文处理单等应齐全、完整,电子 公文 格式 要素</p>
<p className="mb-2 indent-0">符合 GB/T9704—2012的有关要求;</p>
<p className="mb-2 indent-0">c) 在计算机辅助设计和制造过程中形成的 产品 模型 图、装配 图、工程 图、物料 清单、工艺 卡片、设</p>
<p className="mb-2 indent-0">计与工艺变更通知等电子文件及其组件应齐全、完整;</p>
<p className="mb-2 indent-0">d) 声像类电子文件应能客观、完整地反映业务活动的主要内容、人物和场景等;</p>
<p className="mb-2 indent-0">e) 邮件、网页、社交媒体类电子文件的文字信 息、图像、动画、音视 频文 件等 应齐 全、完整,网页 版</p>
<p className="mb-2 indent-0">面格式保持不变。需收集、归档完整的网站系统时,应同时收集网站设计文件、维护手册等;</p>
<p className="mb-2 indent-0">f) 以专有格式存储的电子文件不能转换 为通 用格 式时,应同 时收 集专 用软 件、技术 资料、操作 手</p>
<p className="mb-2 indent-0">册等。</p>
<p className="mb-2 indent-0">7.1.3 以公务电 子邮 件附 件形 式传 输、交换 的电 子文 件,应下 载并 收集、归入 业务 系统 或存 储文 件</p>
<p className="mb-2 indent-0">夹中。</p>
<p className="mb-2 indent-0">7.1.4 应由业务系统按照6.2.2、6.2.3给出的 要求,在电 子文 件拟 制、办理 过程 中采 集文 书、科技、专业</p>
<p className="mb-2 indent-0">等类电子文件元数据。</p>
<p className="mb-2 indent-0">7.1.5 可使用 WPS表格或电子档案管理系统按照6.2.2a)、6.2.4给出的要求著录、采集在单台计算机</p>
<p className="mb-2 indent-0">中经办公、绘图等应用软件形成的各门类电子文件元数据,以及声像类电子文件元数据。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">7.2 电子文件的整理</h3>
<p className="mb-2 indent-0">7.2.1 应在电子文件拟制、办理或收 集过 程中 完成 保管 期限 鉴定、分类、排序、命名、存储 等整 理活 动,</p>
<p className="mb-2 indent-0">并同步完成会议记录、涉密文件等纸质文件的整理。</p>
<p className="mb-2 indent-0">7.2.2 应以件为管理单位整理电子文件,也可根据实际以卷为管理单位进行整理。整理活动应保持电</p>
<p className="mb-2 indent-0">子文件内在的有机联系,建立电子文件与元数据的关联。</p>
<p className="mb-2 indent-0">7.2.3 应基于业务系统完成电子文 件、纸质 文件 的整 理,声像 类电 子文 件的 整理 由电 子文 件形 成部 门</p>
<p className="mb-2 indent-0">基于电子档案管理系统或手工完成。</p>
<p className="mb-2 indent-0">7.2.4 应归档电子文件保管期限分为永久、定期30年和定期10年等。</p>
<p className="mb-2 indent-0">7.2.5 电子文件分类按照电子档案分类方案执行,可执行的标准或分类方案有:</p>
<p className="mb-2 indent-0">a) 文书类电子文件的分类整理按照 DA/T22执行;</p>
<p className="mb-2 indent-0">b) 科技类电子文件应 按照 GB/T11822—2008、DA/T28—2002、《企业 文件 材料 归档 范围 和档</p>
<p className="mb-2 indent-0">案保管期限规定》等进行分类;</p>
<p className="mb-2 indent-0">c) 专业、邮件、网页、社交媒体等类电子文件可参照 DA/T22等要求进行分类。有其他专门规定</p>
<p className="mb-2 indent-0">的,从其规定;</p>
<p className="mb-2 indent-0">d) 声像类电子文件应按照年 度———保管 期限———业务 活动,或保 管期 限———年度———业务 活动</p>
<p className="mb-2 indent-0">等分类方案进行分类。</p>
<p className="mb-2 indent-0">7.2.6 应在整理过程中基于业务系统电子文件元数据库建立纸质文件目录数据,涉密纸质文件目录数</p>
<p className="mb-2 indent-0">据的录入应符合国家保密管理要求,目录数据项参照6.2.2a)给出的要求执行。</p>
<p className="mb-2 indent-0">7.2.7 应在分类方案下按照业务活动、形成时间等关键字,对电子文件元数据、纸质文件目录数据进行</p>
<p className="mb-2 indent-0">同步排序,排序结果应能保持电子文件、纸质文件之间的有机联系。</p>
<p className="mb-2 indent-0">7.2.8 应按规则命名电子文件,命名 规则 应能 保持 电子 文件 及其 组件 的内 在有 机联 系与 排列 顺序,能</p>
<p className="mb-2 indent-0">通过计算机文件名元数据建立电子文件与相应元数据的关联,具体要求如下:</p>
<p className="mb-2 indent-0">a) 应由业务系统按内置命名规则自动、有序地为电子文件及其组件命名;</p>
<p className="mb-2 indent-0">b) 在单台计算机中经办公、绘图等类应用软件形成的电子文件,应采用完 整、准确 的电 子文 件题</p>
<p className="mb-2 indent-0">名命名;</p>
<p className="mb-2 indent-0">c) 声像类电子文件可采用数字摄录设备自动赋予的计算机文件名。</p>
<p className="mb-2 indent-0">6</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">7.2.9 可参照分类方案在计算机存储器中建立文件夹集中存储电子文件及其组件,完成整理活动。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8 电子文件归档与电子档案编目</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.1 电子文件归档程序与要求</h3>
<p className="mb-2 indent-0">8.1.1 电子文件形成或办理部门、档案 部门 可在 归档 过程 中基 于业 务系 统、电子 档案 管理 系统 完成 电</p>
<p className="mb-2 indent-0">子文件及其元数据的清点、鉴定、登记、填写电子文件归档登记表(见表 A.1)等主要归档程序。</p>
<p className="mb-2 indent-0">8.1.2 应清点、核实电子文件的门类、形成年度、保管期限、件数及其元数据数量等。</p>
<p className="mb-2 indent-0">8.1.3 应对电子文件的真实性、可靠性、完整性和可用性进行鉴定,鉴定合格率应达到100%,包括:</p>
<p className="mb-2 indent-0">a) 电子文件及其元数据的形成、收集和归档符合制度要求;</p>
<p className="mb-2 indent-0">b) 电子文件及其元数据能一一对应,数量准确且齐全、完整;</p>
<p className="mb-2 indent-0">c) 电子文件与元数据格式符合8.3、8.4给出的要求;</p>
<p className="mb-2 indent-0">d) 以专有格式归档的,其专用软件、技术资料等齐全、完整;</p>
<p className="mb-2 indent-0">e) 加密电子文件已解密;</p>
<p className="mb-2 indent-0">f) 电子文件及其元数据经安全网络或专用离线存储介质传输、移交;</p>
<p className="mb-2 indent-0">g) 电子文件无病毒,电子文件离线存储介质无病毒、无损伤、可正常使用。</p>
<p className="mb-2 indent-0">8.1.4 档案部门应将清点、鉴定合格 的电 子文 件及 其元 数据 导入 电子 档案 管理 系统 预归 档库,自动 采</p>
<p className="mb-2 indent-0">集电子文件结构元数据,通过计算机文件名建立电子文件与元数据的关联,在管理过程元数据中记录登</p>
<p className="mb-2 indent-0">记行为,登记归档电子文件。</p>
<p className="mb-2 indent-0">8.1.5 应依据清点、鉴定结果,按批次或归档年度填写电子文件 归档 登记 表(见表 A.1),完成 电子 文件</p>
<p className="mb-2 indent-0">的归档。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.2 电子文件归档时间与归档方式</h3>
<p className="mb-2 indent-0">8.2.1 电子文件形成或办理部门应定期将已收集、积累并经过整理的电子文件及其元数据向档案部门</p>
<p className="mb-2 indent-0">提交归档,归档时间最迟不能超过电子文件形成后的第2年6月。</p>
<p className="mb-2 indent-0">8.2.2 应基于安全的网络环境或专 用离 线存 储介 质,采用 在线 归档 或离 线归 档方 式,通过 电子 档案 管</p>
<p className="mb-2 indent-0">理系统客户端或归档接口完成电子文件及其元数据的归档。</p>
<p className="mb-2 indent-0">8.2.3 应结合业务系统、电子档案管 理系 统运 行网 络环 境以 及本 单位 实际,确定 电子 文件 及其 元数 据</p>
<p className="mb-2 indent-0">归档接口并作出书面说明,归档接口通常包括但不限于以下三种:</p>
<p className="mb-2 indent-0">a) webservice 归档接口;</p>
<p className="mb-2 indent-0">b) 中间数据库归档接口;</p>
<p className="mb-2 indent-0">c) 归档电子文件及其元数据的规范存储结构。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.3 电子文件归档格式</h3>
<p className="mb-2 indent-0">8.3.1 电子文件归档格式应具备格式开放、不绑定软硬件、显示一致性、可转换、易于利用等性能,能够</p>
<p className="mb-2 indent-0">支持同级国家综合档案馆向长期保存格式转换。</p>
<p className="mb-2 indent-0">8.3.2 电子文件应以通用格式形成、收集 并归 档,或在 归档 前转 换为 通用 格式。 版式 文件 格式 应按 照</p>
<p className="mb-2 indent-0">DA/T47—2009执行,可采用 PDF、PDF/A 格式。</p>
<p className="mb-2 indent-0">8.3.3 以文本、位图文件形成的文书、科技、专业类电子文件应按以下要求归档:</p>
<p className="mb-2 indent-0">a) 电子公文正本、定稿、公文处理单应以版式文件格式,其他电子文件、电子文件组件可以版式文</p>
<p className="mb-2 indent-0">件、RTF、WPS、DOCX、JPG、TIF、PNG 等通用格式归档;或</p>
<p className="mb-2 indent-0">7</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">b) 电子文件及其组件按顺序合并转换为一个版式文件。</p>
<p className="mb-2 indent-0">8.3.4 在计算机辅助设计与制造过程中形成的科技类电子文件应按以下要求归档:</p>
<p className="mb-2 indent-0">a) 二维矢量文件以 SVG、SWF、WMF、EMF、EPS、DXF 等格式归档;</p>
<p className="mb-2 indent-0">b) 三维矢量文件,需永久保存的应转换为 STEP 格式归档,其他可根据需要按8.3.4a)给出的要</p>
<p className="mb-2 indent-0">求转为二维矢量文件归档。</p>
<p className="mb-2 indent-0">8.3.5 以数据库文件形成的科技、专业 类电 子文 件,应根 据数 据库 表结 构及 电子 档案 管理 要求 转换 为</p>
<p className="mb-2 indent-0">以下格式归档:</p>
<p className="mb-2 indent-0">a) 以 ET、XLS、DBF、XML 等任一格式归档,或</p>
<p className="mb-2 indent-0">b) 参照纸质表单或电子表单版面格式,将应归档数据库数据转换为版式文件归档。</p>
<p className="mb-2 indent-0">8.3.6 照片类电子文件以JPG、TIF 等格式归档;录音类电子文件以 WAV、MP3等格式归档;录像类电</p>
<p className="mb-2 indent-0">子文件以 MPG、MP4、FLV、AVI等格式归档,珍贵且需永久保存的可收集、归档一套 MXF 格式文件。</p>
<p className="mb-2 indent-0">8.3.7 公务电子邮件以 EML 格式,网页、社交媒体类电子文件以 HTML 等格式归档。</p>
<p className="mb-2 indent-0">8.3.8 专用软件生成的电子文件原则上应转换成通用格式归档。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.4 电子文件元数据归档格式</h3>
<p className="mb-2 indent-0">8.4.1 应根据电子文件归档接口以及元数据形成情况确定电子文件元数据归档格式。</p>
<p className="mb-2 indent-0">8.4.2 经业务系统形成的各门类电子文件元数据应根据归档接口确定归档格式:</p>
<p className="mb-2 indent-0">a) 选择8.2.3a)或8.2.3c)所述归档接口时,可以 ET、XLS、DBF、XML 等任一格式归档;</p>
<p className="mb-2 indent-0">b) 选择8.2.3b)所述归档接口时,可与电子文件一并由业务系统数据库推送至中间数据库,也可</p>
<p className="mb-2 indent-0">再由中间数据库导出数据库数据文件。</p>
<p className="mb-2 indent-0">8.4.3 声像类电子文件元数 据、在单 台计 算机 中经 办公、绘图 等应 用软 件形 成的 电子 文件,可以 ET、</p>
<p className="mb-2 indent-0">XLS、DBF 等格式归档。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.5 电子档案的编目</h3>
<p className="mb-2 indent-0">8.5.1 应对电子档案与纸质档案进行同步整理审核、编制档号等编目活动。</p>
<p className="mb-2 indent-0">8.5.2 应对整理阶段划定的电子档案保管期限与分类结果进行审核和确认,对不合理或不准确的应进</p>
<p className="mb-2 indent-0">行修正。</p>
<p className="mb-2 indent-0">8.5.3 应在整理审核基础上,对电子档案、纸质档案重新排序,并依据排序结果编制文件级档号。</p>
<p className="mb-2 indent-0">8.5.4 应采用文件级档号或唯一标识符作为要素为电子档案及其组件重命名,同时更新相应的计算机</p>
<p className="mb-2 indent-0">文件名元数据。</p>
<p className="mb-2 indent-0">8.5.5 应按照 DA/T18—1999以及 6.2.4 给出 的要 求对 电子 档案、纸质 档案 做进 一步 著录,规范、客</p>
<p className="mb-2 indent-0">观、准确地描述主题内容与形式特征。</p>
<p className="mb-2 indent-0">8.5.6 完成整理编目后,应将电子档案及其元数据、纸质档案目录数据归入电子档案管理系统正式库,</p>
<p className="mb-2 indent-0">并参照7.2.9给出的要求分类、有序地存储电子档案及其组件。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">8.6 档号编制要求</h3>
<p className="mb-2 indent-0">8.6.1 应按照 DA/T13—1994等标准以及电子档案全程管理要求确定档号编制规则。</p>
<p className="mb-2 indent-0">8.6.2 应采用同级国家综合档案馆档号编制规则为室藏电子档案、纸质档案编制档号。</p>
<p className="mb-2 indent-0">8.6.3 档号应能唯一标识全宗内任一电子档案或纸质档案。</p>
<p className="mb-2 indent-0">8.6.4 以档号作为电子档案命名要 素时,计算 机文 件名 应能 在计 算机 存储 器中 唯一 标识、有序 存储 全</p>
<p className="mb-2 indent-0">宗内任意一件电子档案及其组件。</p>
<p className="mb-2 indent-0">8</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9 电子档案的管理</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.1 电子档案的存储</h3>
<p className="mb-2 indent-0">9.1.1 应为电子档案及其元数据的安全存储配置与电子档案管理系统相适应的在线存储设备。</p>
<p className="mb-2 indent-0">9.1.2 电子档案管理系统应 依据 档号 等标 识符 构成 要素 在计 算机 存储 器中 逐级 建立 文件 夹,分门 别</p>
<p className="mb-2 indent-0">类、集中有序地存储电子档案及其组件,并在元数据中自动记录电子档案在线存储路径。</p>
<p className="mb-2 indent-0">9.1.3 在线存储系统应实施容错技术方案,定期扫描、诊断硬磁盘,发现问题应及时处置。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.2 电子档案的备份</h3>
<p className="mb-2 indent-0">9.2.1 应结合单位电子档案 管理 和信 息化 建设 实际,在确 保电 子档 案的 真实、完整、可用 和安 全基 础</p>
<p className="mb-2 indent-0">上,统筹制定电子档案备份方案和策略,实施电子档案及其元数据、电子档案管理系统及其配置数据、日</p>
<p className="mb-2 indent-0">志数据等备份管理。</p>
<p className="mb-2 indent-0">9.2.2 电子档案近线备份与灾难备份的基本要求如下:</p>
<p className="mb-2 indent-0">a) 宜采用磁带备份系统进行近线备份,应定期对电子档案及其元数据、电子档案管理系统的配置</p>
<p className="mb-2 indent-0">数据和日志数据等进行全量、增量或差异备份;</p>
<p className="mb-2 indent-0">b) 电子档案数量达到一定量且条件许可时,可实施电子档案管理系统和数据库系统的热备份;</p>
<p className="mb-2 indent-0">c) 本单位建设灾难备份中心时,应将电子档案及其元数据、电子档案管理系统的灾难备份纳入规</p>
<p className="mb-2 indent-0">划之中,进行同步分析、设计和建设。电子档案的灾难备份 和灾 难恢 复应 参照 GB/T20988—</p>
<p className="mb-2 indent-0">2007等标准要求执行。</p>
<p className="mb-2 indent-0">9.2.3 电子档案离线备份的基本要求如下:</p>
<p className="mb-2 indent-0">a) 应采用一次写光盘、磁带、硬磁 盘等 离线 存储 介质,参照 GB/T2828.1—2012、GB/T12628—</p>
<p className="mb-2 indent-0">2008、GB/T17678—1999、DA/T15—1995、DA/T38—2008 等标 准实 施电 子档 案及 其元 数</p>
<p className="mb-2 indent-0">据、电子档案管理系统配置数据、日志数据等的离线备份;</p>
<p className="mb-2 indent-0">b) 电子档案离线存储介质至少应制作一套。可根据异地备份、电子档案珍 贵程 度和 日常 应用 需</p>
<p className="mb-2 indent-0">要等实际情况,制作第二套、第三套离线存储介质,并在装具上标识套别;</p>
<p className="mb-2 indent-0">c) 应对离线存储介质进行规范管理,按规则编制离线存储介质编号,按规范结构存储备份对象和</p>
<p className="mb-2 indent-0">相应的说明文件,标识离线存储介质。禁止在光盘表面粘贴标签;</p>
<p className="mb-2 indent-0">d) 离线存储介质的保管除参照纸质档案保管要求外,还应符合下列条件:</p>
<p className="mb-2 indent-0">———应作防写处理。避免擦、划、触摸记录涂层;</p>
<p className="mb-2 indent-0">———应装盒,竖立存放或平放,避免挤压;</p>
<p className="mb-2 indent-0">———应远离强磁场、强热源,并与有害气体隔离;</p>
<p className="mb-2 indent-0">———保管环境温度选定范围:光盘17 ℃~20 ℃,磁性载体15 ℃~27 ℃;相对湿度选定范围:光</p>
<p className="mb-2 indent-0">盘20%~50%,磁性载体40%~60%。具体要求见 DA/T15—1995、DA/T38—2008。</p>
<p className="mb-2 indent-0">e) 电子档案或电子档案离线存储介质自形成起一年内可送同级国家综合档案馆电子档案中心进</p>
<p className="mb-2 indent-0">行备份;</p>
<p className="mb-2 indent-0">f) 应定期对磁性载体进行抽样检 测,抽样 率不 低于 10%;抽样 检测 过程 中如 果发 现永 久性 误差</p>
<p className="mb-2 indent-0">时应扩大抽检范围或进行100%的检测,并立 即对 发生 永久 性误 差的 磁性 存储 介质 进行 复制</p>
<p className="mb-2 indent-0">或更新;</p>
<p className="mb-2 indent-0">g) 对光盘进行定期检测,检测结果超过三级预警线时应立即实施更新;</p>
<p className="mb-2 indent-0">h) 离线存储介质所采用的技术即将淘汰时,应立即将其中存储的电子档案及其 元数 据等 转换 至</p>
<p className="mb-2 indent-0">新型且性能可靠的离线存储介质之中;</p>
<p className="mb-2 indent-0">i) 确认离线存储介质的复制、更新和转换等管理活动成功时,再按照相关规定对原离线存储介质</p>
<p className="mb-2 indent-0">9</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">实施破坏性销毁。应对离线存储介质管理活动进行登记,登记内容参见表 A.2。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.3 电子档案的利用</h3>
<p className="mb-2 indent-0">9.3.1 电子档案的提供利用应严格遵守国家相关保密规定。</p>
<p className="mb-2 indent-0">9.3.2 应根据工作岗位、职责等要求在电子档案管理系统为利用者设置相应的电子档案利用权限。</p>
<p className="mb-2 indent-0">9.3.3 利用者应在权限允许范围内检索、浏览、复制、下载电子档案、电子档案组件及其元数据。</p>
<p className="mb-2 indent-0">9.3.4 电子档案及其元数据的离线存储介质不得外借,其使用应在档案部门的监控范围内。</p>
<p className="mb-2 indent-0">9.3.5 对电子档案采用在线方式提 供利 用时,应遵 守国 家有 关信 息安 全的 相关 规定,从技 术和 管理 两</p>
<p className="mb-2 indent-0">方面采取严格的管理措施。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.4 电子档案的统计</h3>
<p className="mb-2 indent-0">9.4.1 应按照档案统计年报要求及本单位实际需要对各门类电子档案情况进行统计。</p>
<p className="mb-2 indent-0">9.4.2 可按档案门类、年度、保管期限、密级、卷数、件数、大小、格式、时长、销毁、移交等要素,对室藏电</p>
<p className="mb-2 indent-0">子档案数量等情况进行统计。</p>
<p className="mb-2 indent-0">9.4.3 可按年度、档案门类、保管期 限、卷数、件数、利用 人次、利用 目的、复制、下载 等要 素对 电子 档案</p>
<p className="mb-2 indent-0">利用情况进行统计。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">9.5 电子档案元数据的维护</h3>
<p className="mb-2 indent-0">9.5.1 应基于电子档案管理系统在 电子 档案 管理 全过 程中 持续 开展 电子 档案 元数 据采 集、备份、转换</p>
<p className="mb-2 indent-0">和迁移等管理活动。</p>
<p className="mb-2 indent-0">9.5.2 实施电子档案管理系统升级 或更 新、电子 档案 格式 转换 等管 理活 动时,应自 动采 集新 增的 电子</p>
<p className="mb-2 indent-0">档案背景、结构元数据,包括信息系统描述、格式信息、音频编码标准、视频编码标准、技术参数等。</p>
<p className="mb-2 indent-0">9.5.3 应参照 GB/T26163.1—2010 等标准持续并自动采集电子档案管理过程元数据,应记录的电子</p>
<p className="mb-2 indent-0">档案管理过程包括登记、格式转换、迁移、鉴定、销毁、移交等,具体见8.1.4、10.2.5、10.3.4给出的要求。</p>
<p className="mb-2 indent-0">9.5.4 应通过备份、格式转换、迁移等措施管理电子档案元数据,包括电子文件归档接收的以及归档后</p>
<p className="mb-2 indent-0">形成的电子档案元数据,具体见9.2、10.2、10.3.4给出的要求。</p>
<p className="mb-2 indent-0">9.5.5 应禁止修改电子档案背景、结构和管理过程元数据,对题名、责任者、文件编号、日期、人物、保管</p>
<p className="mb-2 indent-0">期限、密级等元数据的修改应符合管理规定,修改操作应记录于日志文件中。</p>
<p className="mb-2 indent-0">9.5.6 应确保电子档案与其元数据之间的关联关系得到维护。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10 电子档案的处置</h3>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.1 电子档案的鉴定与审查</h3>
<p className="mb-2 indent-0">10.1.1 应定期对电子档案进行销毁鉴定和解密审查,鉴定、审查程序应符合国家有关规定。</p>
<p className="mb-2 indent-0">10.1.2 档案部门应根据本单位档案 保管 期限 表进 行电 子档 案销 毁鉴 定,提出 被鉴 定对 象的 续存 或销</p>
<p className="mb-2 indent-0">毁意见,必要时可协商相关职能部门。销毁鉴定意见经上级领导或主管部门审核、批准后方可实施。</p>
<p className="mb-2 indent-0">10.1.3 电子档案的解密审查应由档案部门、保密部门共同实施,必要时可协商相关职能部门。解密审</p>
<p className="mb-2 indent-0">查意见经上级领导或主管部门审核、批准后方可实施。</p>
<p className="mb-2 indent-0">10.1.4 应根据电子档案所标密级并结合国家有关政策、要求,参照 GB/T7156—2003等标准定期对涉</p>
<p className="mb-2 indent-0">密电子档案进行密级审查,实施解密、延长保密期限或提升密级等处置活动。</p>
<p className="mb-2 indent-0">10.1.5 到期电子档案移交进馆前,应进行解密审查。</p>
<p className="mb-2 indent-0">01</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.2 电子档案的转换与迁移</h3>
<p className="mb-2 indent-0">10.2.1 应在确保电子档案的真实、可靠、完整 和可 用基 础上,参照ISO13008—2012 等标 准实 施电 子</p>
<p className="mb-2 indent-0">档案及其元数据的转换或迁移。</p>
<p className="mb-2 indent-0">10.2.2 出现以下但不限于以下情况时,应实施电子档案及其元数据的转换或迁移:</p>
<p className="mb-2 indent-0">a) 电子档案当前格式将被淘汰或失去技术支持时,应实施电子档案或元数据的格式转换;</p>
<p className="mb-2 indent-0">b) 因技术更新、介质检测不合格等 原因 需更 换离 线存 储介 质时,应实 施电 子档 案或 元数 据离 线</p>
<p className="mb-2 indent-0">存储介质的转换;</p>
<p className="mb-2 indent-0">c) 支撑电子档案管理系统运行的操作系统、数据库管理系统、台式计算机、服务器、磁盘阵列等主</p>
<p className="mb-2 indent-0">要系统硬件、基础软件等设备升级、更新时,应实施电子档案管理系统、电子档案及其元数据的</p>
<p className="mb-2 indent-0">迁移;</p>
<p className="mb-2 indent-0">d) 电子档案管理系统更新时,应实施电子档案及其元数据的迁移。</p>
<p className="mb-2 indent-0">10.2.3 应按照确认转换或迁移需求、评估 转换 或迁 移风 险、制定 转换 或迁 移方 案、审批 转换 或迁 移方</p>
<p className="mb-2 indent-0">案、转换或迁移测试、实施转换或迁移、评估转换或迁移结果、报告转换或迁移结果等步骤实施电子档案</p>
<p className="mb-2 indent-0">及/或元数据的转换或迁移。</p>
<p className="mb-2 indent-0">10.2.4 应在确信转换或迁移活动成 功实 施之 后,根据 本单 位实 际对 转换 或迁 移前 的电 子档 案及 其元</p>
<p className="mb-2 indent-0">数据进行销毁或继续留存的处置。</p>
<p className="mb-2 indent-0">10.2.5 电子档案及其元数据库的转换、迁移活动应记录于电子档案管理过程元数据中,并填写电子档</p>
<p className="mb-2 indent-0">案格式转换与迁移登记表(见表 A.3)。</p>
<p className="mb-2 indent-0">10.2.6 重新对经过格式转换后的电子档案及其元数据进行备份。</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">10.3 电子档案的移交与销毁</h3>
<p className="mb-2 indent-0">10.3.1 保管期限为永久的电子档案 及其 元数 据自 形成 之日 起 5 年内 应向 同级 国家 综合 档案 馆移 交,</p>
<p className="mb-2 indent-0">移交工作按照《电子档案移交与接收办法》和同级国家综合档案馆的要求执行。</p>
<p className="mb-2 indent-0">10.3.2 纸质、银盐感光材料等各门类传统载体档案应以数字副本及其目录数据移交进馆,以确保移交</p>
<p className="mb-2 indent-0">年度内数字档案资源的完整性。纸质档 案数 字化 转换 应按 照 DA/T31、ISO/TR13028—2010 以及 同</p>
<p className="mb-2 indent-0">级国家综合档案馆的要求执行。</p>
<p className="mb-2 indent-0">10.3.3 电子档案的销毁应参照国家关于档案销毁的有关规定与程序执行。</p>
<p className="mb-2 indent-0">10.3.4 应从在线存储设备、异地容灾备份系统中彻底删除应销毁电子档案,电子档案管理系统应在管</p>
<p className="mb-2 indent-0">理过程元数据、日志中自动记录鉴定、销毁活动,将被销毁电子档案的元数据移入销毁数据库。</p>
<p className="mb-2 indent-0">10.3.5 应销毁电子档案的离线存储介质,应对其实施破坏性销毁。实施销毁前,应对备份其中的其他</p>
<p className="mb-2 indent-0">电子档案进行离线存储介质的转换。</p>
<p className="mb-2 indent-0">10.3.6 属于保密范围的电子档案,其销毁应按国家保密规定实施。</p>
<p className="mb-2 indent-0">10.3.7 应填写电子档案销毁登记表(见表 A.4)并归档保存。</p>
<p className="mb-2 indent-0">11</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">附录 A</h3>
<p className="mb-2 indent-0">(资料性附录)</p>
<p className="mb-2 indent-0">登记表格式</p>
<p className="mb-2 indent-0">表 A.1 电子文件归档登记表</p>
<p className="mb-2 indent-0">单位名称</p>
<p className="mb-2 indent-0">归档时间归档电子文件门类</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">归档电子文件数量卷   件张   分钟字节</h3>
<p className="mb-2 indent-0">归档方式    □在线归档   □离线归档</p>
<p className="mb-2 indent-0">检验项目检验结果</p>
<p className="mb-2 indent-0">载体外观检验</p>
<p className="mb-2 indent-0">病毒检验</p>
<p className="mb-2 indent-0">真实性检验</p>
<p className="mb-2 indent-0">可靠性检验</p>
<p className="mb-2 indent-0">完整性检验</p>
<p className="mb-2 indent-0">可用性检验</p>
<p className="mb-2 indent-0">技术方法与相关软件说明</p>
<p className="mb-2 indent-0">登记表、软件、说明资料检验</p>
<p className="mb-2 indent-0">电子文件形成或办理部门(签章)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">档案部门(签章)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">注:归档电子文件门类包括:文书,科技,专业,声像,电子邮件,网页,社交媒体,[其他]。</p>
<p className="mb-2 indent-0">21</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.2 电子档案离线存储介质管理登记表</p>
<p className="mb-2 indent-0">单位名称</p>
<p className="mb-2 indent-0">管理授权</p>
<p className="mb-2 indent-0">责任部门</p>
<p className="mb-2 indent-0">管理类型     □复制    □更新    □转换</p>
<p className="mb-2 indent-0">源介质描述</p>
<p className="mb-2 indent-0">(类型、品牌、参数、数量等)</p>
<p className="mb-2 indent-0">目标介质描述</p>
<p className="mb-2 indent-0">(类型、品牌、参数、数量等)</p>
<p className="mb-2 indent-0">完成情况</p>
<p className="mb-2 indent-0">(操作前后电子档案及其元数据</p>
<p className="mb-2 indent-0">内容、数量等一致性情况)</p>
<p className="mb-2 indent-0">管理起止时间</p>
<p className="mb-2 indent-0">操作者</p>
<p className="mb-2 indent-0">填表人(签名)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">审核人(签名)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">单位(签章)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">31</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.3 电子档案格式转换与迁移登记表</p>
<p className="mb-2 indent-0">单位名称</p>
<p className="mb-2 indent-0">管理授权</p>
<p className="mb-2 indent-0">责任部门</p>
<p className="mb-2 indent-0">管理类型   □格式转换    □迁移</p>
<p className="mb-2 indent-0">源格式或系统描述</p>
<p className="mb-2 indent-0">目标格式或系统描述</p>
<p className="mb-2 indent-0">完成情况</p>
<p className="mb-2 indent-0">(操作前后电子档案及其元数据</p>
<p className="mb-2 indent-0">内容、数量一致性情况等)</p>
<p className="mb-2 indent-0">操作起止时间</p>
<p className="mb-2 indent-0">操作者</p>
<p className="mb-2 indent-0">填表人(签名)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">审核人(签名)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">单位(签章)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">41</p>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">表 A.4 电子档案销毁登记表</p>
<p className="mb-2 indent-0">单位名称</p>
<p className="mb-2 indent-0">销毁授权</p>
<p className="mb-2 indent-0">被销毁电子档案情况</p>
<p className="mb-2 indent-0">(范围、数量、大小等)</p>
<p className="mb-2 indent-0">在线存储内容销毁说明</p>
<p className="mb-2 indent-0">异地容灾备份内容销毁说明</p>
<p className="mb-2 indent-0">离线存储介质销毁说明</p>
<p className="mb-2 indent-0">销毁起止时间</p>
<p className="mb-2 indent-0">操作者</p>
<p className="mb-2 indent-0">填表人(签名)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">审核人(签名)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">单位(签章)</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">年月 日</h3>
<p className="mb-2 indent-0">GB/T 18894—2016</p>
<div className="h-4" />
<p className="mb-2 indent-0">GB/T18894—2016</p>
<h3 className="text-white font-bold text-lg mt-8 mb-4 border-l-4 border-amber-500 pl-4">参考 文献</h3>
<p className="mb-2 indent-0">[1] GB/T26162.1—2010 信息与文献文件管理第1部分:通则(ISO15489-1,IDT)</p>
<p className="mb-2 indent-0">[2] 党政机关公文处理工作条例(中办发[2012]14号)</p>
<p className="mb-2 indent-0">[3] 机关文件材料归档范围和档案保管期限规定(国家档案局令第8号)</p>
<p className="mb-2 indent-0">[4] 企业文件材料归档范围和档案保管期限规定(国家档案局令第10号)</p>
<p className="mb-2 indent-0">[5] 电子档案移交与接收办法(档发[2012]7号)</p>
<p className="mb-2 indent-0">[6] 档案信息系统安全等级保护定级工作指南(档办发[2013]5号)</p>
      </div>
      
      <div className="bg-amber-500/10 border p-8 rounded-3xl border-amber-500/20 mt-16">
          <h3 className="text-xl font-bold text-white mb-4">DigiVoucher 100% 合规落地</h3>
          <p className="text-slate-400 mb-6 leading-relaxed">
              DigiVoucher 系统设计严格遵循 GB/T 18894—2016《电子文件归档与电子档案管理规范》 要求。我们确保您的电子档案管理流程在技术层面上完全对标国标与行标，
              实现全生命周期的合规管控。
          </p>
      </div>
    </RegulationLayout>
  );
};

export default GBT18894Spec;
