-- Input: 数据库引擎
-- Output: 数据库结构初始化/变更
-- Pos: 数据库初始化脚本
-- 一旦我被更新，务必更新我的开头注释，以及所属的文件夹的 md。

-- Dameng DM8 Schema

CREATE TABLE "SYS_ORG" (
  "ID"            VARCHAR(64) NOT NULL PRIMARY KEY,
  "NAME"          VARCHAR(255) NOT NULL,
  "CODE"          VARCHAR(128),
  "PARENT_ID"     VARCHAR(64),
  "TYPE"          VARCHAR(32) DEFAULT 'DEPARTMENT',
  "ORDER_NUM"     INTEGER DEFAULT 0,
  "CREATED_AT"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "DELETED"       INTEGER DEFAULT 0
);
CREATE INDEX "IDX_SYS_ORG_PARENT" ON "SYS_ORG"("PARENT_ID");

CREATE TABLE "SYS_ROLE" (
  "ID"             VARCHAR(64) NOT NULL PRIMARY KEY,
  "NAME"           VARCHAR(255) NOT NULL,
  "CODE"           VARCHAR(128) NOT NULL UNIQUE,
  "ROLE_CATEGORY"  VARCHAR(64),
  "IS_EXCLUSIVE"   BIT DEFAULT 0,
  "DESCRIPTION"    CLOB,
  "PERMISSIONS"    CLOB,
  "DATA_SCOPE"     VARCHAR(32) DEFAULT 'self',
  "TYPE"           VARCHAR(32) DEFAULT 'custom',
  "CREATED_AT"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "DELETED"        INTEGER DEFAULT 0
);

CREATE TABLE "SYS_USER" (
  "ID"               VARCHAR(64) NOT NULL PRIMARY KEY,
  "USERNAME"         VARCHAR(128) NOT NULL UNIQUE,
  "PASSWORD_HASH"    VARCHAR(255) NOT NULL,
  "FULL_NAME"        VARCHAR(255),
  "ORG_CODE"         VARCHAR(128),
  "EMAIL"            VARCHAR(255),
  "PHONE"            VARCHAR(64),
  "AVATAR"           VARCHAR(512),
  "DEPARTMENT_ID"    VARCHAR(64),
  "STATUS"           VARCHAR(32) DEFAULT 'active',
  "LAST_LOGIN_AT"    TIMESTAMP,
  "EMPLOYEE_ID"      VARCHAR(64),
  "JOB_TITLE"        VARCHAR(128),
  "JOIN_DATE"        VARCHAR(32),
  "CREATED_AT"       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT"       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "DELETED"          INTEGER DEFAULT 0
);

CREATE TABLE "SYS_USER_ROLE" (
  "USER_ID"   VARCHAR(64) NOT NULL,
  "ROLE_ID"   VARCHAR(64) NOT NULL,
  PRIMARY KEY ("USER_ID", "ROLE_ID")
);
CREATE INDEX "IDX_SYS_USER_ROLE_USER" ON "SYS_USER_ROLE"("USER_ID");
CREATE INDEX "IDX_SYS_USER_ROLE_ROLE" ON "SYS_USER_ROLE"("ROLE_ID");

CREATE TABLE "SYS_PERMISSION" (
  "ID"            VARCHAR(64) NOT NULL PRIMARY KEY,
  "PERM_KEY"      VARCHAR(128) NOT NULL UNIQUE,
  "LABEL"         VARCHAR(255) NOT NULL,
  "GROUP_NAME"    VARCHAR(128),
  "CREATED_AT"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
